package pinpoint

import (
	"context"
	"errors"
	"fmt"
	"io"
	"sync"
	"sync/atomic"
	"testing"
	"time"

	lru "github.com/hashicorp/golang-lru"
	pb "github.com/pinpoint-apm/pinpoint-go-agent/protobuf"
	"github.com/spaolacci/murmur3"
)

func init() {
	initLogger()
	initConfig()
	initNoopAgent()
	initGoroutine()
	globalAgent = NoopAgent()
}

type agent struct {
	appName     string
	appType     int32
	agentID     string
	agentName   string
	serviceName string
	objName     *objectName

	startTime   int64
	sequence    int64
	agentGrpc   *agentGrpc
	spanGrpc    *spanGrpc
	statGrpc    *statGrpc
	cmdGrpc     *cmdGrpc
	spanChan    chan *spanChunk
	// spanDropMu serializes the queue-full path of enqueueSpan; spanDropCount
	// counts spans discarded there.
	spanDropMu    sync.Mutex
	spanDropCount atomic.Int64

	metaChan    chan interface{}
	urlStatChan chan *urlStat
	statChan    chan *pb.PStatMessage

	errorCache  *lru.Cache
	errorIdGen  int32
	sqlCache    *lru.Cache
	sqlIdGen    int32
	sqlUidCache *lru.Cache
	apiCache    *lru.Cache
	apiIdGen    int32

	config    *Config
	connectWg sync.WaitGroup
	workerWg  sync.WaitGroup
	enable    atomic.Bool
	shutdown  atomic.Bool

	// stopCtx is cancelled when shutdown begins. The shutdown flag above is
	// only polled, so it cannot wake a goroutine already blocked in a
	// reconnect wait; the context can. Created lazily because the agent is
	// built as a struct literal in several places, including test helpers.
	stopOnce   sync.Once
	stopCtx    context.Context
	stopCancel context.CancelFunc

	// grpcMetaCtx caches the outgoing-metadata context (socketId <= 0), whose
	// headers are immutable for the agent's lifetime, so per-send callers reuse
	// it instead of rebuilding the metadata map on every request.
	grpcMetaOnce sync.Once
	grpcMetaCtx  context.Context

	pingTicker    *time.Ticker
	pingDone      chan bool
	statTicker    *time.Ticker
	statDone      chan bool
	urlStatTicker *time.Ticker
	urlStatDone   chan bool
}

type apiMeta struct {
	id         int32
	descriptor string
	apiType    int
}

// apiCacheKey identifies a cached API id by its descriptor and type.
type apiCacheKey struct {
	descriptor string
	apiType    int
}

type stringMeta struct {
	id       int32
	funcName string
}

type sqlMeta struct {
	id  int32
	sql string
}

type sqlUidMeta struct {
	uid []byte
	sql string
}

type exceptionMeta struct {
	txId        TransactionId
	spanId      int64
	uriTemplate string
	exceptions  []*exception
}

type exception struct {
	exceptionId int64
	callstack   *errorWithCallStack
}

const (
	cacheSize        = 1024
	defaultQueueSize = 1024

	defaultSpanBatchSize                  = 50
	defaultSpanBatchFlushInterval         = 1000
	defaultSpanBatchCollectDeadline       = 500
	defaultSpanBatchMaxConcurrentRequests = 10

	// shutdownTimeout bounds how long Shutdown waits for the worker goroutines
	// to drain their queues before abandoning them.
	shutdownTimeout = 3 * time.Second
	// connectGraceTimeout bounds how long Shutdown waits for an in-progress
	// agent registration, in case Shutdown was called too early.
	connectGraceTimeout = 1 * time.Second

	maxSqlSize = 64 * 1024
)

var globalAgent Agent

// GetAgent returns a global Agent created by NewAgent.
func GetAgent() Agent {
	return globalAgent
}

// NewAgent creates an Agent and spawns goroutines that manage spans and statistical data.
// The generated Agent is maintained globally and only one instance is retained.
// The provided config is generated by NewConfig and an error is returned if it is nil.
//
// example:
//
//	opts := []pinpoint.ConfigOption{
//	  pinpoint.WithAppName("GoTestApp"),
//	  pinpoint.WithConfigFile(os.Getenv("HOME") + "/tmp/pinpoint-config.yaml"),
//	}
//	cfg, err := pinpoint.NewConfig(opts...)
//	agent, err := pinpoint.NewAgent(cfg)
func NewAgent(config *Config) (Agent, error) {
	if globalAgent != NoopAgent() {
		return globalAgent, errors.New("agent is already created")
	}
	if config == nil {
		return NoopAgent(), errors.New("configuration is missing")
	}

	logger.setup(config)
	if err := config.checkNameAndID(); err != nil {
		return NoopAgent(), err
	}
	if !config.Bool(CfgEnable) {
		return NoopAgent(), nil
	}

	Log("agent").Infof("new pinpoint agent")
	config.printConfigString()

	agent := &agent{
		appName:     config.objName.applicationName,
		appType:     int32(config.Int(CfgAppType)),
		agentID:     config.objName.agentID,
		agentName:   config.objName.agentName,
		serviceName: config.objName.serviceName,
		objName:     config.objName,
		startTime:   time.Now().UnixNano() / int64(time.Millisecond),
		spanChan:    make(chan *spanChunk, config.Int(CfgSpanQueueSize)),
		metaChan:    make(chan interface{}, config.Int(CfgSpanQueueSize)),
		urlStatChan: make(chan *urlStat, config.Int(CfgSpanQueueSize)),
		statChan:    make(chan *pb.PStatMessage, config.Int(CfgSpanQueueSize)),
		config:      config,
	}

	var err error
	if agent.errorCache, err = lru.New(cacheSize); err != nil {
		return NoopAgent(), err
	}
	if agent.sqlCache, err = lru.New(cacheSize); err != nil {
		return NoopAgent(), err
	}
	if agent.sqlUidCache, err = lru.New(cacheSize); err != nil {
		return NoopAgent(), err
	}
	if agent.apiCache, err = lru.New(cacheSize); err != nil {
		return NoopAgent(), err
	}

	config.AddReloadCallback([]string{CfgLogLevel}, logger.reloadLevel)
	config.AddReloadCallback([]string{CfgLogOutput, CfgLogMaxSize}, logger.reloadOutput)

	if !config.offGrpc {
		agent.connectWg.Add(1)
		go agent.connectGrpcServer()
	}
	globalAgent = agent
	return agent, nil
}

func (agent *agent) connectGrpcServer() {
	var err error
	defer agent.connectWg.Done()

	if agent.agentGrpc, err = newAgentGrpc(agent); err != nil {
		return
	}
	if !agent.agentGrpc.registerAgentWithRetry() {
		return
	}
	if agent.spanGrpc, err = newSpanGrpc(agent); err != nil {
		return
	}
	if agent.statGrpc, err = newStatGrpc(agent); err != nil {
		return
	}
	if agent.cmdGrpc, err = newCommandGrpc(agent); err != nil {
		return
	}

	agent.enable.Store(true)
	agent.workerWg.Add(8)
	go agent.sendPingWorker()
	if agent.config.Bool(CfgSpanBatchEnable) {
		go agent.sendSpanBatchWorker()
	} else {
		go agent.sendSpanWorker()
	}
	go agent.runCommandService()
	go agent.sendMetaWorker()
	go agent.collectAgentStatWorker()
	go agent.collectUrlStatWorker()
	go agent.sendUrlStatWorker()
	go agent.sendStatsWorker()
}

// stopSignal returns a context cancelled when shutdown begins. Reconnect waits
// derive their deadline from it, so a shutdown aborts them instead of holding
// the agent for a whole back-off interval.
func (agent *agent) stopSignal() context.Context {
	agent.stopOnce.Do(func() {
		agent.stopCtx, agent.stopCancel = context.WithCancel(context.Background())
	})
	return agent.stopCtx
}

// signalShutdown marks the agent as shutting down and unblocks the waits that
// are already in progress.
func (agent *agent) signalShutdown() {
	agent.shutdown.Store(true)
	agent.stopSignal() // ensure the context exists before cancelling it
	agent.stopCancel()
}

// waitTimeout waits for wg and reports whether it completed within timeout.
func waitTimeout(wg *sync.WaitGroup, timeout time.Duration) bool {
	done := make(chan struct{})
	go func() {
		wg.Wait()
		close(done)
	}()

	timer := time.NewTimer(timeout)
	defer timer.Stop()

	select {
	case <-done:
		return true
	case <-timer.C:
		return false
	}
}

func (agent *agent) Shutdown() {
	// Give an in-progress registration a moment to finish, in case shutdown was
	// called too early. A registered agent has already released connectWg, so
	// the normal shutdown path pays nothing here.
	waitTimeout(&agent.connectWg, connectGraceTimeout)

	agent.signalShutdown()
	Log("agent").Infof("shutdown pinpoint agent")

	// wait for the grpc connection to be completed
	agent.connectWg.Wait()
	// CompareAndSwap, not Load-then-Store: two concurrent Shutdown calls could
	// both pass a plain check and both reach the close() calls below, panicking
	// on the second close of an already-closed channel. Only the swap winner
	// proceeds.
	if !agent.enable.CompareAndSwap(true, false) {
		return
	}

	globalAgent = NoopAgent()

	close(agent.spanChan)
	close(agent.metaChan)
	close(agent.statChan)
	close(agent.urlStatChan)

	//To terminate the listening state of the command stream,
	//close the command grpc channel first
	if agent.cmdGrpc != nil {
		agent.cmdGrpc.close()
	}

	if !agent.config.offGrpc {
		agent.pingTicker.Stop()
		agent.pingDone <- true
		agent.statTicker.Stop()
		agent.statDone <- true
		agent.urlStatTicker.Stop()
		agent.urlStatDone <- true
	}
	// Bound the drain: a collector outage must not keep the process alive.
	// Abandoned workers are unblocked by the connection close below.
	if !waitTimeout(&agent.workerWg, shutdownTimeout) {
		Log("agent").Warnf("shutdown timeout(%v) exceeded, abandon in-flight workers", shutdownTimeout)
	}

	if agent.agentGrpc != nil {
		agent.agentGrpc.close()
	}
	if agent.spanGrpc != nil {
		agent.spanGrpc.close()
	}
	if agent.statGrpc != nil {
		agent.statGrpc.close()
	}
}

func (agent *agent) NewSpanTracer(operation string, rpcName string) Tracer {
	var tracer Tracer

	if agent.enable.Load() {
		reader := &noopDistributedTracingContextReader{}
		tracer = agent.NewSpanTracerWithReader(operation, rpcName, reader)
	} else {
		tracer = NoopTracer()
	}
	return tracer
}

func (agent *agent) NewSpanTracerWithReader(operation string, rpcName string, reader DistributedTracingContextReader) Tracer {
	if !agent.enable.Load() || reader == nil {
		return NoopTracer()
	}

	sampled := reader.Get(HeaderSampled)
	if sampled == "s0" {
		incrUnSampleCont()
		return newUnSampledSpan(agent, rpcName)
	}

	sampler := agent.config.load().sampler
	tid := reader.Get(HeaderTraceId)
	if tid == "" {
		return agent.samplingSpan(func() bool { return sampler.isNewSampled() }, operation, rpcName, reader)
	} else {
		return agent.samplingSpan(func() bool { return sampler.isContinueSampled() }, operation, rpcName, reader)
	}
}

func (agent *agent) samplingSpan(samplingFunc func() bool, operation string, rpcName string, reader DistributedTracingContextReader) Tracer {
	if samplingFunc() {
		tracer := newSampledSpan(agent, operation, rpcName)
		tracer.Extract(reader)
		return tracer
	} else {
		return newUnSampledSpan(agent, rpcName)
	}
}

func (agent *agent) generateTransactionId() TransactionId {
	// Use the value returned by AddInt64: reading agent.sequence separately
	// races with concurrent increments and could hand two transactions the
	// same sequence (or a torn read on 32-bit).
	seq := atomic.AddInt64(&agent.sequence, 1)
	return TransactionId{agent.agentID, agent.startTime, seq}
}

func (agent *agent) Enable() bool {
	return agent.enable.Load()
}

func (agent *agent) Config() *Config {
	return agent.config
}

func (agent *agent) sendPingWorker() {
	Log("agent").Infof("start ping goroutine")
	defer agent.workerWg.Done()

	agent.pingTicker = time.NewTicker(60 * time.Second)
	agent.pingDone = make(chan bool)
	stream := agent.agentGrpc.newPingStreamWithRetry()

	for agent.enable.Load() {
		err := stream.sendPing()
		if err != nil {
			if err != io.EOF {
				Log("agent").Errorf("send ping - %v", err)
			}

			stream.close()
			stream = agent.agentGrpc.newPingStreamWithRetry()
		}

		select {
		case <-agent.pingDone:
			Log("agent").Infof("end ping goroutine")
			stream.close()
			return
		case t := <-agent.pingTicker.C:
			if IsDebugLogLevelEnabled() {
				Log("agent").Debugf("ping at", t)
			}
		}
	}
}

func (agent *agent) sendSpanWorker() {
	Log("agent").Infof("start span goroutine")
	defer agent.workerWg.Done()

	var (
		skipOldSpan  = bool(false)
		skipBaseTime time.Time
	)

	stream := agent.spanGrpc.newSpanStreamWithRetry()
	for chunk := range agent.spanChan {
		if !agent.enable.Load() {
			break
		}

		if skipOldSpan {
			if chunk.span.startTime.Before(skipBaseTime) {
				continue //skip old span
			} else {
				skipOldSpan = false
			}
		}

		err := stream.sendSpan(chunk)
		if err != nil {
			if err != io.EOF {
				Log("agent").Errorf("send span - %v", err)
			}

			stream.close()
			stream = agent.spanGrpc.newSpanStreamWithRetry()

			skipOldSpan = true
			skipBaseTime = time.Now().Add(-time.Second * 1)
		}
	}

	stream.close()
	Log("agent").Infof("end span goroutine")
}

func (agent *agent) sendSpanBatchWorker() {
	Log("agent").Infof("start span batch goroutine")
	defer agent.workerWg.Done()

	// Drain span chunks into unary SendSpanBatch requests.
	// The first chunk starts a batch, collectSpanBatch opportunistically gathers more chunks,
	// and sendSpanBatchAsync hands the batch to a bounded async sender.
	for {
		chunk, ok := <-agent.spanChan
		if !ok {
			break
		}

		batch, closed := agent.spanGrpc.collectSpanBatch(chunk, agent.spanChan)
		agent.spanGrpc.sendSpanBatchAsync(batch)
		if closed {
			break
		}
	}

	// The span channel is closed during shutdown; wait for already accepted async batches
	// before the worker exits so queued spans get the same best-effort flush.
	agent.spanGrpc.awaitInFlightSpanBatch()
	Log("agent").Infof("end span batch goroutine")
}

func (agent *agent) enqueueSpan(span *spanChunk) bool {
	if !agent.enable.Load() {
		return false
	}

	// Fast path keeps enqueue non-blocking while the queue has capacity.
	select {
	case agent.spanChan <- span:
		return true
	default:
		break
	}

	// When the queue is full, discard the oldest span and enqueue the newest so
	// recent traces are favored under backpressure. The mutex makes the
	// drop-then-send pair atomic against other saturated producers; without it,
	// another producer can fill the freed slot between the recv and the send,
	// losing the new span on top of the dropped one. A fast-path send above can
	// still take the slot, but that span was enqueued, so every drop counted
	// below pairs with exactly one successful enqueue.
	agent.spanDropMu.Lock()
	defer agent.spanDropMu.Unlock()

	for agent.enable.Load() {
		select {
		case agent.spanChan <- span:
			return true
		default:
		}

		select {
		case <-agent.spanChan:
			agent.spanDropCount.Add(1)
			if IsDebugLogLevelEnabled() {
				Log("agent").Debugf("discard oldest span queue size:%d", len(agent.spanChan))
			}
		default:
			// the consumer drained the queue between the two selects; resend
		}
	}
	return false
}

func (agent *agent) sendMetaWorker() {
	Log("agent").Infof("start meta goroutine")
	defer agent.workerWg.Done()

	for md := range agent.metaChan {
		if !agent.enable.Load() {
			break
		}

		var success bool
		switch md.(type) {
		case apiMeta:
			api := md.(apiMeta)
			success = agent.agentGrpc.sendApiMetadataWithRetry(api.id, api.descriptor, -1, api.apiType)
			break
		case stringMeta:
			str := md.(stringMeta)
			success = agent.agentGrpc.sendStringMetadataWithRetry(str.id, str.funcName)
			break
		case sqlMeta:
			sql := md.(sqlMeta)
			success = agent.agentGrpc.sendSqlMetadataWithRetry(sql.id, sql.sql)
			break
		case sqlUidMeta:
			sql := md.(sqlUidMeta)
			success = agent.agentGrpc.sendSqlUidMetadataWithRetry(sql.uid, sql.sql)
			break
		case exceptionMeta:
			em := md.(exceptionMeta)
			success = agent.agentGrpc.sendExceptionMetadataWithRetry(&em)
		}

		if !success {
			agent.deleteMetaCache(md)
		}
	}

	Log("agent").Infof("end meta goroutine")
}

func (agent *agent) deleteMetaCache(md interface{}) {
	switch md.(type) {
	case apiMeta:
		api := md.(apiMeta)
		agent.apiCache.Remove(apiCacheKey{api.descriptor, api.apiType})
		break
	case stringMeta:
		agent.errorCache.Remove(md.(stringMeta).funcName)
		break
	case sqlMeta:
		agent.sqlCache.Remove(md.(sqlMeta).sql)
		break
	case sqlUidMeta:
		agent.sqlUidCache.Remove(md.(sqlUidMeta).sql)
		break
	case exceptionMeta:
		break
	}
}

func (agent *agent) tryEnqueueMeta(md interface{}) bool {
	if !agent.enable.Load() {
		return false
	}

	select {
	case agent.metaChan <- md:
		return true
	default:
		break
	}

	select {
	case <-agent.metaChan:
	default:
	}
	return false
}

func (agent *agent) cacheError(errorName string) int32 {
	if !agent.enable.Load() {
		return 0
	}

	if v, ok := agent.errorCache.Peek(errorName); ok {
		return v.(int32)
	}

	id := atomic.AddInt32(&agent.errorIdGen, 1)
	if v, ok, _ := agent.errorCache.PeekOrAdd(errorName, id); ok {
		return v.(int32)
	}

	md := stringMeta{
		id:       id,
		funcName: errorName,
	}
	agent.tryEnqueueMeta(md)

	Log("agent").Infof("cache error id: %d, %s", id, errorName)
	return id
}

func abbreviateString(str string, length int) string {
	if len(str) <= length {
		return str
	}
	return str[:length] + "...(" + fmt.Sprint(length) + ")"
}

func (agent *agent) cacheSql(sql string) int32 {
	if !agent.enable.Load() {
		return 0
	}

	if v, ok := agent.sqlCache.Peek(sql); ok {
		return v.(int32)
	}

	id := atomic.AddInt32(&agent.sqlIdGen, 1)
	if v, ok, _ := agent.sqlCache.PeekOrAdd(sql, id); ok {
		return v.(int32)
	}

	aSql := abbreviateString(sql, maxSqlSize)
	md := sqlMeta{
		id:  id,
		sql: aSql,
	}
	agent.tryEnqueueMeta(md)

	Log("agent").Infof("cache sql id: %d, %s", id, aSql)
	return id
}

func (agent *agent) cacheSqlUid(sql string) []byte {
	if !agent.enable.Load() {
		return nil
	}

	if v, ok := agent.sqlUidCache.Peek(sql); ok {
		return v.([]byte)
	}

	hash := murmur3.New128()
	hash.Write([]byte(sql))
	uid := hash.Sum(nil)
	if v, ok, _ := agent.sqlUidCache.PeekOrAdd(sql, uid); ok {
		return v.([]byte)
	}

	aSql := abbreviateString(sql, maxSqlSize)
	md := sqlUidMeta{
		uid: uid,
		sql: aSql,
	}
	agent.tryEnqueueMeta(md)

	Log("agent").Infof("cache sql uid: %#v, %s", uid, aSql)
	return uid
}

func (agent *agent) cacheSpanApi(descriptor string, apiType int) int32 {
	if !agent.enable.Load() {
		return 0
	}

	key := apiCacheKey{descriptor, apiType}

	if v, ok := agent.apiCache.Peek(key); ok {
		return v.(int32)
	}

	id := atomic.AddInt32(&agent.apiIdGen, 1)
	if v, ok, _ := agent.apiCache.PeekOrAdd(key, id); ok {
		return v.(int32)
	}

	md := apiMeta{
		id:         id,
		descriptor: descriptor,
		apiType:    apiType,
	}
	agent.tryEnqueueMeta(md)

	Log("agent").Infof("cache api id: %d, %s_%d", id, descriptor, apiType)
	return id
}

func (agent *agent) enqueueExceptionMeta(span *span) {
	if !agent.enable.Load() || !span.cfg.errorTraceCallStack {
		return
	}

	md := exceptionMeta{
		txId:       span.txId,
		spanId:     span.spanId,
		exceptions: span.errorChains,
	}
	if span.urlStat != nil {
		md.uriTemplate = span.urlStat.Url
	} else {
		md.uriTemplate = "NULL"
	}

	agent.tryEnqueueMeta(md)
	if IsDebugLogLevelEnabled() {
		Log("agent").Debugf("enqueue exception meta: %v", md)
	}
}

func (agent *agent) enqueueUrlStat(stat *urlStat) bool {
	if !agent.enable.Load() {
		return false
	}

	select {
	case agent.urlStatChan <- stat:
		return true
	default:
		break
	}

	select {
	case <-agent.urlStatChan:
	default:
	}
	if IsTraceLogLevelEnabled() {
		Log("agent").Tracef("url stat channel - max capacity reached or closed")
	}
	return false
}

func (agent *agent) collectUrlStatWorker() {
	Log("agent").Infof("start collect uri stat goroutine")
	defer agent.workerWg.Done()

	agent.initUrlStat()

	for uri := range agent.urlStatChan {
		if !agent.enable.Load() {
			break
		}
		agent.addUrlStatSnapshot(uri)
	}

	Log("agent").Infof("end collect uri stat goroutine")
}

func (agent *agent) sendUrlStatWorker() {
	Log("agent").Infof("start send uri stat goroutine")
	defer agent.workerWg.Done()

	agent.urlStatTicker = time.NewTicker(30 * time.Second)
	agent.urlStatDone = make(chan bool)

	for agent.enable.Load() {
		select {
		case <-agent.urlStatDone:
			Log("agent").Infof("end send uri stat goroutine")
			return
		case <-agent.urlStatTicker.C:
			if agent.config.load().collectUrlStat {
				snapshot := agent.takeUrlStatSnapshot()
				agent.enqueueStat(makePAgentUriStat(snapshot))
			}
		}
	}
}

func (agent *agent) enqueueStat(stat *pb.PStatMessage) bool {
	select {
	case agent.statChan <- stat:
		return true
	default:
		break
	}

	select {
	case <-agent.statChan:
	default:
	}
	return false
}

func (agent *agent) sendStatsWorker() {
	Log("agent").Infof("start send stats goroutine")
	defer agent.workerWg.Done()

	stream := agent.statGrpc.newStatStreamWithRetry()
	for stats := range agent.statChan {
		if !agent.enable.Load() {
			break
		}

		err := stream.sendStats(stats)
		if err != nil {
			if err != io.EOF {
				Log("stats").Errorf("send stats - %v", err)
			}

			stream.close()
			stream = agent.statGrpc.newStatStreamWithRetry()
		}
	}
	stream.close()

	Log("agent").Infof("end send stats goroutine")
}

func NewTestAgent(config *Config, t *testing.T) (Agent, error) {
	config.offGrpc = true
	logger.setup(config)

	if config.objName == nil {
		if err := config.checkNameAndID(); err != nil {
			// Tests may omit required identity fields; fall back to a default
			// v3 identity so the header builder has a non-nil object name.
			config.objName = &objectName{
				version:         nameV3,
				agentID:         config.String(CfgAgentID),
				agentName:       config.String(CfgAgentName),
				applicationName: config.String(CfgAppName),
			}
		}
	}

	agent := &agent{
		appName:     config.objName.applicationName,
		appType:     int32(config.Int(CfgAppType)),
		agentID:     config.objName.agentID,
		agentName:   config.objName.agentName,
		serviceName: config.objName.serviceName,
		objName:     config.objName,
		startTime:   time.Now().UnixNano() / int64(time.Millisecond),
		spanChan:    make(chan *spanChunk, config.Int(CfgSpanQueueSize)),
		metaChan:    make(chan interface{}, config.Int(CfgSpanQueueSize)),
		urlStatChan: make(chan *urlStat, config.Int(CfgSpanQueueSize)),
		statChan:    make(chan *pb.PStatMessage, config.Int(CfgSpanQueueSize)),
		config:      config,
	}
	agent.errorCache, _ = lru.New(cacheSize)
	agent.sqlCache, _ = lru.New(cacheSize)
	agent.sqlUidCache, _ = lru.New(cacheSize)
	agent.apiCache, _ = lru.New(cacheSize)

	agent.agentGrpc = newMockAgentGrpc(agent, t)
	//agent.spanGrpc = newMockSpanGrpc(agent, t)
	//agent.statGrpc = newMockStatGrpc(agent, t)

	globalAgent = agent
	agent.enable.Store(true)

	return agent, nil
}
