// Code generated by protoc-gen-go-grpcmock. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpcmock dev
// - protoc                 v7.36.1
// - testify                v1.8.4
// source: v1/Service.proto

package grpcmock

import (
	context "context"
	protobuf "github.com/pinpoint-apm/pinpoint-go-agent/protobuf"
	mock "github.com/stretchr/testify/mock"
	grpc "google.golang.org/grpc"
	metadata "google.golang.org/grpc/metadata"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

func AnySpan_SendSpanClient() mock.AnythingOfTypeArgument {
	return mock.AnythingOfType("*grpcmock.Span_SendSpanClient")
}

func AnySpan_SendSpanServer() mock.AnythingOfTypeArgument {
	return mock.AnythingOfType("*grpcmock.Span_SendSpanServer")
}

type MockSpanClient struct {
	mock.Mock
}

func NewMockSpanClient() *MockSpanClient {
	return &MockSpanClient{}
}

// Deprecated: Do not use.
func (c *MockSpanClient) SendSpan(ctx context.Context, opts ...grpc.CallOption) (protobuf.Span_SendSpanClient, error) {
	opts0 := []interface{}{ctx}
	for _, opts1 := range opts {
		opts0 = append(opts0, opts1)
	}
	args := c.Called(opts0...)
	return args.Get(0).(protobuf.Span_SendSpanClient), args.Error(1)
}

func (c *MockSpanClient) OnSendSpan(ctx interface{}, opts ...interface{}) *mock.Call {
	return c.On("SendSpan", append([]interface{}{ctx}, opts...)...)
}

type MockSpan_SendSpanClient struct {
	mock.Mock
}

func NewMockSpan_SendSpanClient() *MockSpan_SendSpanClient {
	return &MockSpan_SendSpanClient{}
}

func (x *MockSpan_SendSpanClient) Header() (metadata.MD, error) {
	args := x.Called()
	return args.Get(0).(metadata.MD), args.Error(1)
}

func (x *MockSpan_SendSpanClient) Trailer() metadata.MD {
	args := x.Called()
	return args.Get(0).(metadata.MD)
}

func (x *MockSpan_SendSpanClient) CloseSend() error {
	args := x.Called()
	return args.Error(0)
}

func (x *MockSpan_SendSpanClient) Context() context.Context {
	args := x.Called()
	return args.Get(0).(context.Context)
}

func (x *MockSpan_SendSpanClient) SendMsg(m interface{}) error {
	args := x.Called(m)
	return args.Error(0)
}

func (x *MockSpan_SendSpanClient) RecvMsg(m interface{}) error {
	args := x.Called(m)
	return args.Error(0)
}

func (x *MockSpan_SendSpanClient) Send(m *protobuf.PSpanMessage) error {
	args := x.Called(m)
	return args.Error(0)
}

func (x *MockSpan_SendSpanClient) OnSend(m interface{}) *mock.Call {
	return x.On("Send", m)
}

func (x *MockSpan_SendSpanClient) CloseAndRecv() (*emptypb.Empty, error) {
	args := x.Called()
	return args.Get(0).(*emptypb.Empty), args.Error(1)
}

func (x *MockSpan_SendSpanClient) OnCloseAndRecv() *mock.Call {
	return x.On("CloseAndRecv")
}

func (c *MockSpanClient) SendSpanBatch(ctx context.Context, in *protobuf.PSpanMessageBatch, opts ...grpc.CallOption) (*protobuf.PSpanResultBatch, error) {
	opts0 := []interface{}{ctx, in}
	for _, opts1 := range opts {
		opts0 = append(opts0, opts1)
	}
	args := c.Called(opts0...)
	return args.Get(0).(*protobuf.PSpanResultBatch), args.Error(1)
}

func (c *MockSpanClient) OnSendSpanBatch(ctx interface{}, in interface{}, opts ...interface{}) *mock.Call {
	return c.On("SendSpanBatch", append([]interface{}{ctx, in}, opts...)...)
}

type MockSpanServer struct {
	mock.Mock
}

func NewMockSpanServer() *MockSpanServer {
	return &MockSpanServer{}
}

// Deprecated: Do not use.
func (s *MockSpanServer) SendSpan(out protobuf.Span_SendSpanServer) error {
	args := s.Called(out)
	return args.Error(0)
}

func (s *MockSpanServer) OnSendSpan(out interface{}) *mock.Call {
	return s.On("SendSpan", out)
}

type MockSpan_SendSpanServer struct {
	mock.Mock
}

func NewMockSpan_SendSpanServer() *MockSpan_SendSpanServer {
	return &MockSpan_SendSpanServer{}
}

func (x *MockSpan_SendSpanServer) SetHeader(md metadata.MD) error {
	args := x.Called(md)
	return args.Error(0)
}

func (x *MockSpan_SendSpanServer) SendHeader(md metadata.MD) error {
	args := x.Called(md)
	return args.Error(0)
}

func (x *MockSpan_SendSpanServer) SetTrailer(md metadata.MD) {
	_ = x.Called(md)
}

func (x *MockSpan_SendSpanServer) Context() context.Context {
	args := x.Called()
	return args.Get(0).(context.Context)
}

func (x *MockSpan_SendSpanServer) SendMsg(m interface{}) error {
	args := x.Called(m)
	return args.Error(0)
}

func (x *MockSpan_SendSpanServer) RecvMsg(m interface{}) error {
	args := x.Called(m)
	return args.Error(0)
}

func (x *MockSpan_SendSpanServer) Recv() (*protobuf.PSpanMessage, error) {
	args := x.Called()
	return args.Get(0).(*protobuf.PSpanMessage), args.Error(1)
}

func (x *MockSpan_SendSpanServer) OnRecv() *mock.Call {
	return x.On("Recv")
}

func (x *MockSpan_SendSpanServer) SendAndClose(m *emptypb.Empty) error {
	args := x.Called(m)
	return args.Error(0)
}

func (x *MockSpan_SendSpanServer) OnSendAndClose(m interface{}) *mock.Call {
	return x.On("SendAndClose", m)
}

func (s *MockSpanServer) SendSpanBatch(ctx context.Context, in *protobuf.PSpanMessageBatch) (*protobuf.PSpanResultBatch, error) {
	args := s.Called(ctx, in)
	return args.Get(0).(*protobuf.PSpanResultBatch), args.Error(1)
}

func (s *MockSpanServer) OnSendSpanBatch(ctx interface{}, in interface{}) *mock.Call {
	return s.On("SendSpanBatch", ctx, in)
}

func AnyAgent_PingSessionClient() mock.AnythingOfTypeArgument {
	return mock.AnythingOfType("*grpcmock.Agent_PingSessionClient")
}

func AnyAgent_PingSessionServer() mock.AnythingOfTypeArgument {
	return mock.AnythingOfType("*grpcmock.Agent_PingSessionServer")
}

type MockAgentClient struct {
	mock.Mock
}

func NewMockAgentClient() *MockAgentClient {
	return &MockAgentClient{}
}

func (c *MockAgentClient) RequestAgentInfo(ctx context.Context, in *protobuf.PAgentInfo, opts ...grpc.CallOption) (*protobuf.PResult, error) {
	opts0 := []interface{}{ctx, in}
	for _, opts1 := range opts {
		opts0 = append(opts0, opts1)
	}
	args := c.Called(opts0...)
	return args.Get(0).(*protobuf.PResult), args.Error(1)
}

func (c *MockAgentClient) OnRequestAgentInfo(ctx interface{}, in interface{}, opts ...interface{}) *mock.Call {
	return c.On("RequestAgentInfo", append([]interface{}{ctx, in}, opts...)...)
}

func (c *MockAgentClient) PingSession(ctx context.Context, opts ...grpc.CallOption) (protobuf.Agent_PingSessionClient, error) {
	opts0 := []interface{}{ctx}
	for _, opts1 := range opts {
		opts0 = append(opts0, opts1)
	}
	args := c.Called(opts0...)
	return args.Get(0).(protobuf.Agent_PingSessionClient), args.Error(1)
}

func (c *MockAgentClient) OnPingSession(ctx interface{}, opts ...interface{}) *mock.Call {
	return c.On("PingSession", append([]interface{}{ctx}, opts...)...)
}

type MockAgent_PingSessionClient struct {
	mock.Mock
}

func NewMockAgent_PingSessionClient() *MockAgent_PingSessionClient {
	return &MockAgent_PingSessionClient{}
}

func (x *MockAgent_PingSessionClient) Header() (metadata.MD, error) {
	args := x.Called()
	return args.Get(0).(metadata.MD), args.Error(1)
}

func (x *MockAgent_PingSessionClient) Trailer() metadata.MD {
	args := x.Called()
	return args.Get(0).(metadata.MD)
}

func (x *MockAgent_PingSessionClient) CloseSend() error {
	args := x.Called()
	return args.Error(0)
}

func (x *MockAgent_PingSessionClient) Context() context.Context {
	args := x.Called()
	return args.Get(0).(context.Context)
}

func (x *MockAgent_PingSessionClient) SendMsg(m interface{}) error {
	args := x.Called(m)
	return args.Error(0)
}

func (x *MockAgent_PingSessionClient) RecvMsg(m interface{}) error {
	args := x.Called(m)
	return args.Error(0)
}

func (x *MockAgent_PingSessionClient) Send(m *protobuf.PPing) error {
	args := x.Called(m)
	return args.Error(0)
}

func (x *MockAgent_PingSessionClient) OnSend(m interface{}) *mock.Call {
	return x.On("Send", m)
}

func (x *MockAgent_PingSessionClient) Recv() (*protobuf.PPing, error) {
	args := x.Called()
	return args.Get(0).(*protobuf.PPing), args.Error(1)
}

func (x *MockAgent_PingSessionClient) OnRecv() *mock.Call {
	return x.On("Recv")
}

type MockAgentServer struct {
	mock.Mock
}

func NewMockAgentServer() *MockAgentServer {
	return &MockAgentServer{}
}

func (s *MockAgentServer) RequestAgentInfo(ctx context.Context, in *protobuf.PAgentInfo) (*protobuf.PResult, error) {
	args := s.Called(ctx, in)
	return args.Get(0).(*protobuf.PResult), args.Error(1)
}

func (s *MockAgentServer) OnRequestAgentInfo(ctx interface{}, in interface{}) *mock.Call {
	return s.On("RequestAgentInfo", ctx, in)
}

func (s *MockAgentServer) PingSession(out protobuf.Agent_PingSessionServer) error {
	args := s.Called(out)
	return args.Error(0)
}

func (s *MockAgentServer) OnPingSession(out interface{}) *mock.Call {
	return s.On("PingSession", out)
}

type MockAgent_PingSessionServer struct {
	mock.Mock
}

func NewMockAgent_PingSessionServer() *MockAgent_PingSessionServer {
	return &MockAgent_PingSessionServer{}
}

func (x *MockAgent_PingSessionServer) SetHeader(md metadata.MD) error {
	args := x.Called(md)
	return args.Error(0)
}

func (x *MockAgent_PingSessionServer) SendHeader(md metadata.MD) error {
	args := x.Called(md)
	return args.Error(0)
}

func (x *MockAgent_PingSessionServer) SetTrailer(md metadata.MD) {
	_ = x.Called(md)
}

func (x *MockAgent_PingSessionServer) Context() context.Context {
	args := x.Called()
	return args.Get(0).(context.Context)
}

func (x *MockAgent_PingSessionServer) SendMsg(m interface{}) error {
	args := x.Called(m)
	return args.Error(0)
}

func (x *MockAgent_PingSessionServer) RecvMsg(m interface{}) error {
	args := x.Called(m)
	return args.Error(0)
}

func (x *MockAgent_PingSessionServer) Recv() (*protobuf.PPing, error) {
	args := x.Called()
	return args.Get(0).(*protobuf.PPing), args.Error(1)
}

func (x *MockAgent_PingSessionServer) OnRecv() *mock.Call {
	return x.On("Recv")
}

func (x *MockAgent_PingSessionServer) Send(m *protobuf.PPing) error {
	args := x.Called(m)
	return args.Error(0)
}

func (x *MockAgent_PingSessionServer) OnSend(m interface{}) *mock.Call {
	return x.On("Send", m)
}

type MockMetadataClient struct {
	mock.Mock
}

func NewMockMetadataClient() *MockMetadataClient {
	return &MockMetadataClient{}
}

func (c *MockMetadataClient) RequestSqlMetaData(ctx context.Context, in *protobuf.PSqlMetaData, opts ...grpc.CallOption) (*protobuf.PResult, error) {
	opts0 := []interface{}{ctx, in}
	for _, opts1 := range opts {
		opts0 = append(opts0, opts1)
	}
	args := c.Called(opts0...)
	return args.Get(0).(*protobuf.PResult), args.Error(1)
}

func (c *MockMetadataClient) OnRequestSqlMetaData(ctx interface{}, in interface{}, opts ...interface{}) *mock.Call {
	return c.On("RequestSqlMetaData", append([]interface{}{ctx, in}, opts...)...)
}

func (c *MockMetadataClient) RequestSqlUidMetaData(ctx context.Context, in *protobuf.PSqlUidMetaData, opts ...grpc.CallOption) (*protobuf.PResult, error) {
	opts0 := []interface{}{ctx, in}
	for _, opts1 := range opts {
		opts0 = append(opts0, opts1)
	}
	args := c.Called(opts0...)
	return args.Get(0).(*protobuf.PResult), args.Error(1)
}

func (c *MockMetadataClient) OnRequestSqlUidMetaData(ctx interface{}, in interface{}, opts ...interface{}) *mock.Call {
	return c.On("RequestSqlUidMetaData", append([]interface{}{ctx, in}, opts...)...)
}

func (c *MockMetadataClient) RequestApiMetaData(ctx context.Context, in *protobuf.PApiMetaData, opts ...grpc.CallOption) (*protobuf.PResult, error) {
	opts0 := []interface{}{ctx, in}
	for _, opts1 := range opts {
		opts0 = append(opts0, opts1)
	}
	args := c.Called(opts0...)
	return args.Get(0).(*protobuf.PResult), args.Error(1)
}

func (c *MockMetadataClient) OnRequestApiMetaData(ctx interface{}, in interface{}, opts ...interface{}) *mock.Call {
	return c.On("RequestApiMetaData", append([]interface{}{ctx, in}, opts...)...)
}

func (c *MockMetadataClient) RequestStringMetaData(ctx context.Context, in *protobuf.PStringMetaData, opts ...grpc.CallOption) (*protobuf.PResult, error) {
	opts0 := []interface{}{ctx, in}
	for _, opts1 := range opts {
		opts0 = append(opts0, opts1)
	}
	args := c.Called(opts0...)
	return args.Get(0).(*protobuf.PResult), args.Error(1)
}

func (c *MockMetadataClient) OnRequestStringMetaData(ctx interface{}, in interface{}, opts ...interface{}) *mock.Call {
	return c.On("RequestStringMetaData", append([]interface{}{ctx, in}, opts...)...)
}

func (c *MockMetadataClient) RequestExceptionMetaData(ctx context.Context, in *protobuf.PExceptionMetaData, opts ...grpc.CallOption) (*protobuf.PResult, error) {
	opts0 := []interface{}{ctx, in}
	for _, opts1 := range opts {
		opts0 = append(opts0, opts1)
	}
	args := c.Called(opts0...)
	return args.Get(0).(*protobuf.PResult), args.Error(1)
}

func (c *MockMetadataClient) OnRequestExceptionMetaData(ctx interface{}, in interface{}, opts ...interface{}) *mock.Call {
	return c.On("RequestExceptionMetaData", append([]interface{}{ctx, in}, opts...)...)
}

type MockMetadataServer struct {
	mock.Mock
}

func NewMockMetadataServer() *MockMetadataServer {
	return &MockMetadataServer{}
}

func (s *MockMetadataServer) RequestSqlMetaData(ctx context.Context, in *protobuf.PSqlMetaData) (*protobuf.PResult, error) {
	args := s.Called(ctx, in)
	return args.Get(0).(*protobuf.PResult), args.Error(1)
}

func (s *MockMetadataServer) OnRequestSqlMetaData(ctx interface{}, in interface{}) *mock.Call {
	return s.On("RequestSqlMetaData", ctx, in)
}

func (s *MockMetadataServer) RequestSqlUidMetaData(ctx context.Context, in *protobuf.PSqlUidMetaData) (*protobuf.PResult, error) {
	args := s.Called(ctx, in)
	return args.Get(0).(*protobuf.PResult), args.Error(1)
}

func (s *MockMetadataServer) OnRequestSqlUidMetaData(ctx interface{}, in interface{}) *mock.Call {
	return s.On("RequestSqlUidMetaData", ctx, in)
}

func (s *MockMetadataServer) RequestApiMetaData(ctx context.Context, in *protobuf.PApiMetaData) (*protobuf.PResult, error) {
	args := s.Called(ctx, in)
	return args.Get(0).(*protobuf.PResult), args.Error(1)
}

func (s *MockMetadataServer) OnRequestApiMetaData(ctx interface{}, in interface{}) *mock.Call {
	return s.On("RequestApiMetaData", ctx, in)
}

func (s *MockMetadataServer) RequestStringMetaData(ctx context.Context, in *protobuf.PStringMetaData) (*protobuf.PResult, error) {
	args := s.Called(ctx, in)
	return args.Get(0).(*protobuf.PResult), args.Error(1)
}

func (s *MockMetadataServer) OnRequestStringMetaData(ctx interface{}, in interface{}) *mock.Call {
	return s.On("RequestStringMetaData", ctx, in)
}

func (s *MockMetadataServer) RequestExceptionMetaData(ctx context.Context, in *protobuf.PExceptionMetaData) (*protobuf.PResult, error) {
	args := s.Called(ctx, in)
	return args.Get(0).(*protobuf.PResult), args.Error(1)
}

func (s *MockMetadataServer) OnRequestExceptionMetaData(ctx interface{}, in interface{}) *mock.Call {
	return s.On("RequestExceptionMetaData", ctx, in)
}

func AnyStat_SendAgentStatClient() mock.AnythingOfTypeArgument {
	return mock.AnythingOfType("*grpcmock.Stat_SendAgentStatClient")
}

func AnyStat_SendAgentStatServer() mock.AnythingOfTypeArgument {
	return mock.AnythingOfType("*grpcmock.Stat_SendAgentStatServer")
}

type MockStatClient struct {
	mock.Mock
}

func NewMockStatClient() *MockStatClient {
	return &MockStatClient{}
}

func (c *MockStatClient) SendAgentStat(ctx context.Context, opts ...grpc.CallOption) (protobuf.Stat_SendAgentStatClient, error) {
	opts0 := []interface{}{ctx}
	for _, opts1 := range opts {
		opts0 = append(opts0, opts1)
	}
	args := c.Called(opts0...)
	return args.Get(0).(protobuf.Stat_SendAgentStatClient), args.Error(1)
}

func (c *MockStatClient) OnSendAgentStat(ctx interface{}, opts ...interface{}) *mock.Call {
	return c.On("SendAgentStat", append([]interface{}{ctx}, opts...)...)
}

type MockStat_SendAgentStatClient struct {
	mock.Mock
}

func NewMockStat_SendAgentStatClient() *MockStat_SendAgentStatClient {
	return &MockStat_SendAgentStatClient{}
}

func (x *MockStat_SendAgentStatClient) Header() (metadata.MD, error) {
	args := x.Called()
	return args.Get(0).(metadata.MD), args.Error(1)
}

func (x *MockStat_SendAgentStatClient) Trailer() metadata.MD {
	args := x.Called()
	return args.Get(0).(metadata.MD)
}

func (x *MockStat_SendAgentStatClient) CloseSend() error {
	args := x.Called()
	return args.Error(0)
}

func (x *MockStat_SendAgentStatClient) Context() context.Context {
	args := x.Called()
	return args.Get(0).(context.Context)
}

func (x *MockStat_SendAgentStatClient) SendMsg(m interface{}) error {
	args := x.Called(m)
	return args.Error(0)
}

func (x *MockStat_SendAgentStatClient) RecvMsg(m interface{}) error {
	args := x.Called(m)
	return args.Error(0)
}

func (x *MockStat_SendAgentStatClient) Send(m *protobuf.PStatMessage) error {
	args := x.Called(m)
	return args.Error(0)
}

func (x *MockStat_SendAgentStatClient) OnSend(m interface{}) *mock.Call {
	return x.On("Send", m)
}

func (x *MockStat_SendAgentStatClient) CloseAndRecv() (*emptypb.Empty, error) {
	args := x.Called()
	return args.Get(0).(*emptypb.Empty), args.Error(1)
}

func (x *MockStat_SendAgentStatClient) OnCloseAndRecv() *mock.Call {
	return x.On("CloseAndRecv")
}

type MockStatServer struct {
	mock.Mock
}

func NewMockStatServer() *MockStatServer {
	return &MockStatServer{}
}

func (s *MockStatServer) SendAgentStat(out protobuf.Stat_SendAgentStatServer) error {
	args := s.Called(out)
	return args.Error(0)
}

func (s *MockStatServer) OnSendAgentStat(out interface{}) *mock.Call {
	return s.On("SendAgentStat", out)
}

type MockStat_SendAgentStatServer struct {
	mock.Mock
}

func NewMockStat_SendAgentStatServer() *MockStat_SendAgentStatServer {
	return &MockStat_SendAgentStatServer{}
}

func (x *MockStat_SendAgentStatServer) SetHeader(md metadata.MD) error {
	args := x.Called(md)
	return args.Error(0)
}

func (x *MockStat_SendAgentStatServer) SendHeader(md metadata.MD) error {
	args := x.Called(md)
	return args.Error(0)
}

func (x *MockStat_SendAgentStatServer) SetTrailer(md metadata.MD) {
	_ = x.Called(md)
}

func (x *MockStat_SendAgentStatServer) Context() context.Context {
	args := x.Called()
	return args.Get(0).(context.Context)
}

func (x *MockStat_SendAgentStatServer) SendMsg(m interface{}) error {
	args := x.Called(m)
	return args.Error(0)
}

func (x *MockStat_SendAgentStatServer) RecvMsg(m interface{}) error {
	args := x.Called(m)
	return args.Error(0)
}

func (x *MockStat_SendAgentStatServer) Recv() (*protobuf.PStatMessage, error) {
	args := x.Called()
	return args.Get(0).(*protobuf.PStatMessage), args.Error(1)
}

func (x *MockStat_SendAgentStatServer) OnRecv() *mock.Call {
	return x.On("Recv")
}

func (x *MockStat_SendAgentStatServer) SendAndClose(m *emptypb.Empty) error {
	args := x.Called(m)
	return args.Error(0)
}

func (x *MockStat_SendAgentStatServer) OnSendAndClose(m interface{}) *mock.Call {
	return x.On("SendAndClose", m)
}

func AnyProfilerCommandService_HandleCommandClient() mock.AnythingOfTypeArgument {
	return mock.AnythingOfType("*grpcmock.ProfilerCommandService_HandleCommandClient")
}

func AnyProfilerCommandService_HandleCommandServer() mock.AnythingOfTypeArgument {
	return mock.AnythingOfType("*grpcmock.ProfilerCommandService_HandleCommandServer")
}

func AnyProfilerCommandService_HandleCommandV2Client() mock.AnythingOfTypeArgument {
	return mock.AnythingOfType("*grpcmock.ProfilerCommandService_HandleCommandV2Client")
}

func AnyProfilerCommandService_HandleCommandV2Server() mock.AnythingOfTypeArgument {
	return mock.AnythingOfType("*grpcmock.ProfilerCommandService_HandleCommandV2Server")
}

func AnyProfilerCommandService_CommandStreamActiveThreadCountClient() mock.AnythingOfTypeArgument {
	return mock.AnythingOfType("*grpcmock.ProfilerCommandService_CommandStreamActiveThreadCountClient")
}

func AnyProfilerCommandService_CommandStreamActiveThreadCountServer() mock.AnythingOfTypeArgument {
	return mock.AnythingOfType("*grpcmock.ProfilerCommandService_CommandStreamActiveThreadCountServer")
}

type MockProfilerCommandServiceClient struct {
	mock.Mock
}

func NewMockProfilerCommandServiceClient() *MockProfilerCommandServiceClient {
	return &MockProfilerCommandServiceClient{}
}

// Deprecated: Do not use.
func (c *MockProfilerCommandServiceClient) HandleCommand(ctx context.Context, opts ...grpc.CallOption) (protobuf.ProfilerCommandService_HandleCommandClient, error) {
	opts0 := []interface{}{ctx}
	for _, opts1 := range opts {
		opts0 = append(opts0, opts1)
	}
	args := c.Called(opts0...)
	return args.Get(0).(protobuf.ProfilerCommandService_HandleCommandClient), args.Error(1)
}

func (c *MockProfilerCommandServiceClient) OnHandleCommand(ctx interface{}, opts ...interface{}) *mock.Call {
	return c.On("HandleCommand", append([]interface{}{ctx}, opts...)...)
}

type MockProfilerCommandService_HandleCommandClient struct {
	mock.Mock
}

func NewMockProfilerCommandService_HandleCommandClient() *MockProfilerCommandService_HandleCommandClient {
	return &MockProfilerCommandService_HandleCommandClient{}
}

func (x *MockProfilerCommandService_HandleCommandClient) Header() (metadata.MD, error) {
	args := x.Called()
	return args.Get(0).(metadata.MD), args.Error(1)
}

func (x *MockProfilerCommandService_HandleCommandClient) Trailer() metadata.MD {
	args := x.Called()
	return args.Get(0).(metadata.MD)
}

func (x *MockProfilerCommandService_HandleCommandClient) CloseSend() error {
	args := x.Called()
	return args.Error(0)
}

func (x *MockProfilerCommandService_HandleCommandClient) Context() context.Context {
	args := x.Called()
	return args.Get(0).(context.Context)
}

func (x *MockProfilerCommandService_HandleCommandClient) SendMsg(m interface{}) error {
	args := x.Called(m)
	return args.Error(0)
}

func (x *MockProfilerCommandService_HandleCommandClient) RecvMsg(m interface{}) error {
	args := x.Called(m)
	return args.Error(0)
}

func (x *MockProfilerCommandService_HandleCommandClient) Send(m *protobuf.PCmdMessage) error {
	args := x.Called(m)
	return args.Error(0)
}

func (x *MockProfilerCommandService_HandleCommandClient) OnSend(m interface{}) *mock.Call {
	return x.On("Send", m)
}

func (x *MockProfilerCommandService_HandleCommandClient) Recv() (*protobuf.PCmdRequest, error) {
	args := x.Called()
	return args.Get(0).(*protobuf.PCmdRequest), args.Error(1)
}

func (x *MockProfilerCommandService_HandleCommandClient) OnRecv() *mock.Call {
	return x.On("Recv")
}

func (c *MockProfilerCommandServiceClient) HandleCommandV2(ctx context.Context, opts ...grpc.CallOption) (protobuf.ProfilerCommandService_HandleCommandV2Client, error) {
	opts0 := []interface{}{ctx}
	for _, opts1 := range opts {
		opts0 = append(opts0, opts1)
	}
	args := c.Called(opts0...)
	return args.Get(0).(protobuf.ProfilerCommandService_HandleCommandV2Client), args.Error(1)
}

func (c *MockProfilerCommandServiceClient) OnHandleCommandV2(ctx interface{}, opts ...interface{}) *mock.Call {
	return c.On("HandleCommandV2", append([]interface{}{ctx}, opts...)...)
}

type MockProfilerCommandService_HandleCommandV2Client struct {
	mock.Mock
}

func NewMockProfilerCommandService_HandleCommandV2Client() *MockProfilerCommandService_HandleCommandV2Client {
	return &MockProfilerCommandService_HandleCommandV2Client{}
}

func (x *MockProfilerCommandService_HandleCommandV2Client) Header() (metadata.MD, error) {
	args := x.Called()
	return args.Get(0).(metadata.MD), args.Error(1)
}

func (x *MockProfilerCommandService_HandleCommandV2Client) Trailer() metadata.MD {
	args := x.Called()
	return args.Get(0).(metadata.MD)
}

func (x *MockProfilerCommandService_HandleCommandV2Client) CloseSend() error {
	args := x.Called()
	return args.Error(0)
}

func (x *MockProfilerCommandService_HandleCommandV2Client) Context() context.Context {
	args := x.Called()
	return args.Get(0).(context.Context)
}

func (x *MockProfilerCommandService_HandleCommandV2Client) SendMsg(m interface{}) error {
	args := x.Called(m)
	return args.Error(0)
}

func (x *MockProfilerCommandService_HandleCommandV2Client) RecvMsg(m interface{}) error {
	args := x.Called(m)
	return args.Error(0)
}

func (x *MockProfilerCommandService_HandleCommandV2Client) Send(m *protobuf.PCmdMessage) error {
	args := x.Called(m)
	return args.Error(0)
}

func (x *MockProfilerCommandService_HandleCommandV2Client) OnSend(m interface{}) *mock.Call {
	return x.On("Send", m)
}

func (x *MockProfilerCommandService_HandleCommandV2Client) Recv() (*protobuf.PCmdRequest, error) {
	args := x.Called()
	return args.Get(0).(*protobuf.PCmdRequest), args.Error(1)
}

func (x *MockProfilerCommandService_HandleCommandV2Client) OnRecv() *mock.Call {
	return x.On("Recv")
}

func (c *MockProfilerCommandServiceClient) CommandEcho(ctx context.Context, in *protobuf.PCmdEchoResponse, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	opts0 := []interface{}{ctx, in}
	for _, opts1 := range opts {
		opts0 = append(opts0, opts1)
	}
	args := c.Called(opts0...)
	return args.Get(0).(*emptypb.Empty), args.Error(1)
}

func (c *MockProfilerCommandServiceClient) OnCommandEcho(ctx interface{}, in interface{}, opts ...interface{}) *mock.Call {
	return c.On("CommandEcho", append([]interface{}{ctx, in}, opts...)...)
}

func (c *MockProfilerCommandServiceClient) CommandStreamActiveThreadCount(ctx context.Context, opts ...grpc.CallOption) (protobuf.ProfilerCommandService_CommandStreamActiveThreadCountClient, error) {
	opts0 := []interface{}{ctx}
	for _, opts1 := range opts {
		opts0 = append(opts0, opts1)
	}
	args := c.Called(opts0...)
	return args.Get(0).(protobuf.ProfilerCommandService_CommandStreamActiveThreadCountClient), args.Error(1)
}

func (c *MockProfilerCommandServiceClient) OnCommandStreamActiveThreadCount(ctx interface{}, opts ...interface{}) *mock.Call {
	return c.On("CommandStreamActiveThreadCount", append([]interface{}{ctx}, opts...)...)
}

type MockProfilerCommandService_CommandStreamActiveThreadCountClient struct {
	mock.Mock
}

func NewMockProfilerCommandService_CommandStreamActiveThreadCountClient() *MockProfilerCommandService_CommandStreamActiveThreadCountClient {
	return &MockProfilerCommandService_CommandStreamActiveThreadCountClient{}
}

func (x *MockProfilerCommandService_CommandStreamActiveThreadCountClient) Header() (metadata.MD, error) {
	args := x.Called()
	return args.Get(0).(metadata.MD), args.Error(1)
}

func (x *MockProfilerCommandService_CommandStreamActiveThreadCountClient) Trailer() metadata.MD {
	args := x.Called()
	return args.Get(0).(metadata.MD)
}

func (x *MockProfilerCommandService_CommandStreamActiveThreadCountClient) CloseSend() error {
	args := x.Called()
	return args.Error(0)
}

func (x *MockProfilerCommandService_CommandStreamActiveThreadCountClient) Context() context.Context {
	args := x.Called()
	return args.Get(0).(context.Context)
}

func (x *MockProfilerCommandService_CommandStreamActiveThreadCountClient) SendMsg(m interface{}) error {
	args := x.Called(m)
	return args.Error(0)
}

func (x *MockProfilerCommandService_CommandStreamActiveThreadCountClient) RecvMsg(m interface{}) error {
	args := x.Called(m)
	return args.Error(0)
}

func (x *MockProfilerCommandService_CommandStreamActiveThreadCountClient) Send(m *protobuf.PCmdActiveThreadCountRes) error {
	args := x.Called(m)
	return args.Error(0)
}

func (x *MockProfilerCommandService_CommandStreamActiveThreadCountClient) OnSend(m interface{}) *mock.Call {
	return x.On("Send", m)
}

func (x *MockProfilerCommandService_CommandStreamActiveThreadCountClient) CloseAndRecv() (*emptypb.Empty, error) {
	args := x.Called()
	return args.Get(0).(*emptypb.Empty), args.Error(1)
}

func (x *MockProfilerCommandService_CommandStreamActiveThreadCountClient) OnCloseAndRecv() *mock.Call {
	return x.On("CloseAndRecv")
}

func (c *MockProfilerCommandServiceClient) CommandActiveThreadDump(ctx context.Context, in *protobuf.PCmdActiveThreadDumpRes, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	opts0 := []interface{}{ctx, in}
	for _, opts1 := range opts {
		opts0 = append(opts0, opts1)
	}
	args := c.Called(opts0...)
	return args.Get(0).(*emptypb.Empty), args.Error(1)
}

func (c *MockProfilerCommandServiceClient) OnCommandActiveThreadDump(ctx interface{}, in interface{}, opts ...interface{}) *mock.Call {
	return c.On("CommandActiveThreadDump", append([]interface{}{ctx, in}, opts...)...)
}

func (c *MockProfilerCommandServiceClient) CommandActiveThreadLightDump(ctx context.Context, in *protobuf.PCmdActiveThreadLightDumpRes, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	opts0 := []interface{}{ctx, in}
	for _, opts1 := range opts {
		opts0 = append(opts0, opts1)
	}
	args := c.Called(opts0...)
	return args.Get(0).(*emptypb.Empty), args.Error(1)
}

func (c *MockProfilerCommandServiceClient) OnCommandActiveThreadLightDump(ctx interface{}, in interface{}, opts ...interface{}) *mock.Call {
	return c.On("CommandActiveThreadLightDump", append([]interface{}{ctx, in}, opts...)...)
}

type MockProfilerCommandServiceServer struct {
	mock.Mock
}

func NewMockProfilerCommandServiceServer() *MockProfilerCommandServiceServer {
	return &MockProfilerCommandServiceServer{}
}

// Deprecated: Do not use.
func (s *MockProfilerCommandServiceServer) HandleCommand(out protobuf.ProfilerCommandService_HandleCommandServer) error {
	args := s.Called(out)
	return args.Error(0)
}

func (s *MockProfilerCommandServiceServer) OnHandleCommand(out interface{}) *mock.Call {
	return s.On("HandleCommand", out)
}

type MockProfilerCommandService_HandleCommandServer struct {
	mock.Mock
}

func NewMockProfilerCommandService_HandleCommandServer() *MockProfilerCommandService_HandleCommandServer {
	return &MockProfilerCommandService_HandleCommandServer{}
}

func (x *MockProfilerCommandService_HandleCommandServer) SetHeader(md metadata.MD) error {
	args := x.Called(md)
	return args.Error(0)
}

func (x *MockProfilerCommandService_HandleCommandServer) SendHeader(md metadata.MD) error {
	args := x.Called(md)
	return args.Error(0)
}

func (x *MockProfilerCommandService_HandleCommandServer) SetTrailer(md metadata.MD) {
	_ = x.Called(md)
}

func (x *MockProfilerCommandService_HandleCommandServer) Context() context.Context {
	args := x.Called()
	return args.Get(0).(context.Context)
}

func (x *MockProfilerCommandService_HandleCommandServer) SendMsg(m interface{}) error {
	args := x.Called(m)
	return args.Error(0)
}

func (x *MockProfilerCommandService_HandleCommandServer) RecvMsg(m interface{}) error {
	args := x.Called(m)
	return args.Error(0)
}

func (x *MockProfilerCommandService_HandleCommandServer) Recv() (*protobuf.PCmdMessage, error) {
	args := x.Called()
	return args.Get(0).(*protobuf.PCmdMessage), args.Error(1)
}

func (x *MockProfilerCommandService_HandleCommandServer) OnRecv() *mock.Call {
	return x.On("Recv")
}

func (x *MockProfilerCommandService_HandleCommandServer) Send(m *protobuf.PCmdRequest) error {
	args := x.Called(m)
	return args.Error(0)
}

func (x *MockProfilerCommandService_HandleCommandServer) OnSend(m interface{}) *mock.Call {
	return x.On("Send", m)
}

func (s *MockProfilerCommandServiceServer) HandleCommandV2(out protobuf.ProfilerCommandService_HandleCommandV2Server) error {
	args := s.Called(out)
	return args.Error(0)
}

func (s *MockProfilerCommandServiceServer) OnHandleCommandV2(out interface{}) *mock.Call {
	return s.On("HandleCommandV2", out)
}

type MockProfilerCommandService_HandleCommandV2Server struct {
	mock.Mock
}

func NewMockProfilerCommandService_HandleCommandV2Server() *MockProfilerCommandService_HandleCommandV2Server {
	return &MockProfilerCommandService_HandleCommandV2Server{}
}

func (x *MockProfilerCommandService_HandleCommandV2Server) SetHeader(md metadata.MD) error {
	args := x.Called(md)
	return args.Error(0)
}

func (x *MockProfilerCommandService_HandleCommandV2Server) SendHeader(md metadata.MD) error {
	args := x.Called(md)
	return args.Error(0)
}

func (x *MockProfilerCommandService_HandleCommandV2Server) SetTrailer(md metadata.MD) {
	_ = x.Called(md)
}

func (x *MockProfilerCommandService_HandleCommandV2Server) Context() context.Context {
	args := x.Called()
	return args.Get(0).(context.Context)
}

func (x *MockProfilerCommandService_HandleCommandV2Server) SendMsg(m interface{}) error {
	args := x.Called(m)
	return args.Error(0)
}

func (x *MockProfilerCommandService_HandleCommandV2Server) RecvMsg(m interface{}) error {
	args := x.Called(m)
	return args.Error(0)
}

func (x *MockProfilerCommandService_HandleCommandV2Server) Recv() (*protobuf.PCmdMessage, error) {
	args := x.Called()
	return args.Get(0).(*protobuf.PCmdMessage), args.Error(1)
}

func (x *MockProfilerCommandService_HandleCommandV2Server) OnRecv() *mock.Call {
	return x.On("Recv")
}

func (x *MockProfilerCommandService_HandleCommandV2Server) Send(m *protobuf.PCmdRequest) error {
	args := x.Called(m)
	return args.Error(0)
}

func (x *MockProfilerCommandService_HandleCommandV2Server) OnSend(m interface{}) *mock.Call {
	return x.On("Send", m)
}

func (s *MockProfilerCommandServiceServer) CommandEcho(ctx context.Context, in *protobuf.PCmdEchoResponse) (*emptypb.Empty, error) {
	args := s.Called(ctx, in)
	return args.Get(0).(*emptypb.Empty), args.Error(1)
}

func (s *MockProfilerCommandServiceServer) OnCommandEcho(ctx interface{}, in interface{}) *mock.Call {
	return s.On("CommandEcho", ctx, in)
}

func (s *MockProfilerCommandServiceServer) CommandStreamActiveThreadCount(out protobuf.ProfilerCommandService_CommandStreamActiveThreadCountServer) error {
	args := s.Called(out)
	return args.Error(0)
}

func (s *MockProfilerCommandServiceServer) OnCommandStreamActiveThreadCount(out interface{}) *mock.Call {
	return s.On("CommandStreamActiveThreadCount", out)
}

type MockProfilerCommandService_CommandStreamActiveThreadCountServer struct {
	mock.Mock
}

func NewMockProfilerCommandService_CommandStreamActiveThreadCountServer() *MockProfilerCommandService_CommandStreamActiveThreadCountServer {
	return &MockProfilerCommandService_CommandStreamActiveThreadCountServer{}
}

func (x *MockProfilerCommandService_CommandStreamActiveThreadCountServer) SetHeader(md metadata.MD) error {
	args := x.Called(md)
	return args.Error(0)
}

func (x *MockProfilerCommandService_CommandStreamActiveThreadCountServer) SendHeader(md metadata.MD) error {
	args := x.Called(md)
	return args.Error(0)
}

func (x *MockProfilerCommandService_CommandStreamActiveThreadCountServer) SetTrailer(md metadata.MD) {
	_ = x.Called(md)
}

func (x *MockProfilerCommandService_CommandStreamActiveThreadCountServer) Context() context.Context {
	args := x.Called()
	return args.Get(0).(context.Context)
}

func (x *MockProfilerCommandService_CommandStreamActiveThreadCountServer) SendMsg(m interface{}) error {
	args := x.Called(m)
	return args.Error(0)
}

func (x *MockProfilerCommandService_CommandStreamActiveThreadCountServer) RecvMsg(m interface{}) error {
	args := x.Called(m)
	return args.Error(0)
}

func (x *MockProfilerCommandService_CommandStreamActiveThreadCountServer) Recv() (*protobuf.PCmdActiveThreadCountRes, error) {
	args := x.Called()
	return args.Get(0).(*protobuf.PCmdActiveThreadCountRes), args.Error(1)
}

func (x *MockProfilerCommandService_CommandStreamActiveThreadCountServer) OnRecv() *mock.Call {
	return x.On("Recv")
}

func (x *MockProfilerCommandService_CommandStreamActiveThreadCountServer) SendAndClose(m *emptypb.Empty) error {
	args := x.Called(m)
	return args.Error(0)
}

func (x *MockProfilerCommandService_CommandStreamActiveThreadCountServer) OnSendAndClose(m interface{}) *mock.Call {
	return x.On("SendAndClose", m)
}

func (s *MockProfilerCommandServiceServer) CommandActiveThreadDump(ctx context.Context, in *protobuf.PCmdActiveThreadDumpRes) (*emptypb.Empty, error) {
	args := s.Called(ctx, in)
	return args.Get(0).(*emptypb.Empty), args.Error(1)
}

func (s *MockProfilerCommandServiceServer) OnCommandActiveThreadDump(ctx interface{}, in interface{}) *mock.Call {
	return s.On("CommandActiveThreadDump", ctx, in)
}

func (s *MockProfilerCommandServiceServer) CommandActiveThreadLightDump(ctx context.Context, in *protobuf.PCmdActiveThreadLightDumpRes) (*emptypb.Empty, error) {
	args := s.Called(ctx, in)
	return args.Get(0).(*emptypb.Empty), args.Error(1)
}

func (s *MockProfilerCommandServiceServer) OnCommandActiveThreadLightDump(ctx interface{}, in interface{}) *mock.Call {
	return s.On("CommandActiveThreadLightDump", ctx, in)
}
