// Code generated by protoc-gen-go-grpcmock. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpcmock dev
// - protoc                 v7.36.1
// - testify                v1.8.4
// source: v1/Log.proto

package grpcmock

import (
	context "context"
	protobuf "github.com/pinpoint-apm/pinpoint-go-agent/protobuf"
	mock "github.com/stretchr/testify/mock"
	grpc "google.golang.org/grpc"
	metadata "google.golang.org/grpc/metadata"
)

func AnyPLogPile() mock.AnythingOfTypeArgument {
	return mock.AnythingOfType("*grpcmock.PLogPile")
}

func AnyPLogRecord() mock.AnythingOfTypeArgument {
	return mock.AnythingOfType("*grpcmock.PLogRecord")
}

func AnyPLogDemand() mock.AnythingOfTypeArgument {
	return mock.AnythingOfType("*grpcmock.PLogDemand")
}

func AnyLog_ConnectClient() mock.AnythingOfTypeArgument {
	return mock.AnythingOfType("*grpcmock.Log_ConnectClient")
}

func AnyLog_ConnectServer() mock.AnythingOfTypeArgument {
	return mock.AnythingOfType("*grpcmock.Log_ConnectServer")
}

type MockLogClient struct {
	mock.Mock
}

func NewMockLogClient() *MockLogClient {
	return &MockLogClient{}
}

func (c *MockLogClient) Connect(ctx context.Context, opts ...grpc.CallOption) (protobuf.Log_ConnectClient, error) {
	opts0 := []interface{}{ctx}
	for _, opts1 := range opts {
		opts0 = append(opts0, opts1)
	}
	args := c.Called(opts0...)
	return args.Get(0).(protobuf.Log_ConnectClient), args.Error(1)
}

func (c *MockLogClient) OnConnect(ctx interface{}, opts ...interface{}) *mock.Call {
	return c.On("Connect", append([]interface{}{ctx}, opts...)...)
}

type MockLog_ConnectClient struct {
	mock.Mock
}

func NewMockLog_ConnectClient() *MockLog_ConnectClient {
	return &MockLog_ConnectClient{}
}

func (x *MockLog_ConnectClient) Header() (metadata.MD, error) {
	args := x.Called()
	return args.Get(0).(metadata.MD), args.Error(1)
}

func (x *MockLog_ConnectClient) Trailer() metadata.MD {
	args := x.Called()
	return args.Get(0).(metadata.MD)
}

func (x *MockLog_ConnectClient) CloseSend() error {
	args := x.Called()
	return args.Error(0)
}

func (x *MockLog_ConnectClient) Context() context.Context {
	args := x.Called()
	return args.Get(0).(context.Context)
}

func (x *MockLog_ConnectClient) SendMsg(m interface{}) error {
	args := x.Called(m)
	return args.Error(0)
}

func (x *MockLog_ConnectClient) RecvMsg(m interface{}) error {
	args := x.Called(m)
	return args.Error(0)
}

func (x *MockLog_ConnectClient) Send(m *protobuf.PLogPile) error {
	args := x.Called(m)
	return args.Error(0)
}

func (x *MockLog_ConnectClient) OnSend(m interface{}) *mock.Call {
	return x.On("Send", m)
}

func (x *MockLog_ConnectClient) Recv() (*protobuf.PLogDemand, error) {
	args := x.Called()
	return args.Get(0).(*protobuf.PLogDemand), args.Error(1)
}

func (x *MockLog_ConnectClient) OnRecv() *mock.Call {
	return x.On("Recv")
}

type MockLogServer struct {
	mock.Mock
}

func NewMockLogServer() *MockLogServer {
	return &MockLogServer{}
}

func (s *MockLogServer) Connect(out protobuf.Log_ConnectServer) error {
	args := s.Called(out)
	return args.Error(0)
}

func (s *MockLogServer) OnConnect(out interface{}) *mock.Call {
	return s.On("Connect", out)
}

type MockLog_ConnectServer struct {
	mock.Mock
}

func NewMockLog_ConnectServer() *MockLog_ConnectServer {
	return &MockLog_ConnectServer{}
}

func (x *MockLog_ConnectServer) SetHeader(md metadata.MD) error {
	args := x.Called(md)
	return args.Error(0)
}

func (x *MockLog_ConnectServer) SendHeader(md metadata.MD) error {
	args := x.Called(md)
	return args.Error(0)
}

func (x *MockLog_ConnectServer) SetTrailer(md metadata.MD) {
	_ = x.Called(md)
}

func (x *MockLog_ConnectServer) Context() context.Context {
	args := x.Called()
	return args.Get(0).(context.Context)
}

func (x *MockLog_ConnectServer) SendMsg(m interface{}) error {
	args := x.Called(m)
	return args.Error(0)
}

func (x *MockLog_ConnectServer) RecvMsg(m interface{}) error {
	args := x.Called(m)
	return args.Error(0)
}

func (x *MockLog_ConnectServer) Recv() (*protobuf.PLogPile, error) {
	args := x.Called()
	return args.Get(0).(*protobuf.PLogPile), args.Error(1)
}

func (x *MockLog_ConnectServer) OnRecv() *mock.Call {
	return x.On("Recv")
}

func (x *MockLog_ConnectServer) Send(m *protobuf.PLogDemand) error {
	args := x.Called(m)
	return args.Error(0)
}

func (x *MockLog_ConnectServer) OnSend(m interface{}) *mock.Call {
	return x.On("Send", m)
}
