// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.36.1
// source: v1/Service.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_v1_Service_proto protoreflect.FileDescriptor

const file_v1_Service_proto_rawDesc = "" +
	"\n" +
	"\x10v1/Service.proto\x12\x02v1\x1a\x1bgoogle/protobuf/empty.proto\x1a\rv1/Span.proto\x1a\rv1/Stat.proto\x1a\fv1/Cmd.proto2\x83\x01\n" +
	"\x04Span\x12;\n" +
	"\bSendSpan\x12\x10.v1.PSpanMessage\x1a\x16.google.protobuf.Empty\"\x03\x88\x02\x01(\x01\x12>\n" +
	"\rSendSpanBatch\x12\x15.v1.PSpanMessageBatch\x1a\x14.v1.PSpanResultBatch\"\x002e\n" +
	"\x05Agent\x121\n" +
	"\x10RequestAgentInfo\x12\x0e.v1.PAgentInfo\x1a\v.v1.PResult\"\x00\x12)\n" +
	"\vPingSession\x12\t.v1.PPing\x1a\t.v1.PPing\"\x00(\x010\x012\xb5\x02\n" +
	"\bMetadata\x125\n" +
	"\x12RequestSqlMetaData\x12\x10.v1.PSqlMetaData\x1a\v.v1.PResult\"\x00\x12;\n" +
	"\x15RequestSqlUidMetaData\x12\x13.v1.PSqlUidMetaData\x1a\v.v1.PResult\"\x00\x125\n" +
	"\x12RequestApiMetaData\x12\x10.v1.PApiMetaData\x1a\v.v1.PResult\"\x00\x12;\n" +
	"\x15RequestStringMetaData\x12\x13.v1.PStringMetaData\x1a\v.v1.PResult\"\x00\x12A\n" +
	"\x18RequestExceptionMetaData\x12\x16.v1.PExceptionMetaData\x1a\v.v1.PResult\"\x002E\n" +
	"\x04Stat\x12=\n" +
	"\rSendAgentStat\x12\x10.v1.PStatMessage\x1a\x16.google.protobuf.Empty\"\x00(\x012\xd8\x03\n" +
	"\x16ProfilerCommandService\x12:\n" +
	"\rHandleCommand\x12\x0f.v1.PCmdMessage\x1a\x0f.v1.PCmdRequest\"\x03\x88\x02\x01(\x010\x01\x129\n" +
	"\x0fHandleCommandV2\x12\x0f.v1.PCmdMessage\x1a\x0f.v1.PCmdRequest\"\x00(\x010\x01\x12=\n" +
	"\vCommandEcho\x12\x14.v1.PCmdEchoResponse\x1a\x16.google.protobuf.Empty\"\x00\x12Z\n" +
	"\x1eCommandStreamActiveThreadCount\x12\x1c.v1.PCmdActiveThreadCountRes\x1a\x16.google.protobuf.Empty\"\x00(\x01\x12P\n" +
	"\x17CommandActiveThreadDump\x12\x1b.v1.PCmdActiveThreadDumpRes\x1a\x16.google.protobuf.Empty\"\x00\x12Z\n" +
	"\x1cCommandActiveThreadLightDump\x12 .v1.PCmdActiveThreadLightDumpRes\x1a\x16.google.protobuf.Empty\"\x00B8\n" +
	"!com.navercorp.pinpoint.grpc.traceB\fServiceProtoP\x01Z\x03/v1b\x06proto3"

var file_v1_Service_proto_goTypes = []any{
	(*PSpanMessage)(nil),                 // 0: v1.PSpanMessage
	(*PSpanMessageBatch)(nil),            // 1: v1.PSpanMessageBatch
	(*PAgentInfo)(nil),                   // 2: v1.PAgentInfo
	(*PPing)(nil),                        // 3: v1.PPing
	(*PSqlMetaData)(nil),                 // 4: v1.PSqlMetaData
	(*PSqlUidMetaData)(nil),              // 5: v1.PSqlUidMetaData
	(*PApiMetaData)(nil),                 // 6: v1.PApiMetaData
	(*PStringMetaData)(nil),              // 7: v1.PStringMetaData
	(*PExceptionMetaData)(nil),           // 8: v1.PExceptionMetaData
	(*PStatMessage)(nil),                 // 9: v1.PStatMessage
	(*PCmdMessage)(nil),                  // 10: v1.PCmdMessage
	(*PCmdEchoResponse)(nil),             // 11: v1.PCmdEchoResponse
	(*PCmdActiveThreadCountRes)(nil),     // 12: v1.PCmdActiveThreadCountRes
	(*PCmdActiveThreadDumpRes)(nil),      // 13: v1.PCmdActiveThreadDumpRes
	(*PCmdActiveThreadLightDumpRes)(nil), // 14: v1.PCmdActiveThreadLightDumpRes
	(*emptypb.Empty)(nil),                // 15: google.protobuf.Empty
	(*PSpanResultBatch)(nil),             // 16: v1.PSpanResultBatch
	(*PResult)(nil),                      // 17: v1.PResult
	(*PCmdRequest)(nil),                  // 18: v1.PCmdRequest
}
var file_v1_Service_proto_depIdxs = []int32{
	0,  // 0: v1.Span.SendSpan:input_type -> v1.PSpanMessage
	1,  // 1: v1.Span.SendSpanBatch:input_type -> v1.PSpanMessageBatch
	2,  // 2: v1.Agent.RequestAgentInfo:input_type -> v1.PAgentInfo
	3,  // 3: v1.Agent.PingSession:input_type -> v1.PPing
	4,  // 4: v1.Metadata.RequestSqlMetaData:input_type -> v1.PSqlMetaData
	5,  // 5: v1.Metadata.RequestSqlUidMetaData:input_type -> v1.PSqlUidMetaData
	6,  // 6: v1.Metadata.RequestApiMetaData:input_type -> v1.PApiMetaData
	7,  // 7: v1.Metadata.RequestStringMetaData:input_type -> v1.PStringMetaData
	8,  // 8: v1.Metadata.RequestExceptionMetaData:input_type -> v1.PExceptionMetaData
	9,  // 9: v1.Stat.SendAgentStat:input_type -> v1.PStatMessage
	10, // 10: v1.ProfilerCommandService.HandleCommand:input_type -> v1.PCmdMessage
	10, // 11: v1.ProfilerCommandService.HandleCommandV2:input_type -> v1.PCmdMessage
	11, // 12: v1.ProfilerCommandService.CommandEcho:input_type -> v1.PCmdEchoResponse
	12, // 13: v1.ProfilerCommandService.CommandStreamActiveThreadCount:input_type -> v1.PCmdActiveThreadCountRes
	13, // 14: v1.ProfilerCommandService.CommandActiveThreadDump:input_type -> v1.PCmdActiveThreadDumpRes
	14, // 15: v1.ProfilerCommandService.CommandActiveThreadLightDump:input_type -> v1.PCmdActiveThreadLightDumpRes
	15, // 16: v1.Span.SendSpan:output_type -> google.protobuf.Empty
	16, // 17: v1.Span.SendSpanBatch:output_type -> v1.PSpanResultBatch
	17, // 18: v1.Agent.RequestAgentInfo:output_type -> v1.PResult
	3,  // 19: v1.Agent.PingSession:output_type -> v1.PPing
	17, // 20: v1.Metadata.RequestSqlMetaData:output_type -> v1.PResult
	17, // 21: v1.Metadata.RequestSqlUidMetaData:output_type -> v1.PResult
	17, // 22: v1.Metadata.RequestApiMetaData:output_type -> v1.PResult
	17, // 23: v1.Metadata.RequestStringMetaData:output_type -> v1.PResult
	17, // 24: v1.Metadata.RequestExceptionMetaData:output_type -> v1.PResult
	15, // 25: v1.Stat.SendAgentStat:output_type -> google.protobuf.Empty
	18, // 26: v1.ProfilerCommandService.HandleCommand:output_type -> v1.PCmdRequest
	18, // 27: v1.ProfilerCommandService.HandleCommandV2:output_type -> v1.PCmdRequest
	15, // 28: v1.ProfilerCommandService.CommandEcho:output_type -> google.protobuf.Empty
	15, // 29: v1.ProfilerCommandService.CommandStreamActiveThreadCount:output_type -> google.protobuf.Empty
	15, // 30: v1.ProfilerCommandService.CommandActiveThreadDump:output_type -> google.protobuf.Empty
	15, // 31: v1.ProfilerCommandService.CommandActiveThreadLightDump:output_type -> google.protobuf.Empty
	16, // [16:32] is the sub-list for method output_type
	0,  // [0:16] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_v1_Service_proto_init() }
func file_v1_Service_proto_init() {
	if File_v1_Service_proto != nil {
		return
	}
	file_v1_Span_proto_init()
	file_v1_Stat_proto_init()
	file_v1_Cmd_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_Service_proto_rawDesc), len(file_v1_Service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   5,
		},
		GoTypes:           file_v1_Service_proto_goTypes,
		DependencyIndexes: file_v1_Service_proto_depIdxs,
	}.Build()
	File_v1_Service_proto = out.File
	file_v1_Service_proto_goTypes = nil
	file_v1_Service_proto_depIdxs = nil
}
