// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.36.1
// source: v1/Cmd.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PCommandType int32

const (
	PCommandType_NONE                     PCommandType = 0
	PCommandType_PING                     PCommandType = 100
	PCommandType_PONG                     PCommandType = 101
	PCommandType_ECHO                     PCommandType = 710
	PCommandType_ACTIVE_THREAD_COUNT      PCommandType = 730
	PCommandType_ACTIVE_THREAD_DUMP       PCommandType = 740
	PCommandType_ACTIVE_THREAD_LIGHT_DUMP PCommandType = 750
)

// Enum value maps for PCommandType.
var (
	PCommandType_name = map[int32]string{
		0:   "NONE",
		100: "PING",
		101: "PONG",
		710: "ECHO",
		730: "ACTIVE_THREAD_COUNT",
		740: "ACTIVE_THREAD_DUMP",
		750: "ACTIVE_THREAD_LIGHT_DUMP",
	}
	PCommandType_value = map[string]int32{
		"NONE":                     0,
		"PING":                     100,
		"PONG":                     101,
		"ECHO":                     710,
		"ACTIVE_THREAD_COUNT":      730,
		"ACTIVE_THREAD_DUMP":       740,
		"ACTIVE_THREAD_LIGHT_DUMP": 750,
	}
)

func (x PCommandType) Enum() *PCommandType {
	p := new(PCommandType)
	*p = x
	return p
}

func (x PCommandType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PCommandType) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_Cmd_proto_enumTypes[0].Descriptor()
}

func (PCommandType) Type() protoreflect.EnumType {
	return &file_v1_Cmd_proto_enumTypes[0]
}

func (x PCommandType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PCommandType.Descriptor instead.
func (PCommandType) EnumDescriptor() ([]byte, []int) {
	return file_v1_Cmd_proto_rawDescGZIP(), []int{0}
}

type PCmdMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Message:
	//
	//	*PCmdMessage_HandshakeMessage
	//	*PCmdMessage_FailMessage
	Message       isPCmdMessage_Message `protobuf_oneof:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PCmdMessage) Reset() {
	*x = PCmdMessage{}
	mi := &file_v1_Cmd_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PCmdMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PCmdMessage) ProtoMessage() {}

func (x *PCmdMessage) ProtoReflect() protoreflect.Message {
	mi := &file_v1_Cmd_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PCmdMessage.ProtoReflect.Descriptor instead.
func (*PCmdMessage) Descriptor() ([]byte, []int) {
	return file_v1_Cmd_proto_rawDescGZIP(), []int{0}
}

func (x *PCmdMessage) GetMessage() isPCmdMessage_Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *PCmdMessage) GetHandshakeMessage() *PCmdServiceHandshake {
	if x != nil {
		if x, ok := x.Message.(*PCmdMessage_HandshakeMessage); ok {
			return x.HandshakeMessage
		}
	}
	return nil
}

func (x *PCmdMessage) GetFailMessage() *PCmdResponse {
	if x != nil {
		if x, ok := x.Message.(*PCmdMessage_FailMessage); ok {
			return x.FailMessage
		}
	}
	return nil
}

type isPCmdMessage_Message interface {
	isPCmdMessage_Message()
}

type PCmdMessage_HandshakeMessage struct {
	HandshakeMessage *PCmdServiceHandshake `protobuf:"bytes,1,opt,name=handshakeMessage,proto3,oneof"`
}

type PCmdMessage_FailMessage struct {
	FailMessage *PCmdResponse `protobuf:"bytes,2,opt,name=failMessage,proto3,oneof"`
}

func (*PCmdMessage_HandshakeMessage) isPCmdMessage_Message() {}

func (*PCmdMessage_FailMessage) isPCmdMessage_Message() {}

type PCmdServiceHandshake struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// initial message
	SupportCommandServiceKey []int32 `protobuf:"varint,1,rep,packed,name=supportCommandServiceKey,proto3" json:"supportCommandServiceKey,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *PCmdServiceHandshake) Reset() {
	*x = PCmdServiceHandshake{}
	mi := &file_v1_Cmd_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PCmdServiceHandshake) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PCmdServiceHandshake) ProtoMessage() {}

func (x *PCmdServiceHandshake) ProtoReflect() protoreflect.Message {
	mi := &file_v1_Cmd_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PCmdServiceHandshake.ProtoReflect.Descriptor instead.
func (*PCmdServiceHandshake) Descriptor() ([]byte, []int) {
	return file_v1_Cmd_proto_rawDescGZIP(), []int{1}
}

func (x *PCmdServiceHandshake) GetSupportCommandServiceKey() []int32 {
	if x != nil {
		return x.SupportCommandServiceKey
	}
	return nil
}

type PCmdResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	ResponseId    int32                   `protobuf:"varint,1,opt,name=responseId,proto3" json:"responseId,omitempty"`
	Status        int32                   `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	Message       *wrapperspb.StringValue `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PCmdResponse) Reset() {
	*x = PCmdResponse{}
	mi := &file_v1_Cmd_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PCmdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PCmdResponse) ProtoMessage() {}

func (x *PCmdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_Cmd_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PCmdResponse.ProtoReflect.Descriptor instead.
func (*PCmdResponse) Descriptor() ([]byte, []int) {
	return file_v1_Cmd_proto_rawDescGZIP(), []int{2}
}

func (x *PCmdResponse) GetResponseId() int32 {
	if x != nil {
		return x.ResponseId
	}
	return 0
}

func (x *PCmdResponse) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *PCmdResponse) GetMessage() *wrapperspb.StringValue {
	if x != nil {
		return x.Message
	}
	return nil
}

type PCmdStreamResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	ResponseId    int32                   `protobuf:"varint,1,opt,name=responseId,proto3" json:"responseId,omitempty"`
	SequenceId    int32                   `protobuf:"varint,2,opt,name=sequenceId,proto3" json:"sequenceId,omitempty"`
	Message       *wrapperspb.StringValue `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PCmdStreamResponse) Reset() {
	*x = PCmdStreamResponse{}
	mi := &file_v1_Cmd_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PCmdStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PCmdStreamResponse) ProtoMessage() {}

func (x *PCmdStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_Cmd_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PCmdStreamResponse.ProtoReflect.Descriptor instead.
func (*PCmdStreamResponse) Descriptor() ([]byte, []int) {
	return file_v1_Cmd_proto_rawDescGZIP(), []int{3}
}

func (x *PCmdStreamResponse) GetResponseId() int32 {
	if x != nil {
		return x.ResponseId
	}
	return 0
}

func (x *PCmdStreamResponse) GetSequenceId() int32 {
	if x != nil {
		return x.SequenceId
	}
	return 0
}

func (x *PCmdStreamResponse) GetMessage() *wrapperspb.StringValue {
	if x != nil {
		return x.Message
	}
	return nil
}

type PCmdRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	RequestId int32                  `protobuf:"varint,1,opt,name=requestId,proto3" json:"requestId,omitempty"`
	// Types that are valid to be assigned to Command:
	//
	//	*PCmdRequest_CommandEcho
	//	*PCmdRequest_CommandActiveThreadCount
	//	*PCmdRequest_CommandActiveThreadDump
	//	*PCmdRequest_CommandActiveThreadLightDump
	Command       isPCmdRequest_Command `protobuf_oneof:"command"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PCmdRequest) Reset() {
	*x = PCmdRequest{}
	mi := &file_v1_Cmd_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PCmdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PCmdRequest) ProtoMessage() {}

func (x *PCmdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_Cmd_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PCmdRequest.ProtoReflect.Descriptor instead.
func (*PCmdRequest) Descriptor() ([]byte, []int) {
	return file_v1_Cmd_proto_rawDescGZIP(), []int{4}
}

func (x *PCmdRequest) GetRequestId() int32 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *PCmdRequest) GetCommand() isPCmdRequest_Command {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *PCmdRequest) GetCommandEcho() *PCmdEcho {
	if x != nil {
		if x, ok := x.Command.(*PCmdRequest_CommandEcho); ok {
			return x.CommandEcho
		}
	}
	return nil
}

func (x *PCmdRequest) GetCommandActiveThreadCount() *PCmdActiveThreadCount {
	if x != nil {
		if x, ok := x.Command.(*PCmdRequest_CommandActiveThreadCount); ok {
			return x.CommandActiveThreadCount
		}
	}
	return nil
}

func (x *PCmdRequest) GetCommandActiveThreadDump() *PCmdActiveThreadDump {
	if x != nil {
		if x, ok := x.Command.(*PCmdRequest_CommandActiveThreadDump); ok {
			return x.CommandActiveThreadDump
		}
	}
	return nil
}

func (x *PCmdRequest) GetCommandActiveThreadLightDump() *PCmdActiveThreadLightDump {
	if x != nil {
		if x, ok := x.Command.(*PCmdRequest_CommandActiveThreadLightDump); ok {
			return x.CommandActiveThreadLightDump
		}
	}
	return nil
}

type isPCmdRequest_Command interface {
	isPCmdRequest_Command()
}

type PCmdRequest_CommandEcho struct {
	CommandEcho *PCmdEcho `protobuf:"bytes,710,opt,name=commandEcho,proto3,oneof"`
}

type PCmdRequest_CommandActiveThreadCount struct {
	CommandActiveThreadCount *PCmdActiveThreadCount `protobuf:"bytes,730,opt,name=commandActiveThreadCount,proto3,oneof"`
}

type PCmdRequest_CommandActiveThreadDump struct {
	CommandActiveThreadDump *PCmdActiveThreadDump `protobuf:"bytes,740,opt,name=commandActiveThreadDump,proto3,oneof"`
}

type PCmdRequest_CommandActiveThreadLightDump struct {
	CommandActiveThreadLightDump *PCmdActiveThreadLightDump `protobuf:"bytes,750,opt,name=commandActiveThreadLightDump,proto3,oneof"`
}

func (*PCmdRequest_CommandEcho) isPCmdRequest_Command() {}

func (*PCmdRequest_CommandActiveThreadCount) isPCmdRequest_Command() {}

func (*PCmdRequest_CommandActiveThreadDump) isPCmdRequest_Command() {}

func (*PCmdRequest_CommandActiveThreadLightDump) isPCmdRequest_Command() {}

type PCmdEcho struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PCmdEcho) Reset() {
	*x = PCmdEcho{}
	mi := &file_v1_Cmd_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PCmdEcho) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PCmdEcho) ProtoMessage() {}

func (x *PCmdEcho) ProtoReflect() protoreflect.Message {
	mi := &file_v1_Cmd_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PCmdEcho.ProtoReflect.Descriptor instead.
func (*PCmdEcho) Descriptor() ([]byte, []int) {
	return file_v1_Cmd_proto_rawDescGZIP(), []int{5}
}

func (x *PCmdEcho) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type PCmdEchoResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CommonResponse *PCmdResponse          `protobuf:"bytes,1,opt,name=commonResponse,proto3" json:"commonResponse,omitempty"`
	Message        string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PCmdEchoResponse) Reset() {
	*x = PCmdEchoResponse{}
	mi := &file_v1_Cmd_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PCmdEchoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PCmdEchoResponse) ProtoMessage() {}

func (x *PCmdEchoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_Cmd_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PCmdEchoResponse.ProtoReflect.Descriptor instead.
func (*PCmdEchoResponse) Descriptor() ([]byte, []int) {
	return file_v1_Cmd_proto_rawDescGZIP(), []int{6}
}

func (x *PCmdEchoResponse) GetCommonResponse() *PCmdResponse {
	if x != nil {
		return x.CommonResponse
	}
	return nil
}

func (x *PCmdEchoResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type PCmdActiveThreadDump struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	ThreadName    []string               `protobuf:"bytes,2,rep,name=threadName,proto3" json:"threadName,omitempty"`
	LocalTraceId  []int64                `protobuf:"varint,3,rep,packed,name=localTraceId,proto3" json:"localTraceId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PCmdActiveThreadDump) Reset() {
	*x = PCmdActiveThreadDump{}
	mi := &file_v1_Cmd_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PCmdActiveThreadDump) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PCmdActiveThreadDump) ProtoMessage() {}

func (x *PCmdActiveThreadDump) ProtoReflect() protoreflect.Message {
	mi := &file_v1_Cmd_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PCmdActiveThreadDump.ProtoReflect.Descriptor instead.
func (*PCmdActiveThreadDump) Descriptor() ([]byte, []int) {
	return file_v1_Cmd_proto_rawDescGZIP(), []int{7}
}

func (x *PCmdActiveThreadDump) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *PCmdActiveThreadDump) GetThreadName() []string {
	if x != nil {
		return x.ThreadName
	}
	return nil
}

func (x *PCmdActiveThreadDump) GetLocalTraceId() []int64 {
	if x != nil {
		return x.LocalTraceId
	}
	return nil
}

type PCmdActiveThreadDumpRes struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CommonResponse *PCmdResponse          `protobuf:"bytes,1,opt,name=commonResponse,proto3" json:"commonResponse,omitempty"`
	ThreadDump     []*PActiveThreadDump   `protobuf:"bytes,2,rep,name=threadDump,proto3" json:"threadDump,omitempty"`
	Type           string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	SubType        string                 `protobuf:"bytes,4,opt,name=subType,proto3" json:"subType,omitempty"`
	Version        string                 `protobuf:"bytes,5,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PCmdActiveThreadDumpRes) Reset() {
	*x = PCmdActiveThreadDumpRes{}
	mi := &file_v1_Cmd_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PCmdActiveThreadDumpRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PCmdActiveThreadDumpRes) ProtoMessage() {}

func (x *PCmdActiveThreadDumpRes) ProtoReflect() protoreflect.Message {
	mi := &file_v1_Cmd_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PCmdActiveThreadDumpRes.ProtoReflect.Descriptor instead.
func (*PCmdActiveThreadDumpRes) Descriptor() ([]byte, []int) {
	return file_v1_Cmd_proto_rawDescGZIP(), []int{8}
}

func (x *PCmdActiveThreadDumpRes) GetCommonResponse() *PCmdResponse {
	if x != nil {
		return x.CommonResponse
	}
	return nil
}

func (x *PCmdActiveThreadDumpRes) GetThreadDump() []*PActiveThreadDump {
	if x != nil {
		return x.ThreadDump
	}
	return nil
}

func (x *PCmdActiveThreadDumpRes) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *PCmdActiveThreadDumpRes) GetSubType() string {
	if x != nil {
		return x.SubType
	}
	return ""
}

func (x *PCmdActiveThreadDumpRes) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type PCmdActiveThreadLightDump struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	ThreadName    []string               `protobuf:"bytes,2,rep,name=threadName,proto3" json:"threadName,omitempty"`
	LocalTraceId  []int64                `protobuf:"varint,3,rep,packed,name=localTraceId,proto3" json:"localTraceId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PCmdActiveThreadLightDump) Reset() {
	*x = PCmdActiveThreadLightDump{}
	mi := &file_v1_Cmd_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PCmdActiveThreadLightDump) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PCmdActiveThreadLightDump) ProtoMessage() {}

func (x *PCmdActiveThreadLightDump) ProtoReflect() protoreflect.Message {
	mi := &file_v1_Cmd_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PCmdActiveThreadLightDump.ProtoReflect.Descriptor instead.
func (*PCmdActiveThreadLightDump) Descriptor() ([]byte, []int) {
	return file_v1_Cmd_proto_rawDescGZIP(), []int{9}
}

func (x *PCmdActiveThreadLightDump) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *PCmdActiveThreadLightDump) GetThreadName() []string {
	if x != nil {
		return x.ThreadName
	}
	return nil
}

func (x *PCmdActiveThreadLightDump) GetLocalTraceId() []int64 {
	if x != nil {
		return x.LocalTraceId
	}
	return nil
}

type PCmdActiveThreadLightDumpRes struct {
	state          protoimpl.MessageState    `protogen:"open.v1"`
	CommonResponse *PCmdResponse             `protobuf:"bytes,1,opt,name=commonResponse,proto3" json:"commonResponse,omitempty"`
	ThreadDump     []*PActiveThreadLightDump `protobuf:"bytes,2,rep,name=threadDump,proto3" json:"threadDump,omitempty"`
	Type           string                    `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	SubType        string                    `protobuf:"bytes,4,opt,name=subType,proto3" json:"subType,omitempty"`
	Version        string                    `protobuf:"bytes,5,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PCmdActiveThreadLightDumpRes) Reset() {
	*x = PCmdActiveThreadLightDumpRes{}
	mi := &file_v1_Cmd_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PCmdActiveThreadLightDumpRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PCmdActiveThreadLightDumpRes) ProtoMessage() {}

func (x *PCmdActiveThreadLightDumpRes) ProtoReflect() protoreflect.Message {
	mi := &file_v1_Cmd_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PCmdActiveThreadLightDumpRes.ProtoReflect.Descriptor instead.
func (*PCmdActiveThreadLightDumpRes) Descriptor() ([]byte, []int) {
	return file_v1_Cmd_proto_rawDescGZIP(), []int{10}
}

func (x *PCmdActiveThreadLightDumpRes) GetCommonResponse() *PCmdResponse {
	if x != nil {
		return x.CommonResponse
	}
	return nil
}

func (x *PCmdActiveThreadLightDumpRes) GetThreadDump() []*PActiveThreadLightDump {
	if x != nil {
		return x.ThreadDump
	}
	return nil
}

func (x *PCmdActiveThreadLightDumpRes) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *PCmdActiveThreadLightDumpRes) GetSubType() string {
	if x != nil {
		return x.SubType
	}
	return ""
}

func (x *PCmdActiveThreadLightDumpRes) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type PCmdActiveThreadCount struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PCmdActiveThreadCount) Reset() {
	*x = PCmdActiveThreadCount{}
	mi := &file_v1_Cmd_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PCmdActiveThreadCount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PCmdActiveThreadCount) ProtoMessage() {}

func (x *PCmdActiveThreadCount) ProtoReflect() protoreflect.Message {
	mi := &file_v1_Cmd_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PCmdActiveThreadCount.ProtoReflect.Descriptor instead.
func (*PCmdActiveThreadCount) Descriptor() ([]byte, []int) {
	return file_v1_Cmd_proto_rawDescGZIP(), []int{11}
}

type PCmdActiveThreadCountRes struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	CommonStreamResponse *PCmdStreamResponse    `protobuf:"bytes,1,opt,name=commonStreamResponse,proto3" json:"commonStreamResponse,omitempty"`
	HistogramSchemaType  int32                  `protobuf:"varint,2,opt,name=histogramSchemaType,proto3" json:"histogramSchemaType,omitempty"`
	ActiveThreadCount    []int32                `protobuf:"varint,3,rep,packed,name=activeThreadCount,proto3" json:"activeThreadCount,omitempty"`
	TimeStamp            int64                  `protobuf:"varint,4,opt,name=timeStamp,proto3" json:"timeStamp,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *PCmdActiveThreadCountRes) Reset() {
	*x = PCmdActiveThreadCountRes{}
	mi := &file_v1_Cmd_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PCmdActiveThreadCountRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PCmdActiveThreadCountRes) ProtoMessage() {}

func (x *PCmdActiveThreadCountRes) ProtoReflect() protoreflect.Message {
	mi := &file_v1_Cmd_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PCmdActiveThreadCountRes.ProtoReflect.Descriptor instead.
func (*PCmdActiveThreadCountRes) Descriptor() ([]byte, []int) {
	return file_v1_Cmd_proto_rawDescGZIP(), []int{12}
}

func (x *PCmdActiveThreadCountRes) GetCommonStreamResponse() *PCmdStreamResponse {
	if x != nil {
		return x.CommonStreamResponse
	}
	return nil
}

func (x *PCmdActiveThreadCountRes) GetHistogramSchemaType() int32 {
	if x != nil {
		return x.HistogramSchemaType
	}
	return 0
}

func (x *PCmdActiveThreadCountRes) GetActiveThreadCount() []int32 {
	if x != nil {
		return x.ActiveThreadCount
	}
	return nil
}

func (x *PCmdActiveThreadCountRes) GetTimeStamp() int64 {
	if x != nil {
		return x.TimeStamp
	}
	return 0
}

var File_v1_Cmd_proto protoreflect.FileDescriptor

const file_v1_Cmd_proto_rawDesc = "" +
	"\n" +
	"\fv1/Cmd.proto\x12\x02v1\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x13v1/ThreadDump.proto\"\x96\x01\n" +
	"\vPCmdMessage\x12F\n" +
	"\x10handshakeMessage\x18\x01 \x01(\v2\x18.v1.PCmdServiceHandshakeH\x00R\x10handshakeMessage\x124\n" +
	"\vfailMessage\x18\x02 \x01(\v2\x10.v1.PCmdResponseH\x00R\vfailMessageB\t\n" +
	"\amessage\"R\n" +
	"\x14PCmdServiceHandshake\x12:\n" +
	"\x18supportCommandServiceKey\x18\x01 \x03(\x05R\x18supportCommandServiceKey\"~\n" +
	"\fPCmdResponse\x12\x1e\n" +
	"\n" +
	"responseId\x18\x01 \x01(\x05R\n" +
	"responseId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\x05R\x06status\x126\n" +
	"\amessage\x18\x03 \x01(\v2\x1c.google.protobuf.StringValueR\amessage\"\x8c\x01\n" +
	"\x12PCmdStreamResponse\x12\x1e\n" +
	"\n" +
	"responseId\x18\x01 \x01(\x05R\n" +
	"responseId\x12\x1e\n" +
	"\n" +
	"sequenceId\x18\x02 \x01(\x05R\n" +
	"sequenceId\x126\n" +
	"\amessage\x18\x03 \x01(\v2\x1c.google.protobuf.StringValueR\amessage\"\x80\x03\n" +
	"\vPCmdRequest\x12\x1c\n" +
	"\trequestId\x18\x01 \x01(\x05R\trequestId\x121\n" +
	"\vcommandEcho\x18\xc6\x05 \x01(\v2\f.v1.PCmdEchoH\x00R\vcommandEcho\x12X\n" +
	"\x18commandActiveThreadCount\x18\xda\x05 \x01(\v2\x19.v1.PCmdActiveThreadCountH\x00R\x18commandActiveThreadCount\x12U\n" +
	"\x17commandActiveThreadDump\x18\xe4\x05 \x01(\v2\x18.v1.PCmdActiveThreadDumpH\x00R\x17commandActiveThreadDump\x12d\n" +
	"\x1ccommandActiveThreadLightDump\x18\xee\x05 \x01(\v2\x1d.v1.PCmdActiveThreadLightDumpH\x00R\x1ccommandActiveThreadLightDumpB\t\n" +
	"\acommand\"$\n" +
	"\bPCmdEcho\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"f\n" +
	"\x10PCmdEchoResponse\x128\n" +
	"\x0ecommonResponse\x18\x01 \x01(\v2\x10.v1.PCmdResponseR\x0ecommonResponse\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"p\n" +
	"\x14PCmdActiveThreadDump\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x1e\n" +
	"\n" +
	"threadName\x18\x02 \x03(\tR\n" +
	"threadName\x12\"\n" +
	"\flocalTraceId\x18\x03 \x03(\x03R\flocalTraceId\"\xd2\x01\n" +
	"\x17PCmdActiveThreadDumpRes\x128\n" +
	"\x0ecommonResponse\x18\x01 \x01(\v2\x10.v1.PCmdResponseR\x0ecommonResponse\x125\n" +
	"\n" +
	"threadDump\x18\x02 \x03(\v2\x15.v1.PActiveThreadDumpR\n" +
	"threadDump\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x18\n" +
	"\asubType\x18\x04 \x01(\tR\asubType\x12\x18\n" +
	"\aversion\x18\x05 \x01(\tR\aversion\"u\n" +
	"\x19PCmdActiveThreadLightDump\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x1e\n" +
	"\n" +
	"threadName\x18\x02 \x03(\tR\n" +
	"threadName\x12\"\n" +
	"\flocalTraceId\x18\x03 \x03(\x03R\flocalTraceId\"\xdc\x01\n" +
	"\x1cPCmdActiveThreadLightDumpRes\x128\n" +
	"\x0ecommonResponse\x18\x01 \x01(\v2\x10.v1.PCmdResponseR\x0ecommonResponse\x12:\n" +
	"\n" +
	"threadDump\x18\x02 \x03(\v2\x1a.v1.PActiveThreadLightDumpR\n" +
	"threadDump\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x18\n" +
	"\asubType\x18\x04 \x01(\tR\asubType\x12\x18\n" +
	"\aversion\x18\x05 \x01(\tR\aversion\"\x17\n" +
	"\x15PCmdActiveThreadCount\"\xe4\x01\n" +
	"\x18PCmdActiveThreadCountRes\x12J\n" +
	"\x14commonStreamResponse\x18\x01 \x01(\v2\x16.v1.PCmdStreamResponseR\x14commonStreamResponse\x120\n" +
	"\x13histogramSchemaType\x18\x02 \x01(\x05R\x13histogramSchemaType\x12,\n" +
	"\x11activeThreadCount\x18\x03 \x03(\x05R\x11activeThreadCount\x12\x1c\n" +
	"\ttimeStamp\x18\x04 \x01(\x03R\ttimeStamp*\x89\x01\n" +
	"\fPCommandType\x12\b\n" +
	"\x04NONE\x10\x00\x12\b\n" +
	"\x04PING\x10d\x12\b\n" +
	"\x04PONG\x10e\x12\t\n" +
	"\x04ECHO\x10\xc6\x05\x12\x18\n" +
	"\x13ACTIVE_THREAD_COUNT\x10\xda\x05\x12\x17\n" +
	"\x12ACTIVE_THREAD_DUMP\x10\xe4\x05\x12\x1d\n" +
	"\x18ACTIVE_THREAD_LIGHT_DUMP\x10\xee\x05B4\n" +
	"!com.navercorp.pinpoint.grpc.traceB\bCmdProtoP\x01Z\x03/v1b\x06proto3"

var (
	file_v1_Cmd_proto_rawDescOnce sync.Once
	file_v1_Cmd_proto_rawDescData []byte
)

func file_v1_Cmd_proto_rawDescGZIP() []byte {
	file_v1_Cmd_proto_rawDescOnce.Do(func() {
		file_v1_Cmd_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_Cmd_proto_rawDesc), len(file_v1_Cmd_proto_rawDesc)))
	})
	return file_v1_Cmd_proto_rawDescData
}

var file_v1_Cmd_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_v1_Cmd_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_v1_Cmd_proto_goTypes = []any{
	(PCommandType)(0),                    // 0: v1.PCommandType
	(*PCmdMessage)(nil),                  // 1: v1.PCmdMessage
	(*PCmdServiceHandshake)(nil),         // 2: v1.PCmdServiceHandshake
	(*PCmdResponse)(nil),                 // 3: v1.PCmdResponse
	(*PCmdStreamResponse)(nil),           // 4: v1.PCmdStreamResponse
	(*PCmdRequest)(nil),                  // 5: v1.PCmdRequest
	(*PCmdEcho)(nil),                     // 6: v1.PCmdEcho
	(*PCmdEchoResponse)(nil),             // 7: v1.PCmdEchoResponse
	(*PCmdActiveThreadDump)(nil),         // 8: v1.PCmdActiveThreadDump
	(*PCmdActiveThreadDumpRes)(nil),      // 9: v1.PCmdActiveThreadDumpRes
	(*PCmdActiveThreadLightDump)(nil),    // 10: v1.PCmdActiveThreadLightDump
	(*PCmdActiveThreadLightDumpRes)(nil), // 11: v1.PCmdActiveThreadLightDumpRes
	(*PCmdActiveThreadCount)(nil),        // 12: v1.PCmdActiveThreadCount
	(*PCmdActiveThreadCountRes)(nil),     // 13: v1.PCmdActiveThreadCountRes
	(*wrapperspb.StringValue)(nil),       // 14: google.protobuf.StringValue
	(*PActiveThreadDump)(nil),            // 15: v1.PActiveThreadDump
	(*PActiveThreadLightDump)(nil),       // 16: v1.PActiveThreadLightDump
}
var file_v1_Cmd_proto_depIdxs = []int32{
	2,  // 0: v1.PCmdMessage.handshakeMessage:type_name -> v1.PCmdServiceHandshake
	3,  // 1: v1.PCmdMessage.failMessage:type_name -> v1.PCmdResponse
	14, // 2: v1.PCmdResponse.message:type_name -> google.protobuf.StringValue
	14, // 3: v1.PCmdStreamResponse.message:type_name -> google.protobuf.StringValue
	6,  // 4: v1.PCmdRequest.commandEcho:type_name -> v1.PCmdEcho
	12, // 5: v1.PCmdRequest.commandActiveThreadCount:type_name -> v1.PCmdActiveThreadCount
	8,  // 6: v1.PCmdRequest.commandActiveThreadDump:type_name -> v1.PCmdActiveThreadDump
	10, // 7: v1.PCmdRequest.commandActiveThreadLightDump:type_name -> v1.PCmdActiveThreadLightDump
	3,  // 8: v1.PCmdEchoResponse.commonResponse:type_name -> v1.PCmdResponse
	3,  // 9: v1.PCmdActiveThreadDumpRes.commonResponse:type_name -> v1.PCmdResponse
	15, // 10: v1.PCmdActiveThreadDumpRes.threadDump:type_name -> v1.PActiveThreadDump
	3,  // 11: v1.PCmdActiveThreadLightDumpRes.commonResponse:type_name -> v1.PCmdResponse
	16, // 12: v1.PCmdActiveThreadLightDumpRes.threadDump:type_name -> v1.PActiveThreadLightDump
	4,  // 13: v1.PCmdActiveThreadCountRes.commonStreamResponse:type_name -> v1.PCmdStreamResponse
	14, // [14:14] is the sub-list for method output_type
	14, // [14:14] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_v1_Cmd_proto_init() }
func file_v1_Cmd_proto_init() {
	if File_v1_Cmd_proto != nil {
		return
	}
	file_v1_ThreadDump_proto_init()
	file_v1_Cmd_proto_msgTypes[0].OneofWrappers = []any{
		(*PCmdMessage_HandshakeMessage)(nil),
		(*PCmdMessage_FailMessage)(nil),
	}
	file_v1_Cmd_proto_msgTypes[4].OneofWrappers = []any{
		(*PCmdRequest_CommandEcho)(nil),
		(*PCmdRequest_CommandActiveThreadCount)(nil),
		(*PCmdRequest_CommandActiveThreadDump)(nil),
		(*PCmdRequest_CommandActiveThreadLightDump)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_Cmd_proto_rawDesc), len(file_v1_Cmd_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1_Cmd_proto_goTypes,
		DependencyIndexes: file_v1_Cmd_proto_depIdxs,
		EnumInfos:         file_v1_Cmd_proto_enumTypes,
		MessageInfos:      file_v1_Cmd_proto_msgTypes,
	}.Build()
	File_v1_Cmd_proto = out.File
	file_v1_Cmd_proto_goTypes = nil
	file_v1_Cmd_proto_depIdxs = nil
}
