// Code generated by protoc-gen-go. DO NOT EDIT.
// source: v1/CustomMetric.proto

package v1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PCustomMetricMessage struct {
	Timestamp            []int64          `protobuf:"varint,1,rep,packed,name=timestamp,proto3" json:"timestamp,omitempty"`
	CollectInterval      []int64          `protobuf:"varint,2,rep,packed,name=collectInterval,proto3" json:"collectInterval,omitempty"`
	CustomMetrics        []*PCustomMetric `protobuf:"bytes,3,rep,name=customMetrics,proto3" json:"customMetrics,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *PCustomMetricMessage) Reset()         { *m = PCustomMetricMessage{} }
func (m *PCustomMetricMessage) String() string { return proto.CompactTextString(m) }
func (*PCustomMetricMessage) ProtoMessage()    {}
func (*PCustomMetricMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce7d80f7f696e9ae, []int{0}
}

func (m *PCustomMetricMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PCustomMetricMessage.Unmarshal(m, b)
}
func (m *PCustomMetricMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PCustomMetricMessage.Marshal(b, m, deterministic)
}
func (m *PCustomMetricMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PCustomMetricMessage.Merge(m, src)
}
func (m *PCustomMetricMessage) XXX_Size() int {
	return xxx_messageInfo_PCustomMetricMessage.Size(m)
}
func (m *PCustomMetricMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_PCustomMetricMessage.DiscardUnknown(m)
}

var xxx_messageInfo_PCustomMetricMessage proto.InternalMessageInfo

func (m *PCustomMetricMessage) GetTimestamp() []int64 {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func (m *PCustomMetricMessage) GetCollectInterval() []int64 {
	if m != nil {
		return m.CollectInterval
	}
	return nil
}

func (m *PCustomMetricMessage) GetCustomMetrics() []*PCustomMetric {
	if m != nil {
		return m.CustomMetrics
	}
	return nil
}

type PCustomMetric struct {
	// Types that are valid to be assigned to Field:
	//	*PCustomMetric_IntCountMetric
	//	*PCustomMetric_LongCountMetric
	//	*PCustomMetric_IntGaugeMetric
	//	*PCustomMetric_LongGaugeMetric
	//	*PCustomMetric_DoubleGaugeMetric
	Field                isPCustomMetric_Field `protobuf_oneof:"field"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *PCustomMetric) Reset()         { *m = PCustomMetric{} }
func (m *PCustomMetric) String() string { return proto.CompactTextString(m) }
func (*PCustomMetric) ProtoMessage()    {}
func (*PCustomMetric) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce7d80f7f696e9ae, []int{1}
}

func (m *PCustomMetric) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PCustomMetric.Unmarshal(m, b)
}
func (m *PCustomMetric) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PCustomMetric.Marshal(b, m, deterministic)
}
func (m *PCustomMetric) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PCustomMetric.Merge(m, src)
}
func (m *PCustomMetric) XXX_Size() int {
	return xxx_messageInfo_PCustomMetric.Size(m)
}
func (m *PCustomMetric) XXX_DiscardUnknown() {
	xxx_messageInfo_PCustomMetric.DiscardUnknown(m)
}

var xxx_messageInfo_PCustomMetric proto.InternalMessageInfo

type isPCustomMetric_Field interface {
	isPCustomMetric_Field()
}

type PCustomMetric_IntCountMetric struct {
	IntCountMetric *PIntCountMetric `protobuf:"bytes,1,opt,name=intCountMetric,proto3,oneof"`
}

type PCustomMetric_LongCountMetric struct {
	LongCountMetric *PLongCountMetric `protobuf:"bytes,2,opt,name=longCountMetric,proto3,oneof"`
}

type PCustomMetric_IntGaugeMetric struct {
	IntGaugeMetric *PIntGaugeMetric `protobuf:"bytes,3,opt,name=intGaugeMetric,proto3,oneof"`
}

type PCustomMetric_LongGaugeMetric struct {
	LongGaugeMetric *PLongGaugeMetric `protobuf:"bytes,4,opt,name=longGaugeMetric,proto3,oneof"`
}

type PCustomMetric_DoubleGaugeMetric struct {
	DoubleGaugeMetric *PDouleGaugeMetric `protobuf:"bytes,5,opt,name=doubleGaugeMetric,proto3,oneof"`
}

func (*PCustomMetric_IntCountMetric) isPCustomMetric_Field() {}

func (*PCustomMetric_LongCountMetric) isPCustomMetric_Field() {}

func (*PCustomMetric_IntGaugeMetric) isPCustomMetric_Field() {}

func (*PCustomMetric_LongGaugeMetric) isPCustomMetric_Field() {}

func (*PCustomMetric_DoubleGaugeMetric) isPCustomMetric_Field() {}

func (m *PCustomMetric) GetField() isPCustomMetric_Field {
	if m != nil {
		return m.Field
	}
	return nil
}

func (m *PCustomMetric) GetIntCountMetric() *PIntCountMetric {
	if x, ok := m.GetField().(*PCustomMetric_IntCountMetric); ok {
		return x.IntCountMetric
	}
	return nil
}

func (m *PCustomMetric) GetLongCountMetric() *PLongCountMetric {
	if x, ok := m.GetField().(*PCustomMetric_LongCountMetric); ok {
		return x.LongCountMetric
	}
	return nil
}

func (m *PCustomMetric) GetIntGaugeMetric() *PIntGaugeMetric {
	if x, ok := m.GetField().(*PCustomMetric_IntGaugeMetric); ok {
		return x.IntGaugeMetric
	}
	return nil
}

func (m *PCustomMetric) GetLongGaugeMetric() *PLongGaugeMetric {
	if x, ok := m.GetField().(*PCustomMetric_LongGaugeMetric); ok {
		return x.LongGaugeMetric
	}
	return nil
}

func (m *PCustomMetric) GetDoubleGaugeMetric() *PDouleGaugeMetric {
	if x, ok := m.GetField().(*PCustomMetric_DoubleGaugeMetric); ok {
		return x.DoubleGaugeMetric
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*PCustomMetric) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*PCustomMetric_IntCountMetric)(nil),
		(*PCustomMetric_LongCountMetric)(nil),
		(*PCustomMetric_IntGaugeMetric)(nil),
		(*PCustomMetric_LongGaugeMetric)(nil),
		(*PCustomMetric_DoubleGaugeMetric)(nil),
	}
}

type PIntCountMetric struct {
	Name                 string       `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Values               []*PIntValue `protobuf:"bytes,2,rep,name=values,proto3" json:"values,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *PIntCountMetric) Reset()         { *m = PIntCountMetric{} }
func (m *PIntCountMetric) String() string { return proto.CompactTextString(m) }
func (*PIntCountMetric) ProtoMessage()    {}
func (*PIntCountMetric) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce7d80f7f696e9ae, []int{2}
}

func (m *PIntCountMetric) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PIntCountMetric.Unmarshal(m, b)
}
func (m *PIntCountMetric) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PIntCountMetric.Marshal(b, m, deterministic)
}
func (m *PIntCountMetric) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PIntCountMetric.Merge(m, src)
}
func (m *PIntCountMetric) XXX_Size() int {
	return xxx_messageInfo_PIntCountMetric.Size(m)
}
func (m *PIntCountMetric) XXX_DiscardUnknown() {
	xxx_messageInfo_PIntCountMetric.DiscardUnknown(m)
}

var xxx_messageInfo_PIntCountMetric proto.InternalMessageInfo

func (m *PIntCountMetric) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PIntCountMetric) GetValues() []*PIntValue {
	if m != nil {
		return m.Values
	}
	return nil
}

type PLongCountMetric struct {
	Name                 string        `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Values               []*PLongValue `protobuf:"bytes,2,rep,name=values,proto3" json:"values,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *PLongCountMetric) Reset()         { *m = PLongCountMetric{} }
func (m *PLongCountMetric) String() string { return proto.CompactTextString(m) }
func (*PLongCountMetric) ProtoMessage()    {}
func (*PLongCountMetric) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce7d80f7f696e9ae, []int{3}
}

func (m *PLongCountMetric) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PLongCountMetric.Unmarshal(m, b)
}
func (m *PLongCountMetric) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PLongCountMetric.Marshal(b, m, deterministic)
}
func (m *PLongCountMetric) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PLongCountMetric.Merge(m, src)
}
func (m *PLongCountMetric) XXX_Size() int {
	return xxx_messageInfo_PLongCountMetric.Size(m)
}
func (m *PLongCountMetric) XXX_DiscardUnknown() {
	xxx_messageInfo_PLongCountMetric.DiscardUnknown(m)
}

var xxx_messageInfo_PLongCountMetric proto.InternalMessageInfo

func (m *PLongCountMetric) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PLongCountMetric) GetValues() []*PLongValue {
	if m != nil {
		return m.Values
	}
	return nil
}

type PIntGaugeMetric struct {
	Name                 string       `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Values               []*PIntValue `protobuf:"bytes,2,rep,name=values,proto3" json:"values,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *PIntGaugeMetric) Reset()         { *m = PIntGaugeMetric{} }
func (m *PIntGaugeMetric) String() string { return proto.CompactTextString(m) }
func (*PIntGaugeMetric) ProtoMessage()    {}
func (*PIntGaugeMetric) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce7d80f7f696e9ae, []int{4}
}

func (m *PIntGaugeMetric) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PIntGaugeMetric.Unmarshal(m, b)
}
func (m *PIntGaugeMetric) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PIntGaugeMetric.Marshal(b, m, deterministic)
}
func (m *PIntGaugeMetric) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PIntGaugeMetric.Merge(m, src)
}
func (m *PIntGaugeMetric) XXX_Size() int {
	return xxx_messageInfo_PIntGaugeMetric.Size(m)
}
func (m *PIntGaugeMetric) XXX_DiscardUnknown() {
	xxx_messageInfo_PIntGaugeMetric.DiscardUnknown(m)
}

var xxx_messageInfo_PIntGaugeMetric proto.InternalMessageInfo

func (m *PIntGaugeMetric) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PIntGaugeMetric) GetValues() []*PIntValue {
	if m != nil {
		return m.Values
	}
	return nil
}

type PLongGaugeMetric struct {
	Name                 string        `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Values               []*PLongValue `protobuf:"bytes,2,rep,name=values,proto3" json:"values,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *PLongGaugeMetric) Reset()         { *m = PLongGaugeMetric{} }
func (m *PLongGaugeMetric) String() string { return proto.CompactTextString(m) }
func (*PLongGaugeMetric) ProtoMessage()    {}
func (*PLongGaugeMetric) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce7d80f7f696e9ae, []int{5}
}

func (m *PLongGaugeMetric) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PLongGaugeMetric.Unmarshal(m, b)
}
func (m *PLongGaugeMetric) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PLongGaugeMetric.Marshal(b, m, deterministic)
}
func (m *PLongGaugeMetric) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PLongGaugeMetric.Merge(m, src)
}
func (m *PLongGaugeMetric) XXX_Size() int {
	return xxx_messageInfo_PLongGaugeMetric.Size(m)
}
func (m *PLongGaugeMetric) XXX_DiscardUnknown() {
	xxx_messageInfo_PLongGaugeMetric.DiscardUnknown(m)
}

var xxx_messageInfo_PLongGaugeMetric proto.InternalMessageInfo

func (m *PLongGaugeMetric) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PLongGaugeMetric) GetValues() []*PLongValue {
	if m != nil {
		return m.Values
	}
	return nil
}

type PDouleGaugeMetric struct {
	Name                 string          `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Values               []*PDoubleValue `protobuf:"bytes,2,rep,name=values,proto3" json:"values,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *PDouleGaugeMetric) Reset()         { *m = PDouleGaugeMetric{} }
func (m *PDouleGaugeMetric) String() string { return proto.CompactTextString(m) }
func (*PDouleGaugeMetric) ProtoMessage()    {}
func (*PDouleGaugeMetric) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce7d80f7f696e9ae, []int{6}
}

func (m *PDouleGaugeMetric) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PDouleGaugeMetric.Unmarshal(m, b)
}
func (m *PDouleGaugeMetric) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PDouleGaugeMetric.Marshal(b, m, deterministic)
}
func (m *PDouleGaugeMetric) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PDouleGaugeMetric.Merge(m, src)
}
func (m *PDouleGaugeMetric) XXX_Size() int {
	return xxx_messageInfo_PDouleGaugeMetric.Size(m)
}
func (m *PDouleGaugeMetric) XXX_DiscardUnknown() {
	xxx_messageInfo_PDouleGaugeMetric.DiscardUnknown(m)
}

var xxx_messageInfo_PDouleGaugeMetric proto.InternalMessageInfo

func (m *PDouleGaugeMetric) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PDouleGaugeMetric) GetValues() []*PDoubleValue {
	if m != nil {
		return m.Values
	}
	return nil
}

type PIntValue struct {
	Value                int32    `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	IsNotSet             bool     `protobuf:"varint,2,opt,name=isNotSet,proto3" json:"isNotSet,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PIntValue) Reset()         { *m = PIntValue{} }
func (m *PIntValue) String() string { return proto.CompactTextString(m) }
func (*PIntValue) ProtoMessage()    {}
func (*PIntValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce7d80f7f696e9ae, []int{7}
}

func (m *PIntValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PIntValue.Unmarshal(m, b)
}
func (m *PIntValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PIntValue.Marshal(b, m, deterministic)
}
func (m *PIntValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PIntValue.Merge(m, src)
}
func (m *PIntValue) XXX_Size() int {
	return xxx_messageInfo_PIntValue.Size(m)
}
func (m *PIntValue) XXX_DiscardUnknown() {
	xxx_messageInfo_PIntValue.DiscardUnknown(m)
}

var xxx_messageInfo_PIntValue proto.InternalMessageInfo

func (m *PIntValue) GetValue() int32 {
	if m != nil {
		return m.Value
	}
	return 0
}

func (m *PIntValue) GetIsNotSet() bool {
	if m != nil {
		return m.IsNotSet
	}
	return false
}

type PLongValue struct {
	Value                int64    `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	IsNotSet             bool     `protobuf:"varint,2,opt,name=isNotSet,proto3" json:"isNotSet,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PLongValue) Reset()         { *m = PLongValue{} }
func (m *PLongValue) String() string { return proto.CompactTextString(m) }
func (*PLongValue) ProtoMessage()    {}
func (*PLongValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce7d80f7f696e9ae, []int{8}
}

func (m *PLongValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PLongValue.Unmarshal(m, b)
}
func (m *PLongValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PLongValue.Marshal(b, m, deterministic)
}
func (m *PLongValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PLongValue.Merge(m, src)
}
func (m *PLongValue) XXX_Size() int {
	return xxx_messageInfo_PLongValue.Size(m)
}
func (m *PLongValue) XXX_DiscardUnknown() {
	xxx_messageInfo_PLongValue.DiscardUnknown(m)
}

var xxx_messageInfo_PLongValue proto.InternalMessageInfo

func (m *PLongValue) GetValue() int64 {
	if m != nil {
		return m.Value
	}
	return 0
}

func (m *PLongValue) GetIsNotSet() bool {
	if m != nil {
		return m.IsNotSet
	}
	return false
}

type PDoubleValue struct {
	Value                float64  `protobuf:"fixed64,1,opt,name=value,proto3" json:"value,omitempty"`
	IsNotSet             bool     `protobuf:"varint,2,opt,name=isNotSet,proto3" json:"isNotSet,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PDoubleValue) Reset()         { *m = PDoubleValue{} }
func (m *PDoubleValue) String() string { return proto.CompactTextString(m) }
func (*PDoubleValue) ProtoMessage()    {}
func (*PDoubleValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce7d80f7f696e9ae, []int{9}
}

func (m *PDoubleValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PDoubleValue.Unmarshal(m, b)
}
func (m *PDoubleValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PDoubleValue.Marshal(b, m, deterministic)
}
func (m *PDoubleValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PDoubleValue.Merge(m, src)
}
func (m *PDoubleValue) XXX_Size() int {
	return xxx_messageInfo_PDoubleValue.Size(m)
}
func (m *PDoubleValue) XXX_DiscardUnknown() {
	xxx_messageInfo_PDoubleValue.DiscardUnknown(m)
}

var xxx_messageInfo_PDoubleValue proto.InternalMessageInfo

func (m *PDoubleValue) GetValue() float64 {
	if m != nil {
		return m.Value
	}
	return 0
}

func (m *PDoubleValue) GetIsNotSet() bool {
	if m != nil {
		return m.IsNotSet
	}
	return false
}

func init() {
	proto.RegisterType((*PCustomMetricMessage)(nil), "v1.PCustomMetricMessage")
	proto.RegisterType((*PCustomMetric)(nil), "v1.PCustomMetric")
	proto.RegisterType((*PIntCountMetric)(nil), "v1.PIntCountMetric")
	proto.RegisterType((*PLongCountMetric)(nil), "v1.PLongCountMetric")
	proto.RegisterType((*PIntGaugeMetric)(nil), "v1.PIntGaugeMetric")
	proto.RegisterType((*PLongGaugeMetric)(nil), "v1.PLongGaugeMetric")
	proto.RegisterType((*PDouleGaugeMetric)(nil), "v1.PDouleGaugeMetric")
	proto.RegisterType((*PIntValue)(nil), "v1.PIntValue")
	proto.RegisterType((*PLongValue)(nil), "v1.PLongValue")
	proto.RegisterType((*PDoubleValue)(nil), "v1.PDoubleValue")
}

func init() { proto.RegisterFile("v1/CustomMetric.proto", fileDescriptor_ce7d80f7f696e9ae) }

var fileDescriptor_ce7d80f7f696e9ae = []byte{
	// 453 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x94, 0x41, 0x6f, 0xd3, 0x30,
	0x14, 0xc7, 0x9b, 0x66, 0x1d, 0xeb, 0x2b, 0x5d, 0x17, 0xd3, 0x49, 0x11, 0xe2, 0x50, 0x22, 0x81,
	0x72, 0xca, 0x94, 0x72, 0xe0, 0x54, 0x34, 0x75, 0x20, 0x3a, 0x69, 0x9b, 0x8a, 0x91, 0x38, 0x70,
	0x73, 0x3d, 0x13, 0x45, 0x72, 0xec, 0x28, 0x71, 0xf2, 0x55, 0xf8, 0x7c, 0x7c, 0x13, 0x34, 0x2f,
	0xed, 0x6c, 0xaf, 0x12, 0x3d, 0x70, 0x8b, 0xdf, 0xfb, 0xff, 0x7f, 0xf9, 0xfb, 0x39, 0x31, 0x9c,
	0xb7, 0xe9, 0xc5, 0x55, 0x53, 0x2b, 0x59, 0xdc, 0x32, 0x55, 0xe5, 0x34, 0x29, 0x2b, 0xa9, 0x24,
	0xea, 0xb7, 0x69, 0xf4, 0xdb, 0x83, 0xe9, 0xda, 0xec, 0xdd, 0xb2, 0xba, 0x26, 0x19, 0x43, 0x6f,
	0x60, 0xa8, 0xf2, 0x82, 0xd5, 0x8a, 0x14, 0x65, 0xe8, 0xcd, 0xfc, 0xd8, 0xc7, 0x4f, 0x05, 0x14,
	0xc3, 0x84, 0x4a, 0xce, 0x19, 0x55, 0xd7, 0x42, 0xb1, 0xaa, 0x25, 0x3c, 0xec, 0x6b, 0x8d, 0x5b,
	0x46, 0x1f, 0x61, 0x4c, 0x0d, 0x7c, 0x1d, 0xfa, 0x33, 0x3f, 0x1e, 0xcd, 0x83, 0xa4, 0x4d, 0x13,
	0xeb, 0xc5, 0xd8, 0xd6, 0x45, 0x7f, 0xfa, 0x30, 0xb6, 0x04, 0x68, 0x01, 0xa7, 0xb9, 0x50, 0x57,
	0xb2, 0x11, 0xea, 0xb1, 0x12, 0x7a, 0x33, 0x2f, 0x1e, 0xcd, 0x5f, 0x69, 0xd6, 0xb5, 0xd5, 0x5a,
	0xf5, 0xb0, 0x23, 0x46, 0x97, 0x30, 0xe1, 0x52, 0x64, 0xa6, 0xbf, 0xaf, 0xfd, 0x53, 0xed, 0xbf,
	0xb1, 0x7b, 0xab, 0x1e, 0x76, 0xe5, 0x5d, 0x80, 0xaf, 0xa4, 0xc9, 0x58, 0x07, 0xf0, 0xed, 0x00,
	0x46, 0xab, 0x0b, 0x60, 0x54, 0xb6, 0x01, 0x4c, 0xff, 0x91, 0x13, 0xc0, 0x06, 0xb8, 0x72, 0xf4,
	0x05, 0x82, 0x7b, 0xd9, 0x6c, 0x38, 0x33, 0x19, 0x03, 0xcd, 0x38, 0xd7, 0x8c, 0xcf, 0xb2, 0xb1,
	0x9a, 0xab, 0x1e, 0x7e, 0xee, 0x58, 0xbe, 0x80, 0xc1, 0xaf, 0x9c, 0xf1, 0xfb, 0xe8, 0x06, 0x26,
	0xce, 0xdc, 0x10, 0x82, 0x23, 0x41, 0x0a, 0xa6, 0x47, 0x3b, 0xc4, 0xfa, 0x19, 0xbd, 0x83, 0xe3,
	0x96, 0xf0, 0x86, 0xd5, 0xfa, 0x90, 0x47, 0xf3, 0xf1, 0x76, 0xbf, 0x3f, 0x1e, 0xaa, 0xb8, 0x6b,
	0x46, 0x77, 0x70, 0xe6, 0x4e, 0x71, 0x2f, 0xee, 0xbd, 0x83, 0x3b, 0xdd, 0x6d, 0xdf, 0xe6, 0x75,
	0xe9, 0xcc, 0x01, 0xfc, 0x87, 0x74, 0xff, 0xc2, 0x1d, 0x9a, 0xee, 0x1b, 0x04, 0xcf, 0xc6, 0xbd,
	0x17, 0x18, 0x3b, 0xc0, 0xb3, 0xed, 0x49, 0x6d, 0x38, 0xb3, 0x91, 0x0b, 0x18, 0xee, 0x72, 0xa3,
	0x29, 0x0c, 0x74, 0x59, 0xb3, 0x06, 0xf8, 0x71, 0x81, 0x5e, 0xc3, 0x49, 0x5e, 0xdf, 0x49, 0xf5,
	0x9d, 0x29, 0xfd, 0xf5, 0x9e, 0xe0, 0xdd, 0x3a, 0xfa, 0x04, 0xf0, 0x94, 0xd3, 0xf6, 0xfb, 0x87,
	0xf8, 0x2f, 0xe1, 0xa5, 0x19, 0xcb, 0x26, 0x78, 0x07, 0x10, 0x96, 0x0b, 0x78, 0x4b, 0x65, 0x91,
	0x08, 0xd2, 0xb2, 0x8a, 0xca, 0xaa, 0x4c, 0xca, 0x5c, 0x94, 0x32, 0x17, 0x2a, 0xc9, 0xaa, 0x92,
	0x26, 0xaa, 0x22, 0x94, 0x2d, 0x03, 0xf3, 0xa7, 0x5e, 0x3f, 0xdc, 0x44, 0x6b, 0xef, 0xa7, 0x7f,
	0xd1, 0xa6, 0x9b, 0x63, 0x7d, 0x2f, 0x7d, 0xf8, 0x1b, 0x00, 0x00, 0xff, 0xff, 0x50, 0x28, 0xfb,
	0x36, 0xb0, 0x04, 0x00, 0x00,
}
