// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.36.1
// source: v1/Span.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PSpanMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Field:
	//
	//	*PSpanMessage_Span
	//	*PSpanMessage_SpanChunk
	Field         isPSpanMessage_Field `protobuf_oneof:"field"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PSpanMessage) Reset() {
	*x = PSpanMessage{}
	mi := &file_v1_Span_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PSpanMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PSpanMessage) ProtoMessage() {}

func (x *PSpanMessage) ProtoReflect() protoreflect.Message {
	mi := &file_v1_Span_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PSpanMessage.ProtoReflect.Descriptor instead.
func (*PSpanMessage) Descriptor() ([]byte, []int) {
	return file_v1_Span_proto_rawDescGZIP(), []int{0}
}

func (x *PSpanMessage) GetField() isPSpanMessage_Field {
	if x != nil {
		return x.Field
	}
	return nil
}

func (x *PSpanMessage) GetSpan() *PSpan {
	if x != nil {
		if x, ok := x.Field.(*PSpanMessage_Span); ok {
			return x.Span
		}
	}
	return nil
}

func (x *PSpanMessage) GetSpanChunk() *PSpanChunk {
	if x != nil {
		if x, ok := x.Field.(*PSpanMessage_SpanChunk); ok {
			return x.SpanChunk
		}
	}
	return nil
}

type isPSpanMessage_Field interface {
	isPSpanMessage_Field()
}

type PSpanMessage_Span struct {
	Span *PSpan `protobuf:"bytes,1,opt,name=span,proto3,oneof"`
}

type PSpanMessage_SpanChunk struct {
	SpanChunk *PSpanChunk `protobuf:"bytes,2,opt,name=spanChunk,proto3,oneof"`
}

func (*PSpanMessage_Span) isPSpanMessage_Field() {}

func (*PSpanMessage_SpanChunk) isPSpanMessage_Field() {}

// Supported since 3.1.0
type PSpanMessageBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Span          []*PSpanMessage        `protobuf:"bytes,1,rep,name=span,proto3" json:"span,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PSpanMessageBatch) Reset() {
	*x = PSpanMessageBatch{}
	mi := &file_v1_Span_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PSpanMessageBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PSpanMessageBatch) ProtoMessage() {}

func (x *PSpanMessageBatch) ProtoReflect() protoreflect.Message {
	mi := &file_v1_Span_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PSpanMessageBatch.ProtoReflect.Descriptor instead.
func (*PSpanMessageBatch) Descriptor() ([]byte, []int) {
	return file_v1_Span_proto_rawDescGZIP(), []int{1}
}

func (x *PSpanMessageBatch) GetSpan() []*PSpanMessage {
	if x != nil {
		return x.Span
	}
	return nil
}

// Supported since 3.1.0
type PSpanResultBatch struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	PartialSuccess *PPartialSuccess       `protobuf:"bytes,1,opt,name=partial_success,json=partialSuccess,proto3" json:"partial_success,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PSpanResultBatch) Reset() {
	*x = PSpanResultBatch{}
	mi := &file_v1_Span_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PSpanResultBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PSpanResultBatch) ProtoMessage() {}

func (x *PSpanResultBatch) ProtoReflect() protoreflect.Message {
	mi := &file_v1_Span_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PSpanResultBatch.ProtoReflect.Descriptor instead.
func (*PSpanResultBatch) Descriptor() ([]byte, []int) {
	return file_v1_Span_proto_rawDescGZIP(), []int{2}
}

func (x *PSpanResultBatch) GetPartialSuccess() *PPartialSuccess {
	if x != nil {
		return x.PartialSuccess
	}
	return nil
}

// Supported since 3.1.0
type PPartialSuccess struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RejectedSpans int64                  `protobuf:"varint,1,opt,name=rejected_spans,json=rejectedSpans,proto3" json:"rejected_spans,omitempty"`
	ErrorId       int64                  `protobuf:"varint,2,opt,name=errorId,proto3" json:"errorId,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PPartialSuccess) Reset() {
	*x = PPartialSuccess{}
	mi := &file_v1_Span_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PPartialSuccess) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PPartialSuccess) ProtoMessage() {}

func (x *PPartialSuccess) ProtoReflect() protoreflect.Message {
	mi := &file_v1_Span_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PPartialSuccess.ProtoReflect.Descriptor instead.
func (*PPartialSuccess) Descriptor() ([]byte, []int) {
	return file_v1_Span_proto_rawDescGZIP(), []int{3}
}

func (x *PPartialSuccess) GetRejectedSpans() int64 {
	if x != nil {
		return x.RejectedSpans
	}
	return 0
}

func (x *PPartialSuccess) GetErrorId() int64 {
	if x != nil {
		return x.ErrorId
	}
	return 0
}

func (x *PPartialSuccess) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type PSpan struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       int32                  `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	TransactionId *PTransactionId        `protobuf:"bytes,2,opt,name=transactionId,proto3" json:"transactionId,omitempty"`
	SpanId        int64                  `protobuf:"fixed64,3,opt,name=spanId,proto3" json:"spanId,omitempty"`
	ParentSpanId  int64                  `protobuf:"fixed64,4,opt,name=parentSpanId,proto3" json:"parentSpanId,omitempty"`
	// span event's startTimestamp
	StartTime              int64            `protobuf:"varint,5,opt,name=startTime,proto3" json:"startTime,omitempty"`
	Elapsed                int32            `protobuf:"varint,6,opt,name=elapsed,proto3" json:"elapsed,omitempty"`
	ApiId                  int32            `protobuf:"varint,7,opt,name=apiId,proto3" json:"apiId,omitempty"`
	ServiceType            int32            `protobuf:"varint,8,opt,name=serviceType,proto3" json:"serviceType,omitempty"`
	AcceptEvent            *PAcceptEvent    `protobuf:"bytes,9,opt,name=acceptEvent,proto3" json:"acceptEvent,omitempty"`
	Annotation             []*PAnnotation   `protobuf:"bytes,10,rep,name=annotation,proto3" json:"annotation,omitempty"`
	Flag                   int32            `protobuf:"varint,11,opt,name=flag,proto3" json:"flag,omitempty"`
	Err                    int32            `protobuf:"zigzag32,12,opt,name=err,proto3" json:"err,omitempty"`
	SpanEvent              []*PSpanEvent    `protobuf:"bytes,13,rep,name=spanEvent,proto3" json:"spanEvent,omitempty"`
	ExceptionInfo          *PIntStringValue `protobuf:"bytes,14,opt,name=exceptionInfo,proto3" json:"exceptionInfo,omitempty"`
	ApplicationServiceType int32            `protobuf:"varint,15,opt,name=applicationServiceType,proto3" json:"applicationServiceType,omitempty"`
	LoggingTransactionInfo int32            `protobuf:"varint,16,opt,name=loggingTransactionInfo,proto3" json:"loggingTransactionInfo,omitempty"`
	// Supported since 3.1.0
	Attribute     []*PAttribute `protobuf:"bytes,17,rep,name=attribute,proto3" json:"attribute,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PSpan) Reset() {
	*x = PSpan{}
	mi := &file_v1_Span_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PSpan) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PSpan) ProtoMessage() {}

func (x *PSpan) ProtoReflect() protoreflect.Message {
	mi := &file_v1_Span_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PSpan.ProtoReflect.Descriptor instead.
func (*PSpan) Descriptor() ([]byte, []int) {
	return file_v1_Span_proto_rawDescGZIP(), []int{4}
}

func (x *PSpan) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *PSpan) GetTransactionId() *PTransactionId {
	if x != nil {
		return x.TransactionId
	}
	return nil
}

func (x *PSpan) GetSpanId() int64 {
	if x != nil {
		return x.SpanId
	}
	return 0
}

func (x *PSpan) GetParentSpanId() int64 {
	if x != nil {
		return x.ParentSpanId
	}
	return 0
}

func (x *PSpan) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *PSpan) GetElapsed() int32 {
	if x != nil {
		return x.Elapsed
	}
	return 0
}

func (x *PSpan) GetApiId() int32 {
	if x != nil {
		return x.ApiId
	}
	return 0
}

func (x *PSpan) GetServiceType() int32 {
	if x != nil {
		return x.ServiceType
	}
	return 0
}

func (x *PSpan) GetAcceptEvent() *PAcceptEvent {
	if x != nil {
		return x.AcceptEvent
	}
	return nil
}

func (x *PSpan) GetAnnotation() []*PAnnotation {
	if x != nil {
		return x.Annotation
	}
	return nil
}

func (x *PSpan) GetFlag() int32 {
	if x != nil {
		return x.Flag
	}
	return 0
}

func (x *PSpan) GetErr() int32 {
	if x != nil {
		return x.Err
	}
	return 0
}

func (x *PSpan) GetSpanEvent() []*PSpanEvent {
	if x != nil {
		return x.SpanEvent
	}
	return nil
}

func (x *PSpan) GetExceptionInfo() *PIntStringValue {
	if x != nil {
		return x.ExceptionInfo
	}
	return nil
}

func (x *PSpan) GetApplicationServiceType() int32 {
	if x != nil {
		return x.ApplicationServiceType
	}
	return 0
}

func (x *PSpan) GetLoggingTransactionInfo() int32 {
	if x != nil {
		return x.LoggingTransactionInfo
	}
	return 0
}

func (x *PSpan) GetAttribute() []*PAttribute {
	if x != nil {
		return x.Attribute
	}
	return nil
}

type PTransactionId struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// identical to agentId if null
	AgentId        string `protobuf:"bytes,1,opt,name=agentId,proto3" json:"agentId,omitempty"` //nullable
	AgentStartTime int64  `protobuf:"varint,2,opt,name=agentStartTime,proto3" json:"agentStartTime,omitempty"`
	Sequence       int64  `protobuf:"varint,3,opt,name=sequence,proto3" json:"sequence,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PTransactionId) Reset() {
	*x = PTransactionId{}
	mi := &file_v1_Span_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PTransactionId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PTransactionId) ProtoMessage() {}

func (x *PTransactionId) ProtoReflect() protoreflect.Message {
	mi := &file_v1_Span_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PTransactionId.ProtoReflect.Descriptor instead.
func (*PTransactionId) Descriptor() ([]byte, []int) {
	return file_v1_Span_proto_rawDescGZIP(), []int{5}
}

func (x *PTransactionId) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *PTransactionId) GetAgentStartTime() int64 {
	if x != nil {
		return x.AgentStartTime
	}
	return 0
}

func (x *PTransactionId) GetSequence() int64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

type PAcceptEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rpc           string                 `protobuf:"bytes,1,opt,name=rpc,proto3" json:"rpc,omitempty"`
	EndPoint      string                 `protobuf:"bytes,2,opt,name=endPoint,proto3" json:"endPoint,omitempty"`
	RemoteAddr    string                 `protobuf:"bytes,3,opt,name=remoteAddr,proto3" json:"remoteAddr,omitempty"`
	ParentInfo    *PParentInfo           `protobuf:"bytes,4,opt,name=parentInfo,proto3" json:"parentInfo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PAcceptEvent) Reset() {
	*x = PAcceptEvent{}
	mi := &file_v1_Span_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PAcceptEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PAcceptEvent) ProtoMessage() {}

func (x *PAcceptEvent) ProtoReflect() protoreflect.Message {
	mi := &file_v1_Span_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PAcceptEvent.ProtoReflect.Descriptor instead.
func (*PAcceptEvent) Descriptor() ([]byte, []int) {
	return file_v1_Span_proto_rawDescGZIP(), []int{6}
}

func (x *PAcceptEvent) GetRpc() string {
	if x != nil {
		return x.Rpc
	}
	return ""
}

func (x *PAcceptEvent) GetEndPoint() string {
	if x != nil {
		return x.EndPoint
	}
	return ""
}

func (x *PAcceptEvent) GetRemoteAddr() string {
	if x != nil {
		return x.RemoteAddr
	}
	return ""
}

func (x *PAcceptEvent) GetParentInfo() *PParentInfo {
	if x != nil {
		return x.ParentInfo
	}
	return nil
}

type PParentInfo struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	ParentApplicationName string                 `protobuf:"bytes,1,opt,name=parentApplicationName,proto3" json:"parentApplicationName,omitempty"`
	ParentApplicationType int32                  `protobuf:"varint,2,opt,name=parentApplicationType,proto3" json:"parentApplicationType,omitempty"`
	AcceptorHost          string                 `protobuf:"bytes,3,opt,name=acceptorHost,proto3" json:"acceptorHost,omitempty"`
	ParentServiceName     string                 `protobuf:"bytes,4,opt,name=parentServiceName,proto3" json:"parentServiceName,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *PParentInfo) Reset() {
	*x = PParentInfo{}
	mi := &file_v1_Span_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PParentInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PParentInfo) ProtoMessage() {}

func (x *PParentInfo) ProtoReflect() protoreflect.Message {
	mi := &file_v1_Span_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PParentInfo.ProtoReflect.Descriptor instead.
func (*PParentInfo) Descriptor() ([]byte, []int) {
	return file_v1_Span_proto_rawDescGZIP(), []int{7}
}

func (x *PParentInfo) GetParentApplicationName() string {
	if x != nil {
		return x.ParentApplicationName
	}
	return ""
}

func (x *PParentInfo) GetParentApplicationType() int32 {
	if x != nil {
		return x.ParentApplicationType
	}
	return 0
}

func (x *PParentInfo) GetAcceptorHost() string {
	if x != nil {
		return x.AcceptorHost
	}
	return ""
}

func (x *PParentInfo) GetParentServiceName() string {
	if x != nil {
		return x.ParentServiceName
	}
	return ""
}

type PLocalAsyncId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AsyncId       int32                  `protobuf:"varint,1,opt,name=asyncId,proto3" json:"asyncId,omitempty"`
	Sequence      int32                  `protobuf:"varint,2,opt,name=sequence,proto3" json:"sequence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PLocalAsyncId) Reset() {
	*x = PLocalAsyncId{}
	mi := &file_v1_Span_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PLocalAsyncId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PLocalAsyncId) ProtoMessage() {}

func (x *PLocalAsyncId) ProtoReflect() protoreflect.Message {
	mi := &file_v1_Span_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PLocalAsyncId.ProtoReflect.Descriptor instead.
func (*PLocalAsyncId) Descriptor() ([]byte, []int) {
	return file_v1_Span_proto_rawDescGZIP(), []int{8}
}

func (x *PLocalAsyncId) GetAsyncId() int32 {
	if x != nil {
		return x.AsyncId
	}
	return 0
}

func (x *PLocalAsyncId) GetSequence() int32 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

type PSpanEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sequence      int32                  `protobuf:"varint,1,opt,name=sequence,proto3" json:"sequence,omitempty"`
	Depth         int32                  `protobuf:"varint,2,opt,name=depth,proto3" json:"depth,omitempty"`
	StartElapsed  int32                  `protobuf:"varint,3,opt,name=startElapsed,proto3" json:"startElapsed,omitempty"`
	EndElapsed    int32                  `protobuf:"varint,4,opt,name=endElapsed,proto3" json:"endElapsed,omitempty"`
	ServiceType   int32                  `protobuf:"zigzag32,5,opt,name=serviceType,proto3" json:"serviceType,omitempty"`
	Annotation    []*PAnnotation         `protobuf:"bytes,6,rep,name=annotation,proto3" json:"annotation,omitempty"`
	ApiId         int32                  `protobuf:"zigzag32,10,opt,name=apiId,proto3" json:"apiId,omitempty"`
	ExceptionInfo *PIntStringValue       `protobuf:"bytes,11,opt,name=exceptionInfo,proto3" json:"exceptionInfo,omitempty"`
	NextEvent     *PNextEvent            `protobuf:"bytes,12,opt,name=nextEvent,proto3" json:"nextEvent,omitempty"`
	AsyncEvent    int32                  `protobuf:"varint,13,opt,name=asyncEvent,proto3" json:"asyncEvent,omitempty"`
	// Supported since 3.1.0
	Attribute     []*PAttribute `protobuf:"bytes,14,rep,name=attribute,proto3" json:"attribute,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PSpanEvent) Reset() {
	*x = PSpanEvent{}
	mi := &file_v1_Span_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PSpanEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PSpanEvent) ProtoMessage() {}

func (x *PSpanEvent) ProtoReflect() protoreflect.Message {
	mi := &file_v1_Span_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PSpanEvent.ProtoReflect.Descriptor instead.
func (*PSpanEvent) Descriptor() ([]byte, []int) {
	return file_v1_Span_proto_rawDescGZIP(), []int{9}
}

func (x *PSpanEvent) GetSequence() int32 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *PSpanEvent) GetDepth() int32 {
	if x != nil {
		return x.Depth
	}
	return 0
}

func (x *PSpanEvent) GetStartElapsed() int32 {
	if x != nil {
		return x.StartElapsed
	}
	return 0
}

func (x *PSpanEvent) GetEndElapsed() int32 {
	if x != nil {
		return x.EndElapsed
	}
	return 0
}

func (x *PSpanEvent) GetServiceType() int32 {
	if x != nil {
		return x.ServiceType
	}
	return 0
}

func (x *PSpanEvent) GetAnnotation() []*PAnnotation {
	if x != nil {
		return x.Annotation
	}
	return nil
}

func (x *PSpanEvent) GetApiId() int32 {
	if x != nil {
		return x.ApiId
	}
	return 0
}

func (x *PSpanEvent) GetExceptionInfo() *PIntStringValue {
	if x != nil {
		return x.ExceptionInfo
	}
	return nil
}

func (x *PSpanEvent) GetNextEvent() *PNextEvent {
	if x != nil {
		return x.NextEvent
	}
	return nil
}

func (x *PSpanEvent) GetAsyncEvent() int32 {
	if x != nil {
		return x.AsyncEvent
	}
	return 0
}

func (x *PSpanEvent) GetAttribute() []*PAttribute {
	if x != nil {
		return x.Attribute
	}
	return nil
}

type PNextEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Field:
	//
	//	*PNextEvent_MessageEvent
	Field         isPNextEvent_Field `protobuf_oneof:"field"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PNextEvent) Reset() {
	*x = PNextEvent{}
	mi := &file_v1_Span_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PNextEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PNextEvent) ProtoMessage() {}

func (x *PNextEvent) ProtoReflect() protoreflect.Message {
	mi := &file_v1_Span_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PNextEvent.ProtoReflect.Descriptor instead.
func (*PNextEvent) Descriptor() ([]byte, []int) {
	return file_v1_Span_proto_rawDescGZIP(), []int{10}
}

func (x *PNextEvent) GetField() isPNextEvent_Field {
	if x != nil {
		return x.Field
	}
	return nil
}

func (x *PNextEvent) GetMessageEvent() *PMessageEvent {
	if x != nil {
		if x, ok := x.Field.(*PNextEvent_MessageEvent); ok {
			return x.MessageEvent
		}
	}
	return nil
}

type isPNextEvent_Field interface {
	isPNextEvent_Field()
}

type PNextEvent_MessageEvent struct {
	MessageEvent *PMessageEvent `protobuf:"bytes,1,opt,name=messageEvent,proto3,oneof"`
}

func (*PNextEvent_MessageEvent) isPNextEvent_Field() {}

type PMessageEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NextSpanId    int64                  `protobuf:"fixed64,1,opt,name=nextSpanId,proto3" json:"nextSpanId,omitempty"`
	EndPoint      string                 `protobuf:"bytes,2,opt,name=endPoint,proto3" json:"endPoint,omitempty"`
	DestinationId string                 `protobuf:"bytes,3,opt,name=destinationId,proto3" json:"destinationId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PMessageEvent) Reset() {
	*x = PMessageEvent{}
	mi := &file_v1_Span_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PMessageEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PMessageEvent) ProtoMessage() {}

func (x *PMessageEvent) ProtoReflect() protoreflect.Message {
	mi := &file_v1_Span_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PMessageEvent.ProtoReflect.Descriptor instead.
func (*PMessageEvent) Descriptor() ([]byte, []int) {
	return file_v1_Span_proto_rawDescGZIP(), []int{11}
}

func (x *PMessageEvent) GetNextSpanId() int64 {
	if x != nil {
		return x.NextSpanId
	}
	return 0
}

func (x *PMessageEvent) GetEndPoint() string {
	if x != nil {
		return x.EndPoint
	}
	return ""
}

func (x *PMessageEvent) GetDestinationId() string {
	if x != nil {
		return x.DestinationId
	}
	return ""
}

type PSpanChunk struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	Version                int32                  `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	TransactionId          *PTransactionId        `protobuf:"bytes,2,opt,name=transactionId,proto3" json:"transactionId,omitempty"`
	SpanId                 int64                  `protobuf:"fixed64,3,opt,name=spanId,proto3" json:"spanId,omitempty"`
	EndPoint               string                 `protobuf:"bytes,4,opt,name=endPoint,proto3" json:"endPoint,omitempty"`
	SpanEvent              []*PSpanEvent          `protobuf:"bytes,5,rep,name=spanEvent,proto3" json:"spanEvent,omitempty"`
	ApplicationServiceType int32                  `protobuf:"varint,6,opt,name=applicationServiceType,proto3" json:"applicationServiceType,omitempty"`
	KeyTime                int64                  `protobuf:"varint,7,opt,name=keyTime,proto3" json:"keyTime,omitempty"`
	LocalAsyncId           *PLocalAsyncId         `protobuf:"bytes,8,opt,name=localAsyncId,proto3" json:"localAsyncId,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *PSpanChunk) Reset() {
	*x = PSpanChunk{}
	mi := &file_v1_Span_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PSpanChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PSpanChunk) ProtoMessage() {}

func (x *PSpanChunk) ProtoReflect() protoreflect.Message {
	mi := &file_v1_Span_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PSpanChunk.ProtoReflect.Descriptor instead.
func (*PSpanChunk) Descriptor() ([]byte, []int) {
	return file_v1_Span_proto_rawDescGZIP(), []int{12}
}

func (x *PSpanChunk) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *PSpanChunk) GetTransactionId() *PTransactionId {
	if x != nil {
		return x.TransactionId
	}
	return nil
}

func (x *PSpanChunk) GetSpanId() int64 {
	if x != nil {
		return x.SpanId
	}
	return 0
}

func (x *PSpanChunk) GetEndPoint() string {
	if x != nil {
		return x.EndPoint
	}
	return ""
}

func (x *PSpanChunk) GetSpanEvent() []*PSpanEvent {
	if x != nil {
		return x.SpanEvent
	}
	return nil
}

func (x *PSpanChunk) GetApplicationServiceType() int32 {
	if x != nil {
		return x.ApplicationServiceType
	}
	return 0
}

func (x *PSpanChunk) GetKeyTime() int64 {
	if x != nil {
		return x.KeyTime
	}
	return 0
}

func (x *PSpanChunk) GetLocalAsyncId() *PLocalAsyncId {
	if x != nil {
		return x.LocalAsyncId
	}
	return nil
}

type PResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PResult) Reset() {
	*x = PResult{}
	mi := &file_v1_Span_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PResult) ProtoMessage() {}

func (x *PResult) ProtoReflect() protoreflect.Message {
	mi := &file_v1_Span_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PResult.ProtoReflect.Descriptor instead.
func (*PResult) Descriptor() ([]byte, []int) {
	return file_v1_Span_proto_rawDescGZIP(), []int{13}
}

func (x *PResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PResult) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type PSqlMetaData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SqlId         int32                  `protobuf:"varint,1,opt,name=sqlId,proto3" json:"sqlId,omitempty"`
	Sql           string                 `protobuf:"bytes,2,opt,name=sql,proto3" json:"sql,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PSqlMetaData) Reset() {
	*x = PSqlMetaData{}
	mi := &file_v1_Span_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PSqlMetaData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PSqlMetaData) ProtoMessage() {}

func (x *PSqlMetaData) ProtoReflect() protoreflect.Message {
	mi := &file_v1_Span_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PSqlMetaData.ProtoReflect.Descriptor instead.
func (*PSqlMetaData) Descriptor() ([]byte, []int) {
	return file_v1_Span_proto_rawDescGZIP(), []int{14}
}

func (x *PSqlMetaData) GetSqlId() int32 {
	if x != nil {
		return x.SqlId
	}
	return 0
}

func (x *PSqlMetaData) GetSql() string {
	if x != nil {
		return x.Sql
	}
	return ""
}

type PSqlUidMetaData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SqlUid        []byte                 `protobuf:"bytes,1,opt,name=sqlUid,proto3" json:"sqlUid,omitempty"`
	Sql           string                 `protobuf:"bytes,2,opt,name=sql,proto3" json:"sql,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PSqlUidMetaData) Reset() {
	*x = PSqlUidMetaData{}
	mi := &file_v1_Span_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PSqlUidMetaData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PSqlUidMetaData) ProtoMessage() {}

func (x *PSqlUidMetaData) ProtoReflect() protoreflect.Message {
	mi := &file_v1_Span_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PSqlUidMetaData.ProtoReflect.Descriptor instead.
func (*PSqlUidMetaData) Descriptor() ([]byte, []int) {
	return file_v1_Span_proto_rawDescGZIP(), []int{15}
}

func (x *PSqlUidMetaData) GetSqlUid() []byte {
	if x != nil {
		return x.SqlUid
	}
	return nil
}

func (x *PSqlUidMetaData) GetSql() string {
	if x != nil {
		return x.Sql
	}
	return ""
}

type PApiMetaData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiId         int32                  `protobuf:"varint,1,opt,name=apiId,proto3" json:"apiId,omitempty"`
	ApiInfo       string                 `protobuf:"bytes,2,opt,name=apiInfo,proto3" json:"apiInfo,omitempty"`
	Line          int32                  `protobuf:"varint,3,opt,name=line,proto3" json:"line,omitempty"`
	Type          int32                  `protobuf:"varint,4,opt,name=type,proto3" json:"type,omitempty"`
	Location      string                 `protobuf:"bytes,5,opt,name=location,proto3" json:"location,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PApiMetaData) Reset() {
	*x = PApiMetaData{}
	mi := &file_v1_Span_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PApiMetaData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PApiMetaData) ProtoMessage() {}

func (x *PApiMetaData) ProtoReflect() protoreflect.Message {
	mi := &file_v1_Span_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PApiMetaData.ProtoReflect.Descriptor instead.
func (*PApiMetaData) Descriptor() ([]byte, []int) {
	return file_v1_Span_proto_rawDescGZIP(), []int{16}
}

func (x *PApiMetaData) GetApiId() int32 {
	if x != nil {
		return x.ApiId
	}
	return 0
}

func (x *PApiMetaData) GetApiInfo() string {
	if x != nil {
		return x.ApiInfo
	}
	return ""
}

func (x *PApiMetaData) GetLine() int32 {
	if x != nil {
		return x.Line
	}
	return 0
}

func (x *PApiMetaData) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *PApiMetaData) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

type PStringMetaData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StringId      int32                  `protobuf:"varint,1,opt,name=stringId,proto3" json:"stringId,omitempty"`
	StringValue   string                 `protobuf:"bytes,2,opt,name=stringValue,proto3" json:"stringValue,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PStringMetaData) Reset() {
	*x = PStringMetaData{}
	mi := &file_v1_Span_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PStringMetaData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PStringMetaData) ProtoMessage() {}

func (x *PStringMetaData) ProtoReflect() protoreflect.Message {
	mi := &file_v1_Span_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PStringMetaData.ProtoReflect.Descriptor instead.
func (*PStringMetaData) Descriptor() ([]byte, []int) {
	return file_v1_Span_proto_rawDescGZIP(), []int{17}
}

func (x *PStringMetaData) GetStringId() int32 {
	if x != nil {
		return x.StringId
	}
	return 0
}

func (x *PStringMetaData) GetStringValue() string {
	if x != nil {
		return x.StringValue
	}
	return ""
}

type PExceptionMetaData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exceptions    []*PException          `protobuf:"bytes,1,rep,name=exceptions,proto3" json:"exceptions,omitempty"`
	TransactionId *PTransactionId        `protobuf:"bytes,2,opt,name=transactionId,proto3" json:"transactionId,omitempty"`
	SpanId        int64                  `protobuf:"fixed64,3,opt,name=spanId,proto3" json:"spanId,omitempty"`
	UriTemplate   string                 `protobuf:"bytes,4,opt,name=uriTemplate,proto3" json:"uriTemplate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PExceptionMetaData) Reset() {
	*x = PExceptionMetaData{}
	mi := &file_v1_Span_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PExceptionMetaData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PExceptionMetaData) ProtoMessage() {}

func (x *PExceptionMetaData) ProtoReflect() protoreflect.Message {
	mi := &file_v1_Span_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PExceptionMetaData.ProtoReflect.Descriptor instead.
func (*PExceptionMetaData) Descriptor() ([]byte, []int) {
	return file_v1_Span_proto_rawDescGZIP(), []int{18}
}

func (x *PExceptionMetaData) GetExceptions() []*PException {
	if x != nil {
		return x.Exceptions
	}
	return nil
}

func (x *PExceptionMetaData) GetTransactionId() *PTransactionId {
	if x != nil {
		return x.TransactionId
	}
	return nil
}

func (x *PExceptionMetaData) GetSpanId() int64 {
	if x != nil {
		return x.SpanId
	}
	return 0
}

func (x *PExceptionMetaData) GetUriTemplate() string {
	if x != nil {
		return x.UriTemplate
	}
	return ""
}

type PException struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ExceptionClassName string                 `protobuf:"bytes,1,opt,name=exceptionClassName,proto3" json:"exceptionClassName,omitempty"`
	ExceptionMessage   string                 `protobuf:"bytes,2,opt,name=exceptionMessage,proto3" json:"exceptionMessage,omitempty"`
	StartTime          int64                  `protobuf:"varint,3,opt,name=startTime,proto3" json:"startTime,omitempty"`
	ExceptionId        int64                  `protobuf:"varint,4,opt,name=exceptionId,proto3" json:"exceptionId,omitempty"`
	ExceptionDepth     int32                  `protobuf:"varint,5,opt,name=exceptionDepth,proto3" json:"exceptionDepth,omitempty"`
	StackTraceElement  []*PStackTraceElement  `protobuf:"bytes,6,rep,name=stackTraceElement,proto3" json:"stackTraceElement,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *PException) Reset() {
	*x = PException{}
	mi := &file_v1_Span_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PException) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PException) ProtoMessage() {}

func (x *PException) ProtoReflect() protoreflect.Message {
	mi := &file_v1_Span_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PException.ProtoReflect.Descriptor instead.
func (*PException) Descriptor() ([]byte, []int) {
	return file_v1_Span_proto_rawDescGZIP(), []int{19}
}

func (x *PException) GetExceptionClassName() string {
	if x != nil {
		return x.ExceptionClassName
	}
	return ""
}

func (x *PException) GetExceptionMessage() string {
	if x != nil {
		return x.ExceptionMessage
	}
	return ""
}

func (x *PException) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *PException) GetExceptionId() int64 {
	if x != nil {
		return x.ExceptionId
	}
	return 0
}

func (x *PException) GetExceptionDepth() int32 {
	if x != nil {
		return x.ExceptionDepth
	}
	return 0
}

func (x *PException) GetStackTraceElement() []*PStackTraceElement {
	if x != nil {
		return x.StackTraceElement
	}
	return nil
}

type PStackTraceElement struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClassName     string                 `protobuf:"bytes,1,opt,name=className,proto3" json:"className,omitempty"`
	FileName      string                 `protobuf:"bytes,2,opt,name=fileName,proto3" json:"fileName,omitempty"`
	LineNumber    int32                  `protobuf:"varint,3,opt,name=lineNumber,proto3" json:"lineNumber,omitempty"`
	MethodName    string                 `protobuf:"bytes,4,opt,name=methodName,proto3" json:"methodName,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PStackTraceElement) Reset() {
	*x = PStackTraceElement{}
	mi := &file_v1_Span_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PStackTraceElement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PStackTraceElement) ProtoMessage() {}

func (x *PStackTraceElement) ProtoReflect() protoreflect.Message {
	mi := &file_v1_Span_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PStackTraceElement.ProtoReflect.Descriptor instead.
func (*PStackTraceElement) Descriptor() ([]byte, []int) {
	return file_v1_Span_proto_rawDescGZIP(), []int{20}
}

func (x *PStackTraceElement) GetClassName() string {
	if x != nil {
		return x.ClassName
	}
	return ""
}

func (x *PStackTraceElement) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *PStackTraceElement) GetLineNumber() int32 {
	if x != nil {
		return x.LineNumber
	}
	return 0
}

func (x *PStackTraceElement) GetMethodName() string {
	if x != nil {
		return x.MethodName
	}
	return ""
}

// Supported since 3.1.0
type PAttributeValue struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Field:
	//
	//	*PAttributeValue_StringValue
	//	*PAttributeValue_BoolValue
	//	*PAttributeValue_LongValue
	//	*PAttributeValue_DoubleValue
	//	*PAttributeValue_BinaryValue
	//	*PAttributeValue_ArrayValue
	//	*PAttributeValue_KvlistValue
	Field         isPAttributeValue_Field `protobuf_oneof:"field"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PAttributeValue) Reset() {
	*x = PAttributeValue{}
	mi := &file_v1_Span_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PAttributeValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PAttributeValue) ProtoMessage() {}

func (x *PAttributeValue) ProtoReflect() protoreflect.Message {
	mi := &file_v1_Span_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PAttributeValue.ProtoReflect.Descriptor instead.
func (*PAttributeValue) Descriptor() ([]byte, []int) {
	return file_v1_Span_proto_rawDescGZIP(), []int{21}
}

func (x *PAttributeValue) GetField() isPAttributeValue_Field {
	if x != nil {
		return x.Field
	}
	return nil
}

func (x *PAttributeValue) GetStringValue() string {
	if x != nil {
		if x, ok := x.Field.(*PAttributeValue_StringValue); ok {
			return x.StringValue
		}
	}
	return ""
}

func (x *PAttributeValue) GetBoolValue() bool {
	if x != nil {
		if x, ok := x.Field.(*PAttributeValue_BoolValue); ok {
			return x.BoolValue
		}
	}
	return false
}

func (x *PAttributeValue) GetLongValue() int64 {
	if x != nil {
		if x, ok := x.Field.(*PAttributeValue_LongValue); ok {
			return x.LongValue
		}
	}
	return 0
}

func (x *PAttributeValue) GetDoubleValue() float64 {
	if x != nil {
		if x, ok := x.Field.(*PAttributeValue_DoubleValue); ok {
			return x.DoubleValue
		}
	}
	return 0
}

func (x *PAttributeValue) GetBinaryValue() []byte {
	if x != nil {
		if x, ok := x.Field.(*PAttributeValue_BinaryValue); ok {
			return x.BinaryValue
		}
	}
	return nil
}

func (x *PAttributeValue) GetArrayValue() *PAttributeArrayValue {
	if x != nil {
		if x, ok := x.Field.(*PAttributeValue_ArrayValue); ok {
			return x.ArrayValue
		}
	}
	return nil
}

func (x *PAttributeValue) GetKvlistValue() *PAttributeKeyValueList {
	if x != nil {
		if x, ok := x.Field.(*PAttributeValue_KvlistValue); ok {
			return x.KvlistValue
		}
	}
	return nil
}

type isPAttributeValue_Field interface {
	isPAttributeValue_Field()
}

type PAttributeValue_StringValue struct {
	StringValue string `protobuf:"bytes,1,opt,name=stringValue,proto3,oneof"`
}

type PAttributeValue_BoolValue struct {
	BoolValue bool `protobuf:"varint,2,opt,name=boolValue,proto3,oneof"`
}

type PAttributeValue_LongValue struct {
	LongValue int64 `protobuf:"varint,3,opt,name=longValue,proto3,oneof"`
}

type PAttributeValue_DoubleValue struct {
	DoubleValue float64 `protobuf:"fixed64,4,opt,name=doubleValue,proto3,oneof"`
}

type PAttributeValue_BinaryValue struct {
	BinaryValue []byte `protobuf:"bytes,5,opt,name=binaryValue,proto3,oneof"`
}

type PAttributeValue_ArrayValue struct {
	ArrayValue *PAttributeArrayValue `protobuf:"bytes,6,opt,name=arrayValue,proto3,oneof"`
}

type PAttributeValue_KvlistValue struct {
	KvlistValue *PAttributeKeyValueList `protobuf:"bytes,7,opt,name=kvlistValue,proto3,oneof"`
}

func (*PAttributeValue_StringValue) isPAttributeValue_Field() {}

func (*PAttributeValue_BoolValue) isPAttributeValue_Field() {}

func (*PAttributeValue_LongValue) isPAttributeValue_Field() {}

func (*PAttributeValue_DoubleValue) isPAttributeValue_Field() {}

func (*PAttributeValue_BinaryValue) isPAttributeValue_Field() {}

func (*PAttributeValue_ArrayValue) isPAttributeValue_Field() {}

func (*PAttributeValue_KvlistValue) isPAttributeValue_Field() {}

// Supported since 3.1.0
type PAttributeArrayValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []*PAttributeValue     `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PAttributeArrayValue) Reset() {
	*x = PAttributeArrayValue{}
	mi := &file_v1_Span_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PAttributeArrayValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PAttributeArrayValue) ProtoMessage() {}

func (x *PAttributeArrayValue) ProtoReflect() protoreflect.Message {
	mi := &file_v1_Span_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PAttributeArrayValue.ProtoReflect.Descriptor instead.
func (*PAttributeArrayValue) Descriptor() ([]byte, []int) {
	return file_v1_Span_proto_rawDescGZIP(), []int{22}
}

func (x *PAttributeArrayValue) GetValues() []*PAttributeValue {
	if x != nil {
		return x.Values
	}
	return nil
}

// Supported since 3.1.0
type PAttributeKeyValueList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []*PAttribute          `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PAttributeKeyValueList) Reset() {
	*x = PAttributeKeyValueList{}
	mi := &file_v1_Span_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PAttributeKeyValueList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PAttributeKeyValueList) ProtoMessage() {}

func (x *PAttributeKeyValueList) ProtoReflect() protoreflect.Message {
	mi := &file_v1_Span_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PAttributeKeyValueList.ProtoReflect.Descriptor instead.
func (*PAttributeKeyValueList) Descriptor() ([]byte, []int) {
	return file_v1_Span_proto_rawDescGZIP(), []int{23}
}

func (x *PAttributeKeyValueList) GetValues() []*PAttribute {
	if x != nil {
		return x.Values
	}
	return nil
}

// Supported since 3.1.0
type PAttribute struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         *PAttributeValue       `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PAttribute) Reset() {
	*x = PAttribute{}
	mi := &file_v1_Span_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PAttribute) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PAttribute) ProtoMessage() {}

func (x *PAttribute) ProtoReflect() protoreflect.Message {
	mi := &file_v1_Span_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PAttribute.ProtoReflect.Descriptor instead.
func (*PAttribute) Descriptor() ([]byte, []int) {
	return file_v1_Span_proto_rawDescGZIP(), []int{24}
}

func (x *PAttribute) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *PAttribute) GetValue() *PAttributeValue {
	if x != nil {
		return x.Value
	}
	return nil
}

var File_v1_Span_proto protoreflect.FileDescriptor

const file_v1_Span_proto_rawDesc = "" +
	"\n" +
	"\rv1/Span.proto\x12\x02v1\x1a\x13v1/Annotation.proto\"h\n" +
	"\fPSpanMessage\x12\x1f\n" +
	"\x04span\x18\x01 \x01(\v2\t.v1.PSpanH\x00R\x04span\x12.\n" +
	"\tspanChunk\x18\x02 \x01(\v2\x0e.v1.PSpanChunkH\x00R\tspanChunkB\a\n" +
	"\x05field\"9\n" +
	"\x11PSpanMessageBatch\x12$\n" +
	"\x04span\x18\x01 \x03(\v2\x10.v1.PSpanMessageR\x04span\"P\n" +
	"\x10PSpanResultBatch\x12<\n" +
	"\x0fpartial_success\x18\x01 \x01(\v2\x13.v1.PPartialSuccessR\x0epartialSuccess\"w\n" +
	"\x0fPPartialSuccess\x12%\n" +
	"\x0erejected_spans\x18\x01 \x01(\x03R\rrejectedSpans\x12\x18\n" +
	"\aerrorId\x18\x02 \x01(\x03R\aerrorId\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\"\xa1\x05\n" +
	"\x05PSpan\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x05R\aversion\x128\n" +
	"\rtransactionId\x18\x02 \x01(\v2\x12.v1.PTransactionIdR\rtransactionId\x12\x1a\n" +
	"\x06spanId\x18\x03 \x01(\x10B\x020\x01R\x06spanId\x12&\n" +
	"\fparentSpanId\x18\x04 \x01(\x10B\x020\x01R\fparentSpanId\x12\x1c\n" +
	"\tstartTime\x18\x05 \x01(\x03R\tstartTime\x12\x18\n" +
	"\aelapsed\x18\x06 \x01(\x05R\aelapsed\x12\x14\n" +
	"\x05apiId\x18\a \x01(\x05R\x05apiId\x12 \n" +
	"\vserviceType\x18\b \x01(\x05R\vserviceType\x122\n" +
	"\vacceptEvent\x18\t \x01(\v2\x10.v1.PAcceptEventR\vacceptEvent\x12/\n" +
	"\n" +
	"annotation\x18\n" +
	" \x03(\v2\x0f.v1.PAnnotationR\n" +
	"annotation\x12\x12\n" +
	"\x04flag\x18\v \x01(\x05R\x04flag\x12\x10\n" +
	"\x03err\x18\f \x01(\x11R\x03err\x12,\n" +
	"\tspanEvent\x18\r \x03(\v2\x0e.v1.PSpanEventR\tspanEvent\x129\n" +
	"\rexceptionInfo\x18\x0e \x01(\v2\x13.v1.PIntStringValueR\rexceptionInfo\x126\n" +
	"\x16applicationServiceType\x18\x0f \x01(\x05R\x16applicationServiceType\x126\n" +
	"\x16loggingTransactionInfo\x18\x10 \x01(\x05R\x16loggingTransactionInfo\x12,\n" +
	"\tattribute\x18\x11 \x03(\v2\x0e.v1.PAttributeR\tattribute\"v\n" +
	"\x0ePTransactionId\x12\x18\n" +
	"\aagentId\x18\x01 \x01(\tR\aagentId\x12*\n" +
	"\x0eagentStartTime\x18\x02 \x01(\x03B\x020\x01R\x0eagentStartTime\x12\x1e\n" +
	"\bsequence\x18\x03 \x01(\x03B\x020\x01R\bsequence\"\x8d\x01\n" +
	"\fPAcceptEvent\x12\x10\n" +
	"\x03rpc\x18\x01 \x01(\tR\x03rpc\x12\x1a\n" +
	"\bendPoint\x18\x02 \x01(\tR\bendPoint\x12\x1e\n" +
	"\n" +
	"remoteAddr\x18\x03 \x01(\tR\n" +
	"remoteAddr\x12/\n" +
	"\n" +
	"parentInfo\x18\x04 \x01(\v2\x0f.v1.PParentInfoR\n" +
	"parentInfo\"\xcb\x01\n" +
	"\vPParentInfo\x124\n" +
	"\x15parentApplicationName\x18\x01 \x01(\tR\x15parentApplicationName\x124\n" +
	"\x15parentApplicationType\x18\x02 \x01(\x05R\x15parentApplicationType\x12\"\n" +
	"\facceptorHost\x18\x03 \x01(\tR\facceptorHost\x12,\n" +
	"\x11parentServiceName\x18\x04 \x01(\tR\x11parentServiceName\"E\n" +
	"\rPLocalAsyncId\x12\x18\n" +
	"\aasyncId\x18\x01 \x01(\x05R\aasyncId\x12\x1a\n" +
	"\bsequence\x18\x02 \x01(\x05R\bsequence\"\xa2\x03\n" +
	"\n" +
	"PSpanEvent\x12\x1a\n" +
	"\bsequence\x18\x01 \x01(\x05R\bsequence\x12\x14\n" +
	"\x05depth\x18\x02 \x01(\x05R\x05depth\x12\"\n" +
	"\fstartElapsed\x18\x03 \x01(\x05R\fstartElapsed\x12\x1e\n" +
	"\n" +
	"endElapsed\x18\x04 \x01(\x05R\n" +
	"endElapsed\x12 \n" +
	"\vserviceType\x18\x05 \x01(\x11R\vserviceType\x12/\n" +
	"\n" +
	"annotation\x18\x06 \x03(\v2\x0f.v1.PAnnotationR\n" +
	"annotation\x12\x14\n" +
	"\x05apiId\x18\n" +
	" \x01(\x11R\x05apiId\x129\n" +
	"\rexceptionInfo\x18\v \x01(\v2\x13.v1.PIntStringValueR\rexceptionInfo\x12,\n" +
	"\tnextEvent\x18\f \x01(\v2\x0e.v1.PNextEventR\tnextEvent\x12\x1e\n" +
	"\n" +
	"asyncEvent\x18\r \x01(\x05R\n" +
	"asyncEvent\x12,\n" +
	"\tattribute\x18\x0e \x03(\v2\x0e.v1.PAttributeR\tattribute\"N\n" +
	"\n" +
	"PNextEvent\x127\n" +
	"\fmessageEvent\x18\x01 \x01(\v2\x11.v1.PMessageEventH\x00R\fmessageEventB\a\n" +
	"\x05field\"u\n" +
	"\rPMessageEvent\x12\"\n" +
	"\n" +
	"nextSpanId\x18\x01 \x01(\x10B\x020\x01R\n" +
	"nextSpanId\x12\x1a\n" +
	"\bendPoint\x18\x02 \x01(\tR\bendPoint\x12$\n" +
	"\rdestinationId\x18\x03 \x01(\tR\rdestinationId\"\xcf\x02\n" +
	"\n" +
	"PSpanChunk\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x05R\aversion\x128\n" +
	"\rtransactionId\x18\x02 \x01(\v2\x12.v1.PTransactionIdR\rtransactionId\x12\x1a\n" +
	"\x06spanId\x18\x03 \x01(\x10B\x020\x01R\x06spanId\x12\x1a\n" +
	"\bendPoint\x18\x04 \x01(\tR\bendPoint\x12,\n" +
	"\tspanEvent\x18\x05 \x03(\v2\x0e.v1.PSpanEventR\tspanEvent\x126\n" +
	"\x16applicationServiceType\x18\x06 \x01(\x05R\x16applicationServiceType\x12\x18\n" +
	"\akeyTime\x18\a \x01(\x03R\akeyTime\x125\n" +
	"\flocalAsyncId\x18\b \x01(\v2\x11.v1.PLocalAsyncIdR\flocalAsyncId\"=\n" +
	"\aPResult\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"6\n" +
	"\fPSqlMetaData\x12\x14\n" +
	"\x05sqlId\x18\x01 \x01(\x05R\x05sqlId\x12\x10\n" +
	"\x03sql\x18\x02 \x01(\tR\x03sql\";\n" +
	"\x0fPSqlUidMetaData\x12\x16\n" +
	"\x06sqlUid\x18\x01 \x01(\fR\x06sqlUid\x12\x10\n" +
	"\x03sql\x18\x02 \x01(\tR\x03sql\"\x82\x01\n" +
	"\fPApiMetaData\x12\x14\n" +
	"\x05apiId\x18\x01 \x01(\x05R\x05apiId\x12\x18\n" +
	"\aapiInfo\x18\x02 \x01(\tR\aapiInfo\x12\x12\n" +
	"\x04line\x18\x03 \x01(\x05R\x04line\x12\x12\n" +
	"\x04type\x18\x04 \x01(\x05R\x04type\x12\x1a\n" +
	"\blocation\x18\x05 \x01(\tR\blocation\"O\n" +
	"\x0fPStringMetaData\x12\x1a\n" +
	"\bstringId\x18\x01 \x01(\x05R\bstringId\x12 \n" +
	"\vstringValue\x18\x02 \x01(\tR\vstringValue\"\xbc\x01\n" +
	"\x12PExceptionMetaData\x12.\n" +
	"\n" +
	"exceptions\x18\x01 \x03(\v2\x0e.v1.PExceptionR\n" +
	"exceptions\x128\n" +
	"\rtransactionId\x18\x02 \x01(\v2\x12.v1.PTransactionIdR\rtransactionId\x12\x1a\n" +
	"\x06spanId\x18\x03 \x01(\x10B\x020\x01R\x06spanId\x12 \n" +
	"\vuriTemplate\x18\x04 \x01(\tR\vuriTemplate\"\x96\x02\n" +
	"\n" +
	"PException\x12.\n" +
	"\x12exceptionClassName\x18\x01 \x01(\tR\x12exceptionClassName\x12*\n" +
	"\x10exceptionMessage\x18\x02 \x01(\tR\x10exceptionMessage\x12\x1c\n" +
	"\tstartTime\x18\x03 \x01(\x03R\tstartTime\x12 \n" +
	"\vexceptionId\x18\x04 \x01(\x03R\vexceptionId\x12&\n" +
	"\x0eexceptionDepth\x18\x05 \x01(\x05R\x0eexceptionDepth\x12D\n" +
	"\x11stackTraceElement\x18\x06 \x03(\v2\x16.v1.PStackTraceElementR\x11stackTraceElement\"\x8e\x01\n" +
	"\x12PStackTraceElement\x12\x1c\n" +
	"\tclassName\x18\x01 \x01(\tR\tclassName\x12\x1a\n" +
	"\bfileName\x18\x02 \x01(\tR\bfileName\x12\x1e\n" +
	"\n" +
	"lineNumber\x18\x03 \x01(\x05R\n" +
	"lineNumber\x12\x1e\n" +
	"\n" +
	"methodName\x18\x04 \x01(\tR\n" +
	"methodName\"\xc2\x02\n" +
	"\x0fPAttributeValue\x12\"\n" +
	"\vstringValue\x18\x01 \x01(\tH\x00R\vstringValue\x12\x1e\n" +
	"\tboolValue\x18\x02 \x01(\bH\x00R\tboolValue\x12\x1e\n" +
	"\tlongValue\x18\x03 \x01(\x03H\x00R\tlongValue\x12\"\n" +
	"\vdoubleValue\x18\x04 \x01(\x01H\x00R\vdoubleValue\x12\"\n" +
	"\vbinaryValue\x18\x05 \x01(\fH\x00R\vbinaryValue\x12:\n" +
	"\n" +
	"arrayValue\x18\x06 \x01(\v2\x18.v1.PAttributeArrayValueH\x00R\n" +
	"arrayValue\x12>\n" +
	"\vkvlistValue\x18\a \x01(\v2\x1a.v1.PAttributeKeyValueListH\x00R\vkvlistValueB\a\n" +
	"\x05field\"C\n" +
	"\x14PAttributeArrayValue\x12+\n" +
	"\x06values\x18\x01 \x03(\v2\x13.v1.PAttributeValueR\x06values\"@\n" +
	"\x16PAttributeKeyValueList\x12&\n" +
	"\x06values\x18\x01 \x03(\v2\x0e.v1.PAttributeR\x06values\"I\n" +
	"\n" +
	"PAttribute\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12)\n" +
	"\x05value\x18\x02 \x01(\v2\x13.v1.PAttributeValueR\x05valueB5\n" +
	"!com.navercorp.pinpoint.grpc.traceB\tSpanProtoP\x01Z\x03/v1b\x06proto3"

var (
	file_v1_Span_proto_rawDescOnce sync.Once
	file_v1_Span_proto_rawDescData []byte
)

func file_v1_Span_proto_rawDescGZIP() []byte {
	file_v1_Span_proto_rawDescOnce.Do(func() {
		file_v1_Span_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_Span_proto_rawDesc), len(file_v1_Span_proto_rawDesc)))
	})
	return file_v1_Span_proto_rawDescData
}

var file_v1_Span_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_v1_Span_proto_goTypes = []any{
	(*PSpanMessage)(nil),           // 0: v1.PSpanMessage
	(*PSpanMessageBatch)(nil),      // 1: v1.PSpanMessageBatch
	(*PSpanResultBatch)(nil),       // 2: v1.PSpanResultBatch
	(*PPartialSuccess)(nil),        // 3: v1.PPartialSuccess
	(*PSpan)(nil),                  // 4: v1.PSpan
	(*PTransactionId)(nil),         // 5: v1.PTransactionId
	(*PAcceptEvent)(nil),           // 6: v1.PAcceptEvent
	(*PParentInfo)(nil),            // 7: v1.PParentInfo
	(*PLocalAsyncId)(nil),          // 8: v1.PLocalAsyncId
	(*PSpanEvent)(nil),             // 9: v1.PSpanEvent
	(*PNextEvent)(nil),             // 10: v1.PNextEvent
	(*PMessageEvent)(nil),          // 11: v1.PMessageEvent
	(*PSpanChunk)(nil),             // 12: v1.PSpanChunk
	(*PResult)(nil),                // 13: v1.PResult
	(*PSqlMetaData)(nil),           // 14: v1.PSqlMetaData
	(*PSqlUidMetaData)(nil),        // 15: v1.PSqlUidMetaData
	(*PApiMetaData)(nil),           // 16: v1.PApiMetaData
	(*PStringMetaData)(nil),        // 17: v1.PStringMetaData
	(*PExceptionMetaData)(nil),     // 18: v1.PExceptionMetaData
	(*PException)(nil),             // 19: v1.PException
	(*PStackTraceElement)(nil),     // 20: v1.PStackTraceElement
	(*PAttributeValue)(nil),        // 21: v1.PAttributeValue
	(*PAttributeArrayValue)(nil),   // 22: v1.PAttributeArrayValue
	(*PAttributeKeyValueList)(nil), // 23: v1.PAttributeKeyValueList
	(*PAttribute)(nil),             // 24: v1.PAttribute
	(*PAnnotation)(nil),            // 25: v1.PAnnotation
	(*PIntStringValue)(nil),        // 26: v1.PIntStringValue
}
var file_v1_Span_proto_depIdxs = []int32{
	4,  // 0: v1.PSpanMessage.span:type_name -> v1.PSpan
	12, // 1: v1.PSpanMessage.spanChunk:type_name -> v1.PSpanChunk
	0,  // 2: v1.PSpanMessageBatch.span:type_name -> v1.PSpanMessage
	3,  // 3: v1.PSpanResultBatch.partial_success:type_name -> v1.PPartialSuccess
	5,  // 4: v1.PSpan.transactionId:type_name -> v1.PTransactionId
	6,  // 5: v1.PSpan.acceptEvent:type_name -> v1.PAcceptEvent
	25, // 6: v1.PSpan.annotation:type_name -> v1.PAnnotation
	9,  // 7: v1.PSpan.spanEvent:type_name -> v1.PSpanEvent
	26, // 8: v1.PSpan.exceptionInfo:type_name -> v1.PIntStringValue
	24, // 9: v1.PSpan.attribute:type_name -> v1.PAttribute
	7,  // 10: v1.PAcceptEvent.parentInfo:type_name -> v1.PParentInfo
	25, // 11: v1.PSpanEvent.annotation:type_name -> v1.PAnnotation
	26, // 12: v1.PSpanEvent.exceptionInfo:type_name -> v1.PIntStringValue
	10, // 13: v1.PSpanEvent.nextEvent:type_name -> v1.PNextEvent
	24, // 14: v1.PSpanEvent.attribute:type_name -> v1.PAttribute
	11, // 15: v1.PNextEvent.messageEvent:type_name -> v1.PMessageEvent
	5,  // 16: v1.PSpanChunk.transactionId:type_name -> v1.PTransactionId
	9,  // 17: v1.PSpanChunk.spanEvent:type_name -> v1.PSpanEvent
	8,  // 18: v1.PSpanChunk.localAsyncId:type_name -> v1.PLocalAsyncId
	19, // 19: v1.PExceptionMetaData.exceptions:type_name -> v1.PException
	5,  // 20: v1.PExceptionMetaData.transactionId:type_name -> v1.PTransactionId
	20, // 21: v1.PException.stackTraceElement:type_name -> v1.PStackTraceElement
	22, // 22: v1.PAttributeValue.arrayValue:type_name -> v1.PAttributeArrayValue
	23, // 23: v1.PAttributeValue.kvlistValue:type_name -> v1.PAttributeKeyValueList
	21, // 24: v1.PAttributeArrayValue.values:type_name -> v1.PAttributeValue
	24, // 25: v1.PAttributeKeyValueList.values:type_name -> v1.PAttribute
	21, // 26: v1.PAttribute.value:type_name -> v1.PAttributeValue
	27, // [27:27] is the sub-list for method output_type
	27, // [27:27] is the sub-list for method input_type
	27, // [27:27] is the sub-list for extension type_name
	27, // [27:27] is the sub-list for extension extendee
	0,  // [0:27] is the sub-list for field type_name
}

func init() { file_v1_Span_proto_init() }
func file_v1_Span_proto_init() {
	if File_v1_Span_proto != nil {
		return
	}
	file_v1_Annotation_proto_init()
	file_v1_Span_proto_msgTypes[0].OneofWrappers = []any{
		(*PSpanMessage_Span)(nil),
		(*PSpanMessage_SpanChunk)(nil),
	}
	file_v1_Span_proto_msgTypes[10].OneofWrappers = []any{
		(*PNextEvent_MessageEvent)(nil),
	}
	file_v1_Span_proto_msgTypes[21].OneofWrappers = []any{
		(*PAttributeValue_StringValue)(nil),
		(*PAttributeValue_BoolValue)(nil),
		(*PAttributeValue_LongValue)(nil),
		(*PAttributeValue_DoubleValue)(nil),
		(*PAttributeValue_BinaryValue)(nil),
		(*PAttributeValue_ArrayValue)(nil),
		(*PAttributeValue_KvlistValue)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_Span_proto_rawDesc), len(file_v1_Span_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1_Span_proto_goTypes,
		DependencyIndexes: file_v1_Span_proto_depIdxs,
		MessageInfos:      file_v1_Span_proto_msgTypes,
	}.Build()
	File_v1_Span_proto = out.File
	file_v1_Span_proto_goTypes = nil
	file_v1_Span_proto_depIdxs = nil
}
