// Code generated by protoc-gen-go. DO NOT EDIT.
// source: v1/Stat.proto

package v1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PJvmGcType int32

const (
	PJvmGcType_JVM_GC_TYPE_UNKNOWN  PJvmGcType = 0
	PJvmGcType_JVM_GC_TYPE_SERIAL   PJvmGcType = 1
	PJvmGcType_JVM_GC_TYPE_PARALLEL PJvmGcType = 2
	PJvmGcType_JVM_GC_TYPE_CMS      PJvmGcType = 3
	PJvmGcType_JVM_GC_TYPE_G1       PJvmGcType = 4
)

var PJvmGcType_name = map[int32]string{
	0: "JVM_GC_TYPE_UNKNOWN",
	1: "JVM_GC_TYPE_SERIAL",
	2: "JVM_GC_TYPE_PARALLEL",
	3: "JVM_GC_TYPE_CMS",
	4: "JVM_GC_TYPE_G1",
}

var PJvmGcType_value = map[string]int32{
	"JVM_GC_TYPE_UNKNOWN":  0,
	"JVM_GC_TYPE_SERIAL":   1,
	"JVM_GC_TYPE_PARALLEL": 2,
	"JVM_GC_TYPE_CMS":      3,
	"JVM_GC_TYPE_G1":       4,
}

func (x PJvmGcType) String() string {
	return proto.EnumName(PJvmGcType_name, int32(x))
}

func (PJvmGcType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_708c871858e42d40, []int{0}
}

type PPing struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PPing) Reset()         { *m = PPing{} }
func (m *PPing) String() string { return proto.CompactTextString(m) }
func (*PPing) ProtoMessage()    {}
func (*PPing) Descriptor() ([]byte, []int) {
	return fileDescriptor_708c871858e42d40, []int{0}
}

func (m *PPing) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PPing.Unmarshal(m, b)
}
func (m *PPing) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PPing.Marshal(b, m, deterministic)
}
func (m *PPing) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PPing.Merge(m, src)
}
func (m *PPing) XXX_Size() int {
	return xxx_messageInfo_PPing.Size(m)
}
func (m *PPing) XXX_DiscardUnknown() {
	xxx_messageInfo_PPing.DiscardUnknown(m)
}

var xxx_messageInfo_PPing proto.InternalMessageInfo

type PStatMessage struct {
	// Types that are valid to be assigned to Field:
	//	*PStatMessage_AgentStat
	//	*PStatMessage_AgentStatBatch
	//	*PStatMessage_AgentUriStat
	Field                isPStatMessage_Field `protobuf_oneof:"field"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *PStatMessage) Reset()         { *m = PStatMessage{} }
func (m *PStatMessage) String() string { return proto.CompactTextString(m) }
func (*PStatMessage) ProtoMessage()    {}
func (*PStatMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_708c871858e42d40, []int{1}
}

func (m *PStatMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PStatMessage.Unmarshal(m, b)
}
func (m *PStatMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PStatMessage.Marshal(b, m, deterministic)
}
func (m *PStatMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PStatMessage.Merge(m, src)
}
func (m *PStatMessage) XXX_Size() int {
	return xxx_messageInfo_PStatMessage.Size(m)
}
func (m *PStatMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_PStatMessage.DiscardUnknown(m)
}

var xxx_messageInfo_PStatMessage proto.InternalMessageInfo

type isPStatMessage_Field interface {
	isPStatMessage_Field()
}

type PStatMessage_AgentStat struct {
	AgentStat *PAgentStat `protobuf:"bytes,1,opt,name=agentStat,proto3,oneof"`
}

type PStatMessage_AgentStatBatch struct {
	AgentStatBatch *PAgentStatBatch `protobuf:"bytes,2,opt,name=agentStatBatch,proto3,oneof"`
}

type PStatMessage_AgentUriStat struct {
	AgentUriStat *PAgentUriStat `protobuf:"bytes,3,opt,name=agentUriStat,proto3,oneof"`
}

func (*PStatMessage_AgentStat) isPStatMessage_Field() {}

func (*PStatMessage_AgentStatBatch) isPStatMessage_Field() {}

func (*PStatMessage_AgentUriStat) isPStatMessage_Field() {}

func (m *PStatMessage) GetField() isPStatMessage_Field {
	if m != nil {
		return m.Field
	}
	return nil
}

func (m *PStatMessage) GetAgentStat() *PAgentStat {
	if x, ok := m.GetField().(*PStatMessage_AgentStat); ok {
		return x.AgentStat
	}
	return nil
}

func (m *PStatMessage) GetAgentStatBatch() *PAgentStatBatch {
	if x, ok := m.GetField().(*PStatMessage_AgentStatBatch); ok {
		return x.AgentStatBatch
	}
	return nil
}

func (m *PStatMessage) GetAgentUriStat() *PAgentUriStat {
	if x, ok := m.GetField().(*PStatMessage_AgentUriStat); ok {
		return x.AgentUriStat
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*PStatMessage) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*PStatMessage_AgentStat)(nil),
		(*PStatMessage_AgentStatBatch)(nil),
		(*PStatMessage_AgentUriStat)(nil),
	}
}

type PAgentInfo struct {
	Hostname             string           `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Ip                   string           `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`
	Ports                string           `protobuf:"bytes,3,opt,name=ports,proto3" json:"ports,omitempty"`
	ServiceType          int32            `protobuf:"varint,4,opt,name=serviceType,proto3" json:"serviceType,omitempty"`
	Pid                  int32            `protobuf:"varint,5,opt,name=pid,proto3" json:"pid,omitempty"`
	AgentVersion         string           `protobuf:"bytes,6,opt,name=agentVersion,proto3" json:"agentVersion,omitempty"`
	VmVersion            string           `protobuf:"bytes,7,opt,name=vmVersion,proto3" json:"vmVersion,omitempty"`
	EndTimestamp         int64            `protobuf:"varint,8,opt,name=endTimestamp,proto3" json:"endTimestamp,omitempty"`
	EndStatus            int32            `protobuf:"varint,9,opt,name=endStatus,proto3" json:"endStatus,omitempty"`
	ServerMetaData       *PServerMetaData `protobuf:"bytes,10,opt,name=serverMetaData,proto3" json:"serverMetaData,omitempty"`
	JvmInfo              *PJvmInfo        `protobuf:"bytes,11,opt,name=jvmInfo,proto3" json:"jvmInfo,omitempty"`
	Container            bool             `protobuf:"varint,12,opt,name=container,proto3" json:"container,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *PAgentInfo) Reset()         { *m = PAgentInfo{} }
func (m *PAgentInfo) String() string { return proto.CompactTextString(m) }
func (*PAgentInfo) ProtoMessage()    {}
func (*PAgentInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_708c871858e42d40, []int{2}
}

func (m *PAgentInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PAgentInfo.Unmarshal(m, b)
}
func (m *PAgentInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PAgentInfo.Marshal(b, m, deterministic)
}
func (m *PAgentInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PAgentInfo.Merge(m, src)
}
func (m *PAgentInfo) XXX_Size() int {
	return xxx_messageInfo_PAgentInfo.Size(m)
}
func (m *PAgentInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_PAgentInfo.DiscardUnknown(m)
}

var xxx_messageInfo_PAgentInfo proto.InternalMessageInfo

func (m *PAgentInfo) GetHostname() string {
	if m != nil {
		return m.Hostname
	}
	return ""
}

func (m *PAgentInfo) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *PAgentInfo) GetPorts() string {
	if m != nil {
		return m.Ports
	}
	return ""
}

func (m *PAgentInfo) GetServiceType() int32 {
	if m != nil {
		return m.ServiceType
	}
	return 0
}

func (m *PAgentInfo) GetPid() int32 {
	if m != nil {
		return m.Pid
	}
	return 0
}

func (m *PAgentInfo) GetAgentVersion() string {
	if m != nil {
		return m.AgentVersion
	}
	return ""
}

func (m *PAgentInfo) GetVmVersion() string {
	if m != nil {
		return m.VmVersion
	}
	return ""
}

func (m *PAgentInfo) GetEndTimestamp() int64 {
	if m != nil {
		return m.EndTimestamp
	}
	return 0
}

func (m *PAgentInfo) GetEndStatus() int32 {
	if m != nil {
		return m.EndStatus
	}
	return 0
}

func (m *PAgentInfo) GetServerMetaData() *PServerMetaData {
	if m != nil {
		return m.ServerMetaData
	}
	return nil
}

func (m *PAgentInfo) GetJvmInfo() *PJvmInfo {
	if m != nil {
		return m.JvmInfo
	}
	return nil
}

func (m *PAgentInfo) GetContainer() bool {
	if m != nil {
		return m.Container
	}
	return false
}

type PServerMetaData struct {
	ServerInfo           string          `protobuf:"bytes,1,opt,name=serverInfo,proto3" json:"serverInfo,omitempty"`
	VmArg                []string        `protobuf:"bytes,2,rep,name=vmArg,proto3" json:"vmArg,omitempty"`
	ServiceInfo          []*PServiceInfo `protobuf:"bytes,3,rep,name=serviceInfo,proto3" json:"serviceInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *PServerMetaData) Reset()         { *m = PServerMetaData{} }
func (m *PServerMetaData) String() string { return proto.CompactTextString(m) }
func (*PServerMetaData) ProtoMessage()    {}
func (*PServerMetaData) Descriptor() ([]byte, []int) {
	return fileDescriptor_708c871858e42d40, []int{3}
}

func (m *PServerMetaData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PServerMetaData.Unmarshal(m, b)
}
func (m *PServerMetaData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PServerMetaData.Marshal(b, m, deterministic)
}
func (m *PServerMetaData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PServerMetaData.Merge(m, src)
}
func (m *PServerMetaData) XXX_Size() int {
	return xxx_messageInfo_PServerMetaData.Size(m)
}
func (m *PServerMetaData) XXX_DiscardUnknown() {
	xxx_messageInfo_PServerMetaData.DiscardUnknown(m)
}

var xxx_messageInfo_PServerMetaData proto.InternalMessageInfo

func (m *PServerMetaData) GetServerInfo() string {
	if m != nil {
		return m.ServerInfo
	}
	return ""
}

func (m *PServerMetaData) GetVmArg() []string {
	if m != nil {
		return m.VmArg
	}
	return nil
}

func (m *PServerMetaData) GetServiceInfo() []*PServiceInfo {
	if m != nil {
		return m.ServiceInfo
	}
	return nil
}

type PServiceInfo struct {
	ServiceName          string   `protobuf:"bytes,1,opt,name=serviceName,proto3" json:"serviceName,omitempty"`
	ServiceLib           []string `protobuf:"bytes,2,rep,name=serviceLib,proto3" json:"serviceLib,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PServiceInfo) Reset()         { *m = PServiceInfo{} }
func (m *PServiceInfo) String() string { return proto.CompactTextString(m) }
func (*PServiceInfo) ProtoMessage()    {}
func (*PServiceInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_708c871858e42d40, []int{4}
}

func (m *PServiceInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PServiceInfo.Unmarshal(m, b)
}
func (m *PServiceInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PServiceInfo.Marshal(b, m, deterministic)
}
func (m *PServiceInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PServiceInfo.Merge(m, src)
}
func (m *PServiceInfo) XXX_Size() int {
	return xxx_messageInfo_PServiceInfo.Size(m)
}
func (m *PServiceInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_PServiceInfo.DiscardUnknown(m)
}

var xxx_messageInfo_PServiceInfo proto.InternalMessageInfo

func (m *PServiceInfo) GetServiceName() string {
	if m != nil {
		return m.ServiceName
	}
	return ""
}

func (m *PServiceInfo) GetServiceLib() []string {
	if m != nil {
		return m.ServiceLib
	}
	return nil
}

type PJvmInfo struct {
	Version              int32      `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	VmVersion            string     `protobuf:"bytes,2,opt,name=vmVersion,proto3" json:"vmVersion,omitempty"`
	GcType               PJvmGcType `protobuf:"varint,3,opt,name=gcType,proto3,enum=v1.PJvmGcType" json:"gcType,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *PJvmInfo) Reset()         { *m = PJvmInfo{} }
func (m *PJvmInfo) String() string { return proto.CompactTextString(m) }
func (*PJvmInfo) ProtoMessage()    {}
func (*PJvmInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_708c871858e42d40, []int{5}
}

func (m *PJvmInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PJvmInfo.Unmarshal(m, b)
}
func (m *PJvmInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PJvmInfo.Marshal(b, m, deterministic)
}
func (m *PJvmInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PJvmInfo.Merge(m, src)
}
func (m *PJvmInfo) XXX_Size() int {
	return xxx_messageInfo_PJvmInfo.Size(m)
}
func (m *PJvmInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_PJvmInfo.DiscardUnknown(m)
}

var xxx_messageInfo_PJvmInfo proto.InternalMessageInfo

func (m *PJvmInfo) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *PJvmInfo) GetVmVersion() string {
	if m != nil {
		return m.VmVersion
	}
	return ""
}

func (m *PJvmInfo) GetGcType() PJvmGcType {
	if m != nil {
		return m.GcType
	}
	return PJvmGcType_JVM_GC_TYPE_UNKNOWN
}

type PAgentStat struct {
	Timestamp            int64            `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	CollectInterval      int64            `protobuf:"varint,2,opt,name=collectInterval,proto3" json:"collectInterval,omitempty"`
	Gc                   *PJvmGc          `protobuf:"bytes,3,opt,name=gc,proto3" json:"gc,omitempty"`
	CpuLoad              *PCpuLoad        `protobuf:"bytes,4,opt,name=cpuLoad,proto3" json:"cpuLoad,omitempty"`
	Transaction          *PTransaction    `protobuf:"bytes,5,opt,name=transaction,proto3" json:"transaction,omitempty"`
	ActiveTrace          *PActiveTrace    `protobuf:"bytes,6,opt,name=activeTrace,proto3" json:"activeTrace,omitempty"`
	DataSourceList       *PDataSourceList `protobuf:"bytes,7,opt,name=dataSourceList,proto3" json:"dataSourceList,omitempty"`
	ResponseTime         *PResponseTime   `protobuf:"bytes,8,opt,name=responseTime,proto3" json:"responseTime,omitempty"`
	Deadlock             *PDeadlock       `protobuf:"bytes,9,opt,name=deadlock,proto3" json:"deadlock,omitempty"`
	FileDescriptor       *PFileDescriptor `protobuf:"bytes,10,opt,name=fileDescriptor,proto3" json:"fileDescriptor,omitempty"`
	DirectBuffer         *PDirectBuffer   `protobuf:"bytes,11,opt,name=directBuffer,proto3" json:"directBuffer,omitempty"`
	Metadata             string           `protobuf:"bytes,12,opt,name=metadata,proto3" json:"metadata,omitempty"`
	TotalThread          *PTotalThread    `protobuf:"bytes,13,opt,name=totalThread,proto3" json:"totalThread,omitempty"`
	LoadedClass          *PLoadedClass    `protobuf:"bytes,14,opt,name=loadedClass,proto3" json:"loadedClass,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *PAgentStat) Reset()         { *m = PAgentStat{} }
func (m *PAgentStat) String() string { return proto.CompactTextString(m) }
func (*PAgentStat) ProtoMessage()    {}
func (*PAgentStat) Descriptor() ([]byte, []int) {
	return fileDescriptor_708c871858e42d40, []int{6}
}

func (m *PAgentStat) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PAgentStat.Unmarshal(m, b)
}
func (m *PAgentStat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PAgentStat.Marshal(b, m, deterministic)
}
func (m *PAgentStat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PAgentStat.Merge(m, src)
}
func (m *PAgentStat) XXX_Size() int {
	return xxx_messageInfo_PAgentStat.Size(m)
}
func (m *PAgentStat) XXX_DiscardUnknown() {
	xxx_messageInfo_PAgentStat.DiscardUnknown(m)
}

var xxx_messageInfo_PAgentStat proto.InternalMessageInfo

func (m *PAgentStat) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *PAgentStat) GetCollectInterval() int64 {
	if m != nil {
		return m.CollectInterval
	}
	return 0
}

func (m *PAgentStat) GetGc() *PJvmGc {
	if m != nil {
		return m.Gc
	}
	return nil
}

func (m *PAgentStat) GetCpuLoad() *PCpuLoad {
	if m != nil {
		return m.CpuLoad
	}
	return nil
}

func (m *PAgentStat) GetTransaction() *PTransaction {
	if m != nil {
		return m.Transaction
	}
	return nil
}

func (m *PAgentStat) GetActiveTrace() *PActiveTrace {
	if m != nil {
		return m.ActiveTrace
	}
	return nil
}

func (m *PAgentStat) GetDataSourceList() *PDataSourceList {
	if m != nil {
		return m.DataSourceList
	}
	return nil
}

func (m *PAgentStat) GetResponseTime() *PResponseTime {
	if m != nil {
		return m.ResponseTime
	}
	return nil
}

func (m *PAgentStat) GetDeadlock() *PDeadlock {
	if m != nil {
		return m.Deadlock
	}
	return nil
}

func (m *PAgentStat) GetFileDescriptor() *PFileDescriptor {
	if m != nil {
		return m.FileDescriptor
	}
	return nil
}

func (m *PAgentStat) GetDirectBuffer() *PDirectBuffer {
	if m != nil {
		return m.DirectBuffer
	}
	return nil
}

func (m *PAgentStat) GetMetadata() string {
	if m != nil {
		return m.Metadata
	}
	return ""
}

func (m *PAgentStat) GetTotalThread() *PTotalThread {
	if m != nil {
		return m.TotalThread
	}
	return nil
}

func (m *PAgentStat) GetLoadedClass() *PLoadedClass {
	if m != nil {
		return m.LoadedClass
	}
	return nil
}

type PAgentStatBatch struct {
	AgentStat            []*PAgentStat `protobuf:"bytes,1,rep,name=agentStat,proto3" json:"agentStat,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *PAgentStatBatch) Reset()         { *m = PAgentStatBatch{} }
func (m *PAgentStatBatch) String() string { return proto.CompactTextString(m) }
func (*PAgentStatBatch) ProtoMessage()    {}
func (*PAgentStatBatch) Descriptor() ([]byte, []int) {
	return fileDescriptor_708c871858e42d40, []int{7}
}

func (m *PAgentStatBatch) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PAgentStatBatch.Unmarshal(m, b)
}
func (m *PAgentStatBatch) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PAgentStatBatch.Marshal(b, m, deterministic)
}
func (m *PAgentStatBatch) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PAgentStatBatch.Merge(m, src)
}
func (m *PAgentStatBatch) XXX_Size() int {
	return xxx_messageInfo_PAgentStatBatch.Size(m)
}
func (m *PAgentStatBatch) XXX_DiscardUnknown() {
	xxx_messageInfo_PAgentStatBatch.DiscardUnknown(m)
}

var xxx_messageInfo_PAgentStatBatch proto.InternalMessageInfo

func (m *PAgentStatBatch) GetAgentStat() []*PAgentStat {
	if m != nil {
		return m.AgentStat
	}
	return nil
}

type PDataSource struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ServiceTypeCode      int32    `protobuf:"varint,2,opt,name=serviceTypeCode,proto3" json:"serviceTypeCode,omitempty"`
	DatabaseName         string   `protobuf:"bytes,3,opt,name=databaseName,proto3" json:"databaseName,omitempty"`
	Url                  string   `protobuf:"bytes,4,opt,name=url,proto3" json:"url,omitempty"`
	ActiveConnectionSize int32    `protobuf:"varint,5,opt,name=activeConnectionSize,proto3" json:"activeConnectionSize,omitempty"`
	MaxConnectionSize    int32    `protobuf:"varint,6,opt,name=maxConnectionSize,proto3" json:"maxConnectionSize,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PDataSource) Reset()         { *m = PDataSource{} }
func (m *PDataSource) String() string { return proto.CompactTextString(m) }
func (*PDataSource) ProtoMessage()    {}
func (*PDataSource) Descriptor() ([]byte, []int) {
	return fileDescriptor_708c871858e42d40, []int{8}
}

func (m *PDataSource) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PDataSource.Unmarshal(m, b)
}
func (m *PDataSource) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PDataSource.Marshal(b, m, deterministic)
}
func (m *PDataSource) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PDataSource.Merge(m, src)
}
func (m *PDataSource) XXX_Size() int {
	return xxx_messageInfo_PDataSource.Size(m)
}
func (m *PDataSource) XXX_DiscardUnknown() {
	xxx_messageInfo_PDataSource.DiscardUnknown(m)
}

var xxx_messageInfo_PDataSource proto.InternalMessageInfo

func (m *PDataSource) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *PDataSource) GetServiceTypeCode() int32 {
	if m != nil {
		return m.ServiceTypeCode
	}
	return 0
}

func (m *PDataSource) GetDatabaseName() string {
	if m != nil {
		return m.DatabaseName
	}
	return ""
}

func (m *PDataSource) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *PDataSource) GetActiveConnectionSize() int32 {
	if m != nil {
		return m.ActiveConnectionSize
	}
	return 0
}

func (m *PDataSource) GetMaxConnectionSize() int32 {
	if m != nil {
		return m.MaxConnectionSize
	}
	return 0
}

type PDataSourceList struct {
	DataSource           []*PDataSource `protobuf:"bytes,1,rep,name=dataSource,proto3" json:"dataSource,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *PDataSourceList) Reset()         { *m = PDataSourceList{} }
func (m *PDataSourceList) String() string { return proto.CompactTextString(m) }
func (*PDataSourceList) ProtoMessage()    {}
func (*PDataSourceList) Descriptor() ([]byte, []int) {
	return fileDescriptor_708c871858e42d40, []int{9}
}

func (m *PDataSourceList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PDataSourceList.Unmarshal(m, b)
}
func (m *PDataSourceList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PDataSourceList.Marshal(b, m, deterministic)
}
func (m *PDataSourceList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PDataSourceList.Merge(m, src)
}
func (m *PDataSourceList) XXX_Size() int {
	return xxx_messageInfo_PDataSourceList.Size(m)
}
func (m *PDataSourceList) XXX_DiscardUnknown() {
	xxx_messageInfo_PDataSourceList.DiscardUnknown(m)
}

var xxx_messageInfo_PDataSourceList proto.InternalMessageInfo

func (m *PDataSourceList) GetDataSource() []*PDataSource {
	if m != nil {
		return m.DataSource
	}
	return nil
}

type PFileDescriptor struct {
	OpenFileDescriptorCount int64    `protobuf:"varint,1,opt,name=openFileDescriptorCount,proto3" json:"openFileDescriptorCount,omitempty"`
	XXX_NoUnkeyedLiteral    struct{} `json:"-"`
	XXX_unrecognized        []byte   `json:"-"`
	XXX_sizecache           int32    `json:"-"`
}

func (m *PFileDescriptor) Reset()         { *m = PFileDescriptor{} }
func (m *PFileDescriptor) String() string { return proto.CompactTextString(m) }
func (*PFileDescriptor) ProtoMessage()    {}
func (*PFileDescriptor) Descriptor() ([]byte, []int) {
	return fileDescriptor_708c871858e42d40, []int{10}
}

func (m *PFileDescriptor) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PFileDescriptor.Unmarshal(m, b)
}
func (m *PFileDescriptor) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PFileDescriptor.Marshal(b, m, deterministic)
}
func (m *PFileDescriptor) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PFileDescriptor.Merge(m, src)
}
func (m *PFileDescriptor) XXX_Size() int {
	return xxx_messageInfo_PFileDescriptor.Size(m)
}
func (m *PFileDescriptor) XXX_DiscardUnknown() {
	xxx_messageInfo_PFileDescriptor.DiscardUnknown(m)
}

var xxx_messageInfo_PFileDescriptor proto.InternalMessageInfo

func (m *PFileDescriptor) GetOpenFileDescriptorCount() int64 {
	if m != nil {
		return m.OpenFileDescriptorCount
	}
	return 0
}

type PJvmGc struct {
	Type                 PJvmGcType      `protobuf:"varint,1,opt,name=type,proto3,enum=v1.PJvmGcType" json:"type,omitempty"`
	JvmMemoryHeapUsed    int64           `protobuf:"varint,2,opt,name=jvmMemoryHeapUsed,proto3" json:"jvmMemoryHeapUsed,omitempty"`
	JvmMemoryHeapMax     int64           `protobuf:"varint,3,opt,name=jvmMemoryHeapMax,proto3" json:"jvmMemoryHeapMax,omitempty"`
	JvmMemoryNonHeapUsed int64           `protobuf:"varint,4,opt,name=jvmMemoryNonHeapUsed,proto3" json:"jvmMemoryNonHeapUsed,omitempty"`
	JvmMemoryNonHeapMax  int64           `protobuf:"varint,5,opt,name=jvmMemoryNonHeapMax,proto3" json:"jvmMemoryNonHeapMax,omitempty"`
	JvmGcOldCount        int64           `protobuf:"varint,6,opt,name=jvmGcOldCount,proto3" json:"jvmGcOldCount,omitempty"`
	JvmGcOldTime         int64           `protobuf:"varint,7,opt,name=jvmGcOldTime,proto3" json:"jvmGcOldTime,omitempty"`
	JvmGcDetailed        *PJvmGcDetailed `protobuf:"bytes,8,opt,name=jvmGcDetailed,proto3" json:"jvmGcDetailed,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *PJvmGc) Reset()         { *m = PJvmGc{} }
func (m *PJvmGc) String() string { return proto.CompactTextString(m) }
func (*PJvmGc) ProtoMessage()    {}
func (*PJvmGc) Descriptor() ([]byte, []int) {
	return fileDescriptor_708c871858e42d40, []int{11}
}

func (m *PJvmGc) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PJvmGc.Unmarshal(m, b)
}
func (m *PJvmGc) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PJvmGc.Marshal(b, m, deterministic)
}
func (m *PJvmGc) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PJvmGc.Merge(m, src)
}
func (m *PJvmGc) XXX_Size() int {
	return xxx_messageInfo_PJvmGc.Size(m)
}
func (m *PJvmGc) XXX_DiscardUnknown() {
	xxx_messageInfo_PJvmGc.DiscardUnknown(m)
}

var xxx_messageInfo_PJvmGc proto.InternalMessageInfo

func (m *PJvmGc) GetType() PJvmGcType {
	if m != nil {
		return m.Type
	}
	return PJvmGcType_JVM_GC_TYPE_UNKNOWN
}

func (m *PJvmGc) GetJvmMemoryHeapUsed() int64 {
	if m != nil {
		return m.JvmMemoryHeapUsed
	}
	return 0
}

func (m *PJvmGc) GetJvmMemoryHeapMax() int64 {
	if m != nil {
		return m.JvmMemoryHeapMax
	}
	return 0
}

func (m *PJvmGc) GetJvmMemoryNonHeapUsed() int64 {
	if m != nil {
		return m.JvmMemoryNonHeapUsed
	}
	return 0
}

func (m *PJvmGc) GetJvmMemoryNonHeapMax() int64 {
	if m != nil {
		return m.JvmMemoryNonHeapMax
	}
	return 0
}

func (m *PJvmGc) GetJvmGcOldCount() int64 {
	if m != nil {
		return m.JvmGcOldCount
	}
	return 0
}

func (m *PJvmGc) GetJvmGcOldTime() int64 {
	if m != nil {
		return m.JvmGcOldTime
	}
	return 0
}

func (m *PJvmGc) GetJvmGcDetailed() *PJvmGcDetailed {
	if m != nil {
		return m.JvmGcDetailed
	}
	return nil
}

type PJvmGcDetailed struct {
	JvmGcNewCount            int64    `protobuf:"varint,1,opt,name=jvmGcNewCount,proto3" json:"jvmGcNewCount,omitempty"`
	JvmGcNewTime             int64    `protobuf:"varint,2,opt,name=jvmGcNewTime,proto3" json:"jvmGcNewTime,omitempty"`
	JvmPoolCodeCacheUsed     float64  `protobuf:"fixed64,3,opt,name=jvmPoolCodeCacheUsed,proto3" json:"jvmPoolCodeCacheUsed,omitempty"`
	JvmPoolNewGenUsed        float64  `protobuf:"fixed64,4,opt,name=jvmPoolNewGenUsed,proto3" json:"jvmPoolNewGenUsed,omitempty"`
	JvmPoolOldGenUsed        float64  `protobuf:"fixed64,5,opt,name=jvmPoolOldGenUsed,proto3" json:"jvmPoolOldGenUsed,omitempty"`
	JvmPoolSurvivorSpaceUsed float64  `protobuf:"fixed64,6,opt,name=jvmPoolSurvivorSpaceUsed,proto3" json:"jvmPoolSurvivorSpaceUsed,omitempty"`
	JvmPoolPermGenUsed       float64  `protobuf:"fixed64,7,opt,name=jvmPoolPermGenUsed,proto3" json:"jvmPoolPermGenUsed,omitempty"`
	JvmPoolMetaspaceUsed     float64  `protobuf:"fixed64,8,opt,name=jvmPoolMetaspaceUsed,proto3" json:"jvmPoolMetaspaceUsed,omitempty"`
	XXX_NoUnkeyedLiteral     struct{} `json:"-"`
	XXX_unrecognized         []byte   `json:"-"`
	XXX_sizecache            int32    `json:"-"`
}

func (m *PJvmGcDetailed) Reset()         { *m = PJvmGcDetailed{} }
func (m *PJvmGcDetailed) String() string { return proto.CompactTextString(m) }
func (*PJvmGcDetailed) ProtoMessage()    {}
func (*PJvmGcDetailed) Descriptor() ([]byte, []int) {
	return fileDescriptor_708c871858e42d40, []int{12}
}

func (m *PJvmGcDetailed) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PJvmGcDetailed.Unmarshal(m, b)
}
func (m *PJvmGcDetailed) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PJvmGcDetailed.Marshal(b, m, deterministic)
}
func (m *PJvmGcDetailed) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PJvmGcDetailed.Merge(m, src)
}
func (m *PJvmGcDetailed) XXX_Size() int {
	return xxx_messageInfo_PJvmGcDetailed.Size(m)
}
func (m *PJvmGcDetailed) XXX_DiscardUnknown() {
	xxx_messageInfo_PJvmGcDetailed.DiscardUnknown(m)
}

var xxx_messageInfo_PJvmGcDetailed proto.InternalMessageInfo

func (m *PJvmGcDetailed) GetJvmGcNewCount() int64 {
	if m != nil {
		return m.JvmGcNewCount
	}
	return 0
}

func (m *PJvmGcDetailed) GetJvmGcNewTime() int64 {
	if m != nil {
		return m.JvmGcNewTime
	}
	return 0
}

func (m *PJvmGcDetailed) GetJvmPoolCodeCacheUsed() float64 {
	if m != nil {
		return m.JvmPoolCodeCacheUsed
	}
	return 0
}

func (m *PJvmGcDetailed) GetJvmPoolNewGenUsed() float64 {
	if m != nil {
		return m.JvmPoolNewGenUsed
	}
	return 0
}

func (m *PJvmGcDetailed) GetJvmPoolOldGenUsed() float64 {
	if m != nil {
		return m.JvmPoolOldGenUsed
	}
	return 0
}

func (m *PJvmGcDetailed) GetJvmPoolSurvivorSpaceUsed() float64 {
	if m != nil {
		return m.JvmPoolSurvivorSpaceUsed
	}
	return 0
}

func (m *PJvmGcDetailed) GetJvmPoolPermGenUsed() float64 {
	if m != nil {
		return m.JvmPoolPermGenUsed
	}
	return 0
}

func (m *PJvmGcDetailed) GetJvmPoolMetaspaceUsed() float64 {
	if m != nil {
		return m.JvmPoolMetaspaceUsed
	}
	return 0
}

type PCpuLoad struct {
	JvmCpuLoad           float64  `protobuf:"fixed64,1,opt,name=jvmCpuLoad,proto3" json:"jvmCpuLoad,omitempty"`
	SystemCpuLoad        float64  `protobuf:"fixed64,2,opt,name=systemCpuLoad,proto3" json:"systemCpuLoad,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PCpuLoad) Reset()         { *m = PCpuLoad{} }
func (m *PCpuLoad) String() string { return proto.CompactTextString(m) }
func (*PCpuLoad) ProtoMessage()    {}
func (*PCpuLoad) Descriptor() ([]byte, []int) {
	return fileDescriptor_708c871858e42d40, []int{13}
}

func (m *PCpuLoad) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PCpuLoad.Unmarshal(m, b)
}
func (m *PCpuLoad) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PCpuLoad.Marshal(b, m, deterministic)
}
func (m *PCpuLoad) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PCpuLoad.Merge(m, src)
}
func (m *PCpuLoad) XXX_Size() int {
	return xxx_messageInfo_PCpuLoad.Size(m)
}
func (m *PCpuLoad) XXX_DiscardUnknown() {
	xxx_messageInfo_PCpuLoad.DiscardUnknown(m)
}

var xxx_messageInfo_PCpuLoad proto.InternalMessageInfo

func (m *PCpuLoad) GetJvmCpuLoad() float64 {
	if m != nil {
		return m.JvmCpuLoad
	}
	return 0
}

func (m *PCpuLoad) GetSystemCpuLoad() float64 {
	if m != nil {
		return m.SystemCpuLoad
	}
	return 0
}

type PTransaction struct {
	SampledNewCount            int64    `protobuf:"varint,2,opt,name=sampledNewCount,proto3" json:"sampledNewCount,omitempty"`
	SampledContinuationCount   int64    `protobuf:"varint,3,opt,name=sampledContinuationCount,proto3" json:"sampledContinuationCount,omitempty"`
	UnsampledNewCount          int64    `protobuf:"varint,4,opt,name=unsampledNewCount,proto3" json:"unsampledNewCount,omitempty"`
	UnsampledContinuationCount int64    `protobuf:"varint,5,opt,name=unsampledContinuationCount,proto3" json:"unsampledContinuationCount,omitempty"`
	SkippedNewCount            int64    `protobuf:"varint,6,opt,name=skippedNewCount,proto3" json:"skippedNewCount,omitempty"`
	SkippedContinuationCount   int64    `protobuf:"varint,7,opt,name=skippedContinuationCount,proto3" json:"skippedContinuationCount,omitempty"`
	XXX_NoUnkeyedLiteral       struct{} `json:"-"`
	XXX_unrecognized           []byte   `json:"-"`
	XXX_sizecache              int32    `json:"-"`
}

func (m *PTransaction) Reset()         { *m = PTransaction{} }
func (m *PTransaction) String() string { return proto.CompactTextString(m) }
func (*PTransaction) ProtoMessage()    {}
func (*PTransaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_708c871858e42d40, []int{14}
}

func (m *PTransaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PTransaction.Unmarshal(m, b)
}
func (m *PTransaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PTransaction.Marshal(b, m, deterministic)
}
func (m *PTransaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PTransaction.Merge(m, src)
}
func (m *PTransaction) XXX_Size() int {
	return xxx_messageInfo_PTransaction.Size(m)
}
func (m *PTransaction) XXX_DiscardUnknown() {
	xxx_messageInfo_PTransaction.DiscardUnknown(m)
}

var xxx_messageInfo_PTransaction proto.InternalMessageInfo

func (m *PTransaction) GetSampledNewCount() int64 {
	if m != nil {
		return m.SampledNewCount
	}
	return 0
}

func (m *PTransaction) GetSampledContinuationCount() int64 {
	if m != nil {
		return m.SampledContinuationCount
	}
	return 0
}

func (m *PTransaction) GetUnsampledNewCount() int64 {
	if m != nil {
		return m.UnsampledNewCount
	}
	return 0
}

func (m *PTransaction) GetUnsampledContinuationCount() int64 {
	if m != nil {
		return m.UnsampledContinuationCount
	}
	return 0
}

func (m *PTransaction) GetSkippedNewCount() int64 {
	if m != nil {
		return m.SkippedNewCount
	}
	return 0
}

func (m *PTransaction) GetSkippedContinuationCount() int64 {
	if m != nil {
		return m.SkippedContinuationCount
	}
	return 0
}

type PActiveTraceHistogram struct {
	Version              int32    `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	HistogramSchemaType  int32    `protobuf:"varint,2,opt,name=histogramSchemaType,proto3" json:"histogramSchemaType,omitempty"`
	ActiveTraceCount     []int32  `protobuf:"varint,3,rep,packed,name=activeTraceCount,proto3" json:"activeTraceCount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PActiveTraceHistogram) Reset()         { *m = PActiveTraceHistogram{} }
func (m *PActiveTraceHistogram) String() string { return proto.CompactTextString(m) }
func (*PActiveTraceHistogram) ProtoMessage()    {}
func (*PActiveTraceHistogram) Descriptor() ([]byte, []int) {
	return fileDescriptor_708c871858e42d40, []int{15}
}

func (m *PActiveTraceHistogram) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PActiveTraceHistogram.Unmarshal(m, b)
}
func (m *PActiveTraceHistogram) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PActiveTraceHistogram.Marshal(b, m, deterministic)
}
func (m *PActiveTraceHistogram) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PActiveTraceHistogram.Merge(m, src)
}
func (m *PActiveTraceHistogram) XXX_Size() int {
	return xxx_messageInfo_PActiveTraceHistogram.Size(m)
}
func (m *PActiveTraceHistogram) XXX_DiscardUnknown() {
	xxx_messageInfo_PActiveTraceHistogram.DiscardUnknown(m)
}

var xxx_messageInfo_PActiveTraceHistogram proto.InternalMessageInfo

func (m *PActiveTraceHistogram) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *PActiveTraceHistogram) GetHistogramSchemaType() int32 {
	if m != nil {
		return m.HistogramSchemaType
	}
	return 0
}

func (m *PActiveTraceHistogram) GetActiveTraceCount() []int32 {
	if m != nil {
		return m.ActiveTraceCount
	}
	return nil
}

type PActiveTrace struct {
	Histogram            *PActiveTraceHistogram `protobuf:"bytes,1,opt,name=histogram,proto3" json:"histogram,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *PActiveTrace) Reset()         { *m = PActiveTrace{} }
func (m *PActiveTrace) String() string { return proto.CompactTextString(m) }
func (*PActiveTrace) ProtoMessage()    {}
func (*PActiveTrace) Descriptor() ([]byte, []int) {
	return fileDescriptor_708c871858e42d40, []int{16}
}

func (m *PActiveTrace) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PActiveTrace.Unmarshal(m, b)
}
func (m *PActiveTrace) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PActiveTrace.Marshal(b, m, deterministic)
}
func (m *PActiveTrace) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PActiveTrace.Merge(m, src)
}
func (m *PActiveTrace) XXX_Size() int {
	return xxx_messageInfo_PActiveTrace.Size(m)
}
func (m *PActiveTrace) XXX_DiscardUnknown() {
	xxx_messageInfo_PActiveTrace.DiscardUnknown(m)
}

var xxx_messageInfo_PActiveTrace proto.InternalMessageInfo

func (m *PActiveTrace) GetHistogram() *PActiveTraceHistogram {
	if m != nil {
		return m.Histogram
	}
	return nil
}

type PResponseTime struct {
	Avg                  int64    `protobuf:"varint,1,opt,name=avg,proto3" json:"avg,omitempty"`
	Max                  int64    `protobuf:"varint,2,opt,name=max,proto3" json:"max,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PResponseTime) Reset()         { *m = PResponseTime{} }
func (m *PResponseTime) String() string { return proto.CompactTextString(m) }
func (*PResponseTime) ProtoMessage()    {}
func (*PResponseTime) Descriptor() ([]byte, []int) {
	return fileDescriptor_708c871858e42d40, []int{17}
}

func (m *PResponseTime) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PResponseTime.Unmarshal(m, b)
}
func (m *PResponseTime) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PResponseTime.Marshal(b, m, deterministic)
}
func (m *PResponseTime) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PResponseTime.Merge(m, src)
}
func (m *PResponseTime) XXX_Size() int {
	return xxx_messageInfo_PResponseTime.Size(m)
}
func (m *PResponseTime) XXX_DiscardUnknown() {
	xxx_messageInfo_PResponseTime.DiscardUnknown(m)
}

var xxx_messageInfo_PResponseTime proto.InternalMessageInfo

func (m *PResponseTime) GetAvg() int64 {
	if m != nil {
		return m.Avg
	}
	return 0
}

func (m *PResponseTime) GetMax() int64 {
	if m != nil {
		return m.Max
	}
	return 0
}

type PDeadlock struct {
	Count                int32          `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	ThreadDump           []*PThreadDump `protobuf:"bytes,2,rep,name=threadDump,proto3" json:"threadDump,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *PDeadlock) Reset()         { *m = PDeadlock{} }
func (m *PDeadlock) String() string { return proto.CompactTextString(m) }
func (*PDeadlock) ProtoMessage()    {}
func (*PDeadlock) Descriptor() ([]byte, []int) {
	return fileDescriptor_708c871858e42d40, []int{18}
}

func (m *PDeadlock) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PDeadlock.Unmarshal(m, b)
}
func (m *PDeadlock) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PDeadlock.Marshal(b, m, deterministic)
}
func (m *PDeadlock) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PDeadlock.Merge(m, src)
}
func (m *PDeadlock) XXX_Size() int {
	return xxx_messageInfo_PDeadlock.Size(m)
}
func (m *PDeadlock) XXX_DiscardUnknown() {
	xxx_messageInfo_PDeadlock.DiscardUnknown(m)
}

var xxx_messageInfo_PDeadlock proto.InternalMessageInfo

func (m *PDeadlock) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *PDeadlock) GetThreadDump() []*PThreadDump {
	if m != nil {
		return m.ThreadDump
	}
	return nil
}

type PDirectBuffer struct {
	DirectCount          int64    `protobuf:"varint,1,opt,name=directCount,proto3" json:"directCount,omitempty"`
	DirectMemoryUsed     int64    `protobuf:"varint,2,opt,name=directMemoryUsed,proto3" json:"directMemoryUsed,omitempty"`
	MappedCount          int64    `protobuf:"varint,3,opt,name=mappedCount,proto3" json:"mappedCount,omitempty"`
	MappedMemoryUsed     int64    `protobuf:"varint,4,opt,name=mappedMemoryUsed,proto3" json:"mappedMemoryUsed,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PDirectBuffer) Reset()         { *m = PDirectBuffer{} }
func (m *PDirectBuffer) String() string { return proto.CompactTextString(m) }
func (*PDirectBuffer) ProtoMessage()    {}
func (*PDirectBuffer) Descriptor() ([]byte, []int) {
	return fileDescriptor_708c871858e42d40, []int{19}
}

func (m *PDirectBuffer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PDirectBuffer.Unmarshal(m, b)
}
func (m *PDirectBuffer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PDirectBuffer.Marshal(b, m, deterministic)
}
func (m *PDirectBuffer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PDirectBuffer.Merge(m, src)
}
func (m *PDirectBuffer) XXX_Size() int {
	return xxx_messageInfo_PDirectBuffer.Size(m)
}
func (m *PDirectBuffer) XXX_DiscardUnknown() {
	xxx_messageInfo_PDirectBuffer.DiscardUnknown(m)
}

var xxx_messageInfo_PDirectBuffer proto.InternalMessageInfo

func (m *PDirectBuffer) GetDirectCount() int64 {
	if m != nil {
		return m.DirectCount
	}
	return 0
}

func (m *PDirectBuffer) GetDirectMemoryUsed() int64 {
	if m != nil {
		return m.DirectMemoryUsed
	}
	return 0
}

func (m *PDirectBuffer) GetMappedCount() int64 {
	if m != nil {
		return m.MappedCount
	}
	return 0
}

func (m *PDirectBuffer) GetMappedMemoryUsed() int64 {
	if m != nil {
		return m.MappedMemoryUsed
	}
	return 0
}

type PTotalThread struct {
	TotalThreadCount     int64    `protobuf:"varint,1,opt,name=totalThreadCount,proto3" json:"totalThreadCount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PTotalThread) Reset()         { *m = PTotalThread{} }
func (m *PTotalThread) String() string { return proto.CompactTextString(m) }
func (*PTotalThread) ProtoMessage()    {}
func (*PTotalThread) Descriptor() ([]byte, []int) {
	return fileDescriptor_708c871858e42d40, []int{20}
}

func (m *PTotalThread) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PTotalThread.Unmarshal(m, b)
}
func (m *PTotalThread) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PTotalThread.Marshal(b, m, deterministic)
}
func (m *PTotalThread) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PTotalThread.Merge(m, src)
}
func (m *PTotalThread) XXX_Size() int {
	return xxx_messageInfo_PTotalThread.Size(m)
}
func (m *PTotalThread) XXX_DiscardUnknown() {
	xxx_messageInfo_PTotalThread.DiscardUnknown(m)
}

var xxx_messageInfo_PTotalThread proto.InternalMessageInfo

func (m *PTotalThread) GetTotalThreadCount() int64 {
	if m != nil {
		return m.TotalThreadCount
	}
	return 0
}

type PLoadedClass struct {
	LoadedClassCount     int64    `protobuf:"varint,1,opt,name=loadedClassCount,proto3" json:"loadedClassCount,omitempty"`
	UnloadedClassCount   int64    `protobuf:"varint,2,opt,name=unloadedClassCount,proto3" json:"unloadedClassCount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PLoadedClass) Reset()         { *m = PLoadedClass{} }
func (m *PLoadedClass) String() string { return proto.CompactTextString(m) }
func (*PLoadedClass) ProtoMessage()    {}
func (*PLoadedClass) Descriptor() ([]byte, []int) {
	return fileDescriptor_708c871858e42d40, []int{21}
}

func (m *PLoadedClass) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PLoadedClass.Unmarshal(m, b)
}
func (m *PLoadedClass) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PLoadedClass.Marshal(b, m, deterministic)
}
func (m *PLoadedClass) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PLoadedClass.Merge(m, src)
}
func (m *PLoadedClass) XXX_Size() int {
	return xxx_messageInfo_PLoadedClass.Size(m)
}
func (m *PLoadedClass) XXX_DiscardUnknown() {
	xxx_messageInfo_PLoadedClass.DiscardUnknown(m)
}

var xxx_messageInfo_PLoadedClass proto.InternalMessageInfo

func (m *PLoadedClass) GetLoadedClassCount() int64 {
	if m != nil {
		return m.LoadedClassCount
	}
	return 0
}

func (m *PLoadedClass) GetUnloadedClassCount() int64 {
	if m != nil {
		return m.UnloadedClassCount
	}
	return 0
}

type PAgentUriStat struct {
	Timestamp            int64           `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	BucketVersion        int32           `protobuf:"varint,2,opt,name=bucketVersion,proto3" json:"bucketVersion,omitempty"`
	EachUriStat          []*PEachUriStat `protobuf:"bytes,3,rep,name=eachUriStat,proto3" json:"eachUriStat,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *PAgentUriStat) Reset()         { *m = PAgentUriStat{} }
func (m *PAgentUriStat) String() string { return proto.CompactTextString(m) }
func (*PAgentUriStat) ProtoMessage()    {}
func (*PAgentUriStat) Descriptor() ([]byte, []int) {
	return fileDescriptor_708c871858e42d40, []int{22}
}

func (m *PAgentUriStat) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PAgentUriStat.Unmarshal(m, b)
}
func (m *PAgentUriStat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PAgentUriStat.Marshal(b, m, deterministic)
}
func (m *PAgentUriStat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PAgentUriStat.Merge(m, src)
}
func (m *PAgentUriStat) XXX_Size() int {
	return xxx_messageInfo_PAgentUriStat.Size(m)
}
func (m *PAgentUriStat) XXX_DiscardUnknown() {
	xxx_messageInfo_PAgentUriStat.DiscardUnknown(m)
}

var xxx_messageInfo_PAgentUriStat proto.InternalMessageInfo

func (m *PAgentUriStat) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *PAgentUriStat) GetBucketVersion() int32 {
	if m != nil {
		return m.BucketVersion
	}
	return 0
}

func (m *PAgentUriStat) GetEachUriStat() []*PEachUriStat {
	if m != nil {
		return m.EachUriStat
	}
	return nil
}

type PEachUriStat struct {
	Uri                  string         `protobuf:"bytes,1,opt,name=uri,proto3" json:"uri,omitempty"`
	TotalHistogram       *PUriHistogram `protobuf:"bytes,2,opt,name=totalHistogram,proto3" json:"totalHistogram,omitempty"`
	FailedHistogram      *PUriHistogram `protobuf:"bytes,3,opt,name=failedHistogram,proto3" json:"failedHistogram,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *PEachUriStat) Reset()         { *m = PEachUriStat{} }
func (m *PEachUriStat) String() string { return proto.CompactTextString(m) }
func (*PEachUriStat) ProtoMessage()    {}
func (*PEachUriStat) Descriptor() ([]byte, []int) {
	return fileDescriptor_708c871858e42d40, []int{23}
}

func (m *PEachUriStat) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PEachUriStat.Unmarshal(m, b)
}
func (m *PEachUriStat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PEachUriStat.Marshal(b, m, deterministic)
}
func (m *PEachUriStat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PEachUriStat.Merge(m, src)
}
func (m *PEachUriStat) XXX_Size() int {
	return xxx_messageInfo_PEachUriStat.Size(m)
}
func (m *PEachUriStat) XXX_DiscardUnknown() {
	xxx_messageInfo_PEachUriStat.DiscardUnknown(m)
}

var xxx_messageInfo_PEachUriStat proto.InternalMessageInfo

func (m *PEachUriStat) GetUri() string {
	if m != nil {
		return m.Uri
	}
	return ""
}

func (m *PEachUriStat) GetTotalHistogram() *PUriHistogram {
	if m != nil {
		return m.TotalHistogram
	}
	return nil
}

func (m *PEachUriStat) GetFailedHistogram() *PUriHistogram {
	if m != nil {
		return m.FailedHistogram
	}
	return nil
}

type PUriHistogram struct {
	Count                int32    `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	Avg                  float64  `protobuf:"fixed64,2,opt,name=avg,proto3" json:"avg,omitempty"`
	Max                  int64    `protobuf:"varint,3,opt,name=max,proto3" json:"max,omitempty"`
	Histogram            []int32  `protobuf:"varint,4,rep,packed,name=histogram,proto3" json:"histogram,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PUriHistogram) Reset()         { *m = PUriHistogram{} }
func (m *PUriHistogram) String() string { return proto.CompactTextString(m) }
func (*PUriHistogram) ProtoMessage()    {}
func (*PUriHistogram) Descriptor() ([]byte, []int) {
	return fileDescriptor_708c871858e42d40, []int{24}
}

func (m *PUriHistogram) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PUriHistogram.Unmarshal(m, b)
}
func (m *PUriHistogram) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PUriHistogram.Marshal(b, m, deterministic)
}
func (m *PUriHistogram) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PUriHistogram.Merge(m, src)
}
func (m *PUriHistogram) XXX_Size() int {
	return xxx_messageInfo_PUriHistogram.Size(m)
}
func (m *PUriHistogram) XXX_DiscardUnknown() {
	xxx_messageInfo_PUriHistogram.DiscardUnknown(m)
}

var xxx_messageInfo_PUriHistogram proto.InternalMessageInfo

func (m *PUriHistogram) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *PUriHistogram) GetAvg() float64 {
	if m != nil {
		return m.Avg
	}
	return 0
}

func (m *PUriHistogram) GetMax() int64 {
	if m != nil {
		return m.Max
	}
	return 0
}

func (m *PUriHistogram) GetHistogram() []int32 {
	if m != nil {
		return m.Histogram
	}
	return nil
}

func init() {
	proto.RegisterEnum("v1.PJvmGcType", PJvmGcType_name, PJvmGcType_value)
	proto.RegisterType((*PPing)(nil), "v1.PPing")
	proto.RegisterType((*PStatMessage)(nil), "v1.PStatMessage")
	proto.RegisterType((*PAgentInfo)(nil), "v1.PAgentInfo")
	proto.RegisterType((*PServerMetaData)(nil), "v1.PServerMetaData")
	proto.RegisterType((*PServiceInfo)(nil), "v1.PServiceInfo")
	proto.RegisterType((*PJvmInfo)(nil), "v1.PJvmInfo")
	proto.RegisterType((*PAgentStat)(nil), "v1.PAgentStat")
	proto.RegisterType((*PAgentStatBatch)(nil), "v1.PAgentStatBatch")
	proto.RegisterType((*PDataSource)(nil), "v1.PDataSource")
	proto.RegisterType((*PDataSourceList)(nil), "v1.PDataSourceList")
	proto.RegisterType((*PFileDescriptor)(nil), "v1.PFileDescriptor")
	proto.RegisterType((*PJvmGc)(nil), "v1.PJvmGc")
	proto.RegisterType((*PJvmGcDetailed)(nil), "v1.PJvmGcDetailed")
	proto.RegisterType((*PCpuLoad)(nil), "v1.PCpuLoad")
	proto.RegisterType((*PTransaction)(nil), "v1.PTransaction")
	proto.RegisterType((*PActiveTraceHistogram)(nil), "v1.PActiveTraceHistogram")
	proto.RegisterType((*PActiveTrace)(nil), "v1.PActiveTrace")
	proto.RegisterType((*PResponseTime)(nil), "v1.PResponseTime")
	proto.RegisterType((*PDeadlock)(nil), "v1.PDeadlock")
	proto.RegisterType((*PDirectBuffer)(nil), "v1.PDirectBuffer")
	proto.RegisterType((*PTotalThread)(nil), "v1.PTotalThread")
	proto.RegisterType((*PLoadedClass)(nil), "v1.PLoadedClass")
	proto.RegisterType((*PAgentUriStat)(nil), "v1.PAgentUriStat")
	proto.RegisterType((*PEachUriStat)(nil), "v1.PEachUriStat")
	proto.RegisterType((*PUriHistogram)(nil), "v1.PUriHistogram")
}

func init() { proto.RegisterFile("v1/Stat.proto", fileDescriptor_708c871858e42d40) }

var fileDescriptor_708c871858e42d40 = []byte{
	// 1684 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x58, 0xdd, 0x6e, 0xdb, 0xc8,
	0x15, 0x0e, 0x45, 0x4b, 0xb2, 0x8e, 0xf5, 0xb7, 0xe3, 0xb4, 0xcb, 0x06, 0x8b, 0xc2, 0x25, 0x16,
	0x0b, 0x37, 0x58, 0x28, 0x6b, 0x2f, 0x16, 0xbb, 0xdd, 0x45, 0x5b, 0xd8, 0x72, 0x6a, 0x27, 0x6b,
	0x2b, 0xc2, 0xc8, 0xd9, 0xa2, 0xbd, 0x09, 0x26, 0xe4, 0x58, 0xa6, 0x23, 0xfe, 0x80, 0x1c, 0x31,
	0x49, 0x7b, 0xd3, 0xbb, 0xa2, 0xbd, 0xe9, 0x65, 0xfb, 0x0e, 0x7d, 0x88, 0xde, 0xf6, 0x2d, 0xfa,
	0x0a, 0x7d, 0x84, 0xe2, 0xcc, 0x0c, 0xc9, 0x21, 0x25, 0xa7, 0x77, 0x9a, 0xef, 0xfb, 0xce, 0xfc,
	0x9d, 0x9f, 0x39, 0x14, 0x0c, 0xf2, 0xa3, 0x27, 0x0b, 0xc1, 0xc4, 0x24, 0x49, 0x63, 0x11, 0x93,
	0x56, 0x7e, 0xf4, 0x68, 0x3f, 0x3f, 0x7a, 0x72, 0x7d, 0x9b, 0x72, 0xe6, 0x9f, 0xad, 0xc3, 0x44,
	0x11, 0x6e, 0x17, 0xda, 0xf3, 0x79, 0x10, 0x2d, 0xdd, 0x7f, 0x59, 0xd0, 0x9f, 0xa3, 0xc5, 0x15,
	0xcf, 0x32, 0xb6, 0xe4, 0x64, 0x02, 0x3d, 0xb6, 0xe4, 0x91, 0x40, 0xcc, 0xb1, 0x0e, 0xac, 0xc3,
	0xbd, 0xe3, 0xe1, 0x24, 0x3f, 0x9a, 0xcc, 0x4f, 0x0a, 0xf4, 0xe2, 0x01, 0xad, 0x24, 0xe4, 0x97,
	0x30, 0x2c, 0x07, 0xa7, 0x4c, 0x78, 0xb7, 0x4e, 0x4b, 0x1a, 0xed, 0xd7, 0x8d, 0x24, 0x75, 0xf1,
	0x80, 0x36, 0xc4, 0xe4, 0x6b, 0xe8, 0x4b, 0xe4, 0x65, 0x1a, 0xc8, 0x15, 0x6d, 0x69, 0xfc, 0x51,
	0x65, 0xac, 0x89, 0x8b, 0x07, 0xb4, 0x26, 0x3c, 0xed, 0x42, 0xfb, 0x26, 0xe0, 0x2b, 0xdf, 0xfd,
	0x8b, 0x0d, 0xa0, 0xa4, 0xcf, 0xa2, 0x9b, 0x98, 0x3c, 0x82, 0xdd, 0xdb, 0x38, 0x13, 0x11, 0x0b,
	0xb9, 0xdc, 0x7e, 0x8f, 0x96, 0x63, 0x32, 0x84, 0x56, 0x90, 0xc8, 0xfd, 0xf5, 0x68, 0x2b, 0x48,
	0xc8, 0x43, 0x68, 0x27, 0x71, 0x2a, 0x32, 0xb9, 0x6a, 0x8f, 0xaa, 0x01, 0x39, 0x80, 0xbd, 0x8c,
	0xa7, 0x79, 0xe0, 0xf1, 0xeb, 0xf7, 0x09, 0x77, 0x76, 0x0e, 0xac, 0xc3, 0x36, 0x35, 0x21, 0x32,
	0x06, 0x3b, 0x09, 0x7c, 0xa7, 0x2d, 0x19, 0xfc, 0x49, 0x5c, 0x7d, 0x8c, 0x1f, 0x78, 0x9a, 0x05,
	0x71, 0xe4, 0x74, 0xe4, 0x84, 0x35, 0x8c, 0x7c, 0x02, 0xbd, 0x3c, 0x2c, 0x04, 0x5d, 0x29, 0xa8,
	0x00, 0x9c, 0x81, 0x47, 0xfe, 0x75, 0x10, 0xf2, 0x4c, 0xb0, 0x30, 0x71, 0x76, 0x0f, 0xac, 0x43,
	0x9b, 0xd6, 0x30, 0x9c, 0x81, 0x47, 0x3e, 0x1e, 0x7f, 0x9d, 0x39, 0x3d, 0xb9, 0x7a, 0x05, 0x90,
	0xef, 0x60, 0x88, 0x9b, 0xe4, 0xe9, 0x15, 0x17, 0xec, 0x8c, 0x09, 0xe6, 0x80, 0xe1, 0x89, 0x45,
	0x8d, 0xa2, 0x0d, 0x29, 0xf9, 0x0c, 0xba, 0x77, 0x79, 0x88, 0x37, 0xe8, 0xec, 0x49, 0xab, 0xbe,
	0xb4, 0x7a, 0xae, 0x30, 0x5a, 0x90, 0xb8, 0x05, 0x2f, 0x8e, 0x04, 0x0b, 0x22, 0x9e, 0x3a, 0xfd,
	0x03, 0xeb, 0x70, 0x97, 0x56, 0x80, 0xfb, 0x47, 0x18, 0x35, 0x16, 0x22, 0x3f, 0x05, 0x50, 0x4b,
	0xc9, 0xb9, 0x95, 0x47, 0x0c, 0x04, 0x7d, 0x90, 0x87, 0x27, 0xe9, 0xd2, 0x69, 0x1d, 0xd8, 0xe8,
	0x03, 0x39, 0x20, 0xc7, 0xa5, 0x0f, 0xa4, 0x99, 0x7d, 0x60, 0x1f, 0xee, 0x1d, 0x8f, 0xcb, 0x83,
	0x68, 0x9c, 0x9a, 0x22, 0x77, 0x8e, 0x91, 0x5c, 0x8d, 0x0d, 0x3f, 0xce, 0xaa, 0x60, 0x30, 0xa1,
	0x62, 0x6f, 0x81, 0xc7, 0x2f, 0x83, 0xd7, 0x7a, 0x03, 0x06, 0xe2, 0xde, 0xc1, 0x6e, 0x71, 0x03,
	0xc4, 0x81, 0x6e, 0xae, 0x7d, 0x67, 0xc9, 0x9b, 0x2f, 0x86, 0x75, 0xbf, 0xb6, 0x9a, 0x7e, 0xfd,
	0x0c, 0x3a, 0x4b, 0x4f, 0x06, 0x12, 0x06, 0xd9, 0x50, 0x27, 0xd3, 0xf3, 0x3c, 0x3c, 0x97, 0x28,
	0xd5, 0xac, 0xfb, 0xf7, 0x76, 0x11, 0xc6, 0x32, 0xad, 0x3e, 0x81, 0x9e, 0x28, 0x63, 0xc1, 0x92,
	0xb1, 0x50, 0x01, 0xe4, 0x10, 0x46, 0x5e, 0xbc, 0x5a, 0x71, 0x4f, 0x3c, 0x8b, 0x04, 0x4f, 0x73,
	0xb6, 0x92, 0x0b, 0xdb, 0xb4, 0x09, 0x93, 0x47, 0xd0, 0x5a, 0x7a, 0x3a, 0xab, 0xa0, 0x5a, 0x9a,
	0xb6, 0x96, 0x1e, 0xfa, 0xdc, 0x4b, 0xd6, 0x97, 0x31, 0xf3, 0x65, 0x90, 0x17, 0x3e, 0x9f, 0x2a,
	0x8c, 0x16, 0x24, 0x3a, 0x43, 0xa4, 0x2c, 0xca, 0x98, 0x27, 0xf0, 0x88, 0x6d, 0xa9, 0x55, 0xce,
	0xb8, 0xae, 0x70, 0x6a, 0x8a, 0xd0, 0x06, 0x7f, 0xe5, 0xfc, 0x3a, 0x65, 0x1e, 0x97, 0xf9, 0x50,
	0xd8, 0x9c, 0x54, 0x38, 0x35, 0x45, 0x18, 0xc0, 0x3e, 0x13, 0x6c, 0x11, 0xaf, 0x53, 0xbc, 0xff,
	0x4c, 0xc8, 0x2c, 0x29, 0x02, 0xf8, 0xac, 0x46, 0xd1, 0x86, 0x94, 0x7c, 0x05, 0xfd, 0x94, 0x67,
	0x49, 0x1c, 0x65, 0x1c, 0x13, 0x46, 0xe6, 0x4f, 0x51, 0x48, 0xa8, 0x41, 0xd0, 0x9a, 0x8c, 0xfc,
	0x1c, 0x76, 0x7d, 0xce, 0xfc, 0x55, 0xec, 0xbd, 0x91, 0x19, 0xb5, 0x77, 0x3c, 0x50, 0xab, 0x69,
	0x90, 0x96, 0x34, 0x6e, 0xef, 0x26, 0x58, 0xf1, 0x33, 0x9e, 0x79, 0x69, 0x90, 0x88, 0x38, 0xad,
	0xe5, 0xd7, 0x6f, 0x6a, 0x14, 0x6d, 0x48, 0x71, 0x7b, 0x7e, 0x90, 0x72, 0x4f, 0x9c, 0xae, 0x6f,
	0x6e, 0x78, 0xaa, 0x93, 0x4c, 0x6d, 0xef, 0xcc, 0x20, 0x68, 0x4d, 0x86, 0xd5, 0x2c, 0xe4, 0x82,
	0xe1, 0x59, 0x65, 0xb6, 0xf5, 0x68, 0x39, 0x96, 0x6e, 0x89, 0x05, 0x5b, 0xa9, 0xe2, 0xee, 0x0c,
	0x4c, 0xb7, 0x54, 0x38, 0x35, 0x45, 0x68, 0xb3, 0x8a, 0x99, 0xcf, 0xfd, 0xe9, 0x8a, 0x65, 0x99,
	0x33, 0x34, 0x6c, 0x2e, 0x2b, 0x9c, 0x9a, 0x22, 0xf7, 0xd7, 0x30, 0x6a, 0xd4, 0x71, 0xf2, 0x79,
	0xfd, 0x91, 0xb0, 0x37, 0x1f, 0x09, 0xe3, 0x89, 0x70, 0xff, 0x63, 0xc1, 0x9e, 0xe1, 0x3e, 0x59,
	0x86, 0x7d, 0x9d, 0x45, 0xad, 0xc0, 0xc7, 0x68, 0x36, 0xaa, 0xeb, 0x34, 0xf6, 0xb9, 0x8c, 0xe6,
	0x36, 0x6d, 0xc2, 0x58, 0x24, 0xf1, 0xe8, 0xaf, 0x59, 0xa6, 0x72, 0x5a, 0xd5, 0xed, 0x1a, 0x86,
	0xc5, 0x79, 0x9d, 0xae, 0x64, 0x44, 0xf7, 0x28, 0xfe, 0x24, 0xc7, 0xf0, 0x50, 0x85, 0xd9, 0x34,
	0x8e, 0x22, 0x2e, 0xe3, 0x73, 0x11, 0xfc, 0x81, 0xeb, 0xfa, 0xbd, 0x95, 0x23, 0x9f, 0xc3, 0x47,
	0x21, 0x7b, 0xd7, 0x30, 0xe8, 0x48, 0x83, 0x4d, 0xc2, 0x3d, 0x85, 0x51, 0x23, 0x3e, 0xc9, 0x13,
	0x80, 0x2a, 0x42, 0xf5, 0x1d, 0x8d, 0x1a, 0x81, 0x4c, 0x0d, 0x89, 0xfb, 0x3d, 0x8c, 0x1a, 0x41,
	0x44, 0xbe, 0x81, 0x8f, 0xe3, 0x84, 0x47, 0x75, 0x74, 0x1a, 0xaf, 0x23, 0xa1, 0x4b, 0xc2, 0x7d,
	0xb4, 0xfb, 0xdf, 0x16, 0x74, 0x54, 0xa6, 0x13, 0x17, 0x76, 0x04, 0x96, 0x1f, 0x6b, 0x6b, 0xf9,
	0x91, 0x1c, 0x9e, 0xf6, 0x2e, 0x0f, 0xaf, 0x78, 0x18, 0xa7, 0xef, 0x2f, 0x38, 0x4b, 0x5e, 0x66,
	0xdc, 0xd7, 0x15, 0x65, 0x93, 0x20, 0x8f, 0x61, 0x5c, 0x03, 0xaf, 0xd8, 0x3b, 0xe9, 0x09, 0x9b,
	0x6e, 0xe0, 0x78, 0xf7, 0x25, 0x36, 0x8b, 0xa3, 0x72, 0xf2, 0x1d, 0xa9, 0xdf, 0xca, 0x91, 0x2f,
	0x60, 0xbf, 0x89, 0xe3, 0x12, 0x6d, 0x69, 0xb2, 0x8d, 0x22, 0x9f, 0xc2, 0xe0, 0x0e, 0x8f, 0xf4,
	0x62, 0xe5, 0xab, 0xeb, 0xe9, 0x48, 0x6d, 0x1d, 0xc4, 0xe8, 0x29, 0x00, 0x59, 0x22, 0xba, 0xea,
	0x89, 0x35, 0x31, 0xf2, 0x8d, 0x9e, 0xe9, 0x8c, 0x0b, 0x16, 0xac, 0xb8, 0xaf, 0xeb, 0x08, 0xa9,
	0xae, 0xad, 0x60, 0x68, 0x5d, 0xe8, 0xfe, 0xd5, 0x86, 0x61, 0x5d, 0x51, 0x6e, 0x6b, 0xc6, 0xdf,
	0x9a, 0x5e, 0xab, 0x83, 0xe5, 0xb6, 0x66, 0xfc, 0xad, 0xdc, 0x56, 0xcb, 0xd8, 0x96, 0xc6, 0xf4,
	0x35, 0xce, 0xe3, 0x78, 0x85, 0x79, 0x30, 0x65, 0xde, 0x2d, 0x97, 0xd7, 0x88, 0xd7, 0x6e, 0xd1,
	0xad, 0x9c, 0x76, 0x2a, 0xe2, 0x33, 0xfe, 0xf6, 0x9c, 0x47, 0xe5, 0xbd, 0x5b, 0x74, 0x93, 0x30,
	0xd4, 0x2f, 0x56, 0x7e, 0xa1, 0x6e, 0xd7, 0xd4, 0x15, 0x41, 0xbe, 0x05, 0x47, 0x83, 0x8b, 0x75,
	0x9a, 0x07, 0x79, 0x9c, 0x2e, 0x12, 0xe6, 0xa9, 0x3d, 0x75, 0xa4, 0xd1, 0xbd, 0x3c, 0x99, 0x00,
	0xd1, 0xdc, 0x9c, 0xa7, 0x61, 0xb1, 0x54, 0x57, 0x5a, 0x6d, 0x61, 0x8c, 0xb3, 0x63, 0x53, 0x91,
	0x95, 0xeb, 0xec, 0xd6, 0xce, 0x5e, 0xe3, 0xdc, 0x39, 0xec, 0x16, 0xef, 0x18, 0xbe, 0xf2, 0x77,
	0x79, 0xa8, 0x47, 0xd2, 0x05, 0x16, 0x35, 0x10, 0xf4, 0x52, 0xf6, 0x3e, 0x13, 0xbc, 0x94, 0xb4,
	0xa4, 0xa4, 0x0e, 0xba, 0xff, 0x6e, 0x41, 0xdf, 0x7c, 0xee, 0x64, 0xd5, 0x62, 0x61, 0xb2, 0xe2,
	0x7e, 0xe9, 0x5e, 0xfd, 0x06, 0x37, 0x60, 0xbc, 0x2c, 0x0d, 0x4d, 0xe3, 0x48, 0x04, 0xd1, 0x9a,
	0xe1, 0x04, 0xca, 0x44, 0xe5, 0xcd, 0xbd, 0x3c, 0xba, 0x65, 0x1d, 0x35, 0xd7, 0x51, 0xc9, 0xb3,
	0x49, 0x90, 0x5f, 0xc1, 0xa3, 0x12, 0xdc, 0x5c, 0x4b, 0x25, 0xd0, 0x07, 0x14, 0xf2, 0x4c, 0x6f,
	0x82, 0x24, 0x31, 0xd6, 0xea, 0xe8, 0x33, 0xd5, 0x61, 0x79, 0x26, 0x05, 0x6d, 0xae, 0xd3, 0xd5,
	0x67, 0xba, 0x87, 0x77, 0xff, 0x66, 0xc1, 0x8f, 0xcc, 0x2e, 0xe0, 0x22, 0xc8, 0x44, 0xbc, 0x4c,
	0x59, 0xf8, 0x81, 0x26, 0xeb, 0x0b, 0xd8, 0xbf, 0x2d, 0x64, 0x0b, 0xef, 0x96, 0x87, 0x4c, 0xf6,
	0x54, 0xea, 0x9d, 0xd8, 0x46, 0x61, 0x95, 0x32, 0x9a, 0x8b, 0xe2, 0xb6, 0xed, 0xc3, 0x36, 0xdd,
	0xc0, 0xdd, 0x73, 0xe8, 0x9b, 0x1b, 0x22, 0x5f, 0x43, 0xaf, 0x9c, 0x52, 0x7f, 0x04, 0xfd, 0xa4,
	0xd9, 0xbb, 0x94, 0xbb, 0xa6, 0x95, 0xd6, 0xfd, 0x12, 0x06, 0xb5, 0x6e, 0x03, 0x5f, 0x23, 0x96,
	0x2f, 0x75, 0xe2, 0xe3, 0x4f, 0x44, 0x42, 0xf6, 0x4e, 0xc7, 0x0a, 0xfe, 0x74, 0x29, 0xf4, 0xca,
	0x7e, 0x03, 0xfb, 0x61, 0xaf, 0xac, 0x15, 0x6d, 0xaa, 0x06, 0xf8, 0x9a, 0x88, 0xf2, 0x1b, 0x4e,
	0x76, 0xaa, 0xc5, 0x6b, 0x52, 0x7d, 0xda, 0x51, 0x43, 0xe2, 0xfe, 0xd3, 0x82, 0x41, 0xad, 0xb1,
	0xc0, 0x76, 0x58, 0xb5, 0x16, 0x66, 0x29, 0x32, 0x21, 0xbc, 0x31, 0x35, 0x54, 0xf5, 0xd5, 0x78,
	0x04, 0x36, 0x70, 0x9c, 0x2d, 0x64, 0xca, 0xbd, 0x55, 0x18, 0x9b, 0x10, 0xce, 0xa6, 0x86, 0xc6,
	0x6c, 0x2a, 0x70, 0x37, 0x70, 0xf7, 0x5b, 0xcc, 0x2d, 0xa3, 0x4d, 0x79, 0x0c, 0x63, 0xa3, 0x6b,
	0x31, 0x37, 0xbc, 0x81, 0xbb, 0x77, 0xd0, 0x37, 0x7b, 0x17, 0xb4, 0x35, 0xba, 0x97, 0x9a, 0x6d,
	0x13, 0xc7, 0x52, 0xb4, 0x8e, 0x36, 0xd4, 0xea, 0xcc, 0x5b, 0x18, 0xf7, 0xcf, 0x78, 0xab, 0xe6,
	0x67, 0xe9, 0xff, 0xe9, 0xd3, 0x3f, 0x85, 0xc1, 0xeb, 0xb5, 0xf7, 0x86, 0x0b, 0xf3, 0xf3, 0xa0,
	0x4d, 0xeb, 0x20, 0x36, 0x65, 0x9c, 0x79, 0xb7, 0xd5, 0x27, 0x70, 0xf5, 0xb1, 0xf3, 0xb4, 0xc2,
	0xa9, 0x29, 0x72, 0xff, 0x81, 0xdf, 0xed, 0x06, 0xab, 0xda, 0x9e, 0x40, 0x7f, 0xe5, 0xe0, 0x4f,
	0xf2, 0x0b, 0x18, 0xca, 0xcb, 0x2a, 0x03, 0x55, 0x7f, 0x99, 0xab, 0xa6, 0xf3, 0x65, 0x1a, 0x54,
	0x11, 0xdc, 0x10, 0x92, 0xef, 0x60, 0x74, 0x23, 0x9f, 0xb0, 0xca, 0xd6, 0xbe, 0xcf, 0xb6, 0xa9,
	0x74, 0x97, 0x30, 0xa8, 0x29, 0xee, 0x09, 0x69, 0x9d, 0x19, 0xaa, 0xd8, 0x9a, 0x99, 0x61, 0x97,
	0x99, 0x81, 0xb7, 0x5b, 0xe5, 0xe1, 0x8e, 0x4c, 0xde, 0x0a, 0x78, 0xfc, 0x27, 0x0b, 0xa0, 0x6a,
	0x65, 0xc8, 0xc7, 0xb0, 0xff, 0xfc, 0x87, 0xab, 0x57, 0xe7, 0xd3, 0x57, 0xd7, 0xbf, 0x9b, 0x3f,
	0x7d, 0xf5, 0x72, 0xf6, 0xfd, 0xec, 0xc5, 0x6f, 0x67, 0xe3, 0x07, 0xe4, 0xc7, 0x40, 0x4c, 0x62,
	0xf1, 0x94, 0x3e, 0x3b, 0xb9, 0x1c, 0x5b, 0xc4, 0x81, 0x87, 0x26, 0x3e, 0x3f, 0xa1, 0x27, 0x97,
	0x97, 0x4f, 0x2f, 0xc7, 0x2d, 0xb2, 0x0f, 0x23, 0x93, 0x99, 0x5e, 0x2d, 0xc6, 0x36, 0x21, 0x30,
	0x34, 0xc1, 0xf3, 0xa3, 0xf1, 0xce, 0xe9, 0x57, 0xf0, 0x33, 0x2f, 0x0e, 0x27, 0x11, 0xcb, 0x79,
	0xea, 0xc5, 0x69, 0x32, 0x49, 0x82, 0x28, 0x89, 0x83, 0x48, 0x4c, 0x96, 0x69, 0xe2, 0x4d, 0x04,
	0x16, 0x8a, 0xd3, 0x1e, 0x3a, 0x68, 0x9e, 0xc6, 0x22, 0x9e, 0x5b, 0xbf, 0xb7, 0x9f, 0xe4, 0x47,
	0xaf, 0x3b, 0xf2, 0x5f, 0x98, 0x2f, 0xff, 0x17, 0x00, 0x00, 0xff, 0xff, 0xad, 0x08, 0xa7, 0x54,
	0xaf, 0x11, 0x00, 0x00,
}
