// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.36.1
// source: v1/Stat.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PJvmGcType int32

const (
	PJvmGcType_JVM_GC_TYPE_UNKNOWN  PJvmGcType = 0
	PJvmGcType_JVM_GC_TYPE_SERIAL   PJvmGcType = 1
	PJvmGcType_JVM_GC_TYPE_PARALLEL PJvmGcType = 2
	PJvmGcType_JVM_GC_TYPE_CMS      PJvmGcType = 3
	PJvmGcType_JVM_GC_TYPE_G1       PJvmGcType = 4
	PJvmGcType_JVM_GC_TYPE_ZGC      PJvmGcType = 5
)

// Enum value maps for PJvmGcType.
var (
	PJvmGcType_name = map[int32]string{
		0: "JVM_GC_TYPE_UNKNOWN",
		1: "JVM_GC_TYPE_SERIAL",
		2: "JVM_GC_TYPE_PARALLEL",
		3: "JVM_GC_TYPE_CMS",
		4: "JVM_GC_TYPE_G1",
		5: "JVM_GC_TYPE_ZGC",
	}
	PJvmGcType_value = map[string]int32{
		"JVM_GC_TYPE_UNKNOWN":  0,
		"JVM_GC_TYPE_SERIAL":   1,
		"JVM_GC_TYPE_PARALLEL": 2,
		"JVM_GC_TYPE_CMS":      3,
		"JVM_GC_TYPE_G1":       4,
		"JVM_GC_TYPE_ZGC":      5,
	}
)

func (x PJvmGcType) Enum() *PJvmGcType {
	p := new(PJvmGcType)
	*p = x
	return p
}

func (x PJvmGcType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PJvmGcType) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_Stat_proto_enumTypes[0].Descriptor()
}

func (PJvmGcType) Type() protoreflect.EnumType {
	return &file_v1_Stat_proto_enumTypes[0]
}

func (x PJvmGcType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PJvmGcType.Descriptor instead.
func (PJvmGcType) EnumDescriptor() ([]byte, []int) {
	return file_v1_Stat_proto_rawDescGZIP(), []int{0}
}

type PPing struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PPing) Reset() {
	*x = PPing{}
	mi := &file_v1_Stat_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PPing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PPing) ProtoMessage() {}

func (x *PPing) ProtoReflect() protoreflect.Message {
	mi := &file_v1_Stat_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PPing.ProtoReflect.Descriptor instead.
func (*PPing) Descriptor() ([]byte, []int) {
	return file_v1_Stat_proto_rawDescGZIP(), []int{0}
}

type PStatMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Field:
	//
	//	*PStatMessage_AgentStat
	//	*PStatMessage_AgentStatBatch
	//	*PStatMessage_AgentUriStat
	//	*PStatMessage_ProfilerMetric
	Field         isPStatMessage_Field `protobuf_oneof:"field"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PStatMessage) Reset() {
	*x = PStatMessage{}
	mi := &file_v1_Stat_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PStatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PStatMessage) ProtoMessage() {}

func (x *PStatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_v1_Stat_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PStatMessage.ProtoReflect.Descriptor instead.
func (*PStatMessage) Descriptor() ([]byte, []int) {
	return file_v1_Stat_proto_rawDescGZIP(), []int{1}
}

func (x *PStatMessage) GetField() isPStatMessage_Field {
	if x != nil {
		return x.Field
	}
	return nil
}

func (x *PStatMessage) GetAgentStat() *PAgentStat {
	if x != nil {
		if x, ok := x.Field.(*PStatMessage_AgentStat); ok {
			return x.AgentStat
		}
	}
	return nil
}

func (x *PStatMessage) GetAgentStatBatch() *PAgentStatBatch {
	if x != nil {
		if x, ok := x.Field.(*PStatMessage_AgentStatBatch); ok {
			return x.AgentStatBatch
		}
	}
	return nil
}

func (x *PStatMessage) GetAgentUriStat() *PAgentUriStat {
	if x != nil {
		if x, ok := x.Field.(*PStatMessage_AgentUriStat); ok {
			return x.AgentUriStat
		}
	}
	return nil
}

func (x *PStatMessage) GetProfilerMetric() *PProfilerMetric {
	if x != nil {
		if x, ok := x.Field.(*PStatMessage_ProfilerMetric); ok {
			return x.ProfilerMetric
		}
	}
	return nil
}

type isPStatMessage_Field interface {
	isPStatMessage_Field()
}

type PStatMessage_AgentStat struct {
	AgentStat *PAgentStat `protobuf:"bytes,1,opt,name=agentStat,proto3,oneof"`
}

type PStatMessage_AgentStatBatch struct {
	AgentStatBatch *PAgentStatBatch `protobuf:"bytes,2,opt,name=agentStatBatch,proto3,oneof"`
}

type PStatMessage_AgentUriStat struct {
	AgentUriStat *PAgentUriStat `protobuf:"bytes,3,opt,name=agentUriStat,proto3,oneof"`
}

type PStatMessage_ProfilerMetric struct {
	ProfilerMetric *PProfilerMetric `protobuf:"bytes,4,opt,name=profilerMetric,proto3,oneof"`
}

func (*PStatMessage_AgentStat) isPStatMessage_Field() {}

func (*PStatMessage_AgentStatBatch) isPStatMessage_Field() {}

func (*PStatMessage_AgentUriStat) isPStatMessage_Field() {}

func (*PStatMessage_ProfilerMetric) isPStatMessage_Field() {}

type PAgentInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Hostname       string                 `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Ip             string                 `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`
	Ports          string                 `protobuf:"bytes,3,opt,name=ports,proto3" json:"ports,omitempty"`
	ServiceType    int32                  `protobuf:"varint,4,opt,name=serviceType,proto3" json:"serviceType,omitempty"`
	Pid            int32                  `protobuf:"varint,5,opt,name=pid,proto3" json:"pid,omitempty"`
	AgentVersion   string                 `protobuf:"bytes,6,opt,name=agentVersion,proto3" json:"agentVersion,omitempty"`
	VmVersion      string                 `protobuf:"bytes,7,opt,name=vmVersion,proto3" json:"vmVersion,omitempty"`
	EndTimestamp   int64                  `protobuf:"varint,8,opt,name=endTimestamp,proto3" json:"endTimestamp,omitempty"`
	EndStatus      int32                  `protobuf:"varint,9,opt,name=endStatus,proto3" json:"endStatus,omitempty"`
	ServerMetaData *PServerMetaData       `protobuf:"bytes,10,opt,name=serverMetaData,proto3" json:"serverMetaData,omitempty"`
	JvmInfo        *PJvmInfo              `protobuf:"bytes,11,opt,name=jvmInfo,proto3" json:"jvmInfo,omitempty"`
	Container      bool                   `protobuf:"varint,12,opt,name=container,proto3" json:"container,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PAgentInfo) Reset() {
	*x = PAgentInfo{}
	mi := &file_v1_Stat_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PAgentInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PAgentInfo) ProtoMessage() {}

func (x *PAgentInfo) ProtoReflect() protoreflect.Message {
	mi := &file_v1_Stat_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PAgentInfo.ProtoReflect.Descriptor instead.
func (*PAgentInfo) Descriptor() ([]byte, []int) {
	return file_v1_Stat_proto_rawDescGZIP(), []int{2}
}

func (x *PAgentInfo) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *PAgentInfo) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *PAgentInfo) GetPorts() string {
	if x != nil {
		return x.Ports
	}
	return ""
}

func (x *PAgentInfo) GetServiceType() int32 {
	if x != nil {
		return x.ServiceType
	}
	return 0
}

func (x *PAgentInfo) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *PAgentInfo) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

func (x *PAgentInfo) GetVmVersion() string {
	if x != nil {
		return x.VmVersion
	}
	return ""
}

func (x *PAgentInfo) GetEndTimestamp() int64 {
	if x != nil {
		return x.EndTimestamp
	}
	return 0
}

func (x *PAgentInfo) GetEndStatus() int32 {
	if x != nil {
		return x.EndStatus
	}
	return 0
}

func (x *PAgentInfo) GetServerMetaData() *PServerMetaData {
	if x != nil {
		return x.ServerMetaData
	}
	return nil
}

func (x *PAgentInfo) GetJvmInfo() *PJvmInfo {
	if x != nil {
		return x.JvmInfo
	}
	return nil
}

func (x *PAgentInfo) GetContainer() bool {
	if x != nil {
		return x.Container
	}
	return false
}

type PServerMetaData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerInfo    string                 `protobuf:"bytes,1,opt,name=serverInfo,proto3" json:"serverInfo,omitempty"`
	VmArg         []string               `protobuf:"bytes,2,rep,name=vmArg,proto3" json:"vmArg,omitempty"`
	ServiceInfo   []*PServiceInfo        `protobuf:"bytes,3,rep,name=serviceInfo,proto3" json:"serviceInfo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PServerMetaData) Reset() {
	*x = PServerMetaData{}
	mi := &file_v1_Stat_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PServerMetaData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PServerMetaData) ProtoMessage() {}

func (x *PServerMetaData) ProtoReflect() protoreflect.Message {
	mi := &file_v1_Stat_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PServerMetaData.ProtoReflect.Descriptor instead.
func (*PServerMetaData) Descriptor() ([]byte, []int) {
	return file_v1_Stat_proto_rawDescGZIP(), []int{3}
}

func (x *PServerMetaData) GetServerInfo() string {
	if x != nil {
		return x.ServerInfo
	}
	return ""
}

func (x *PServerMetaData) GetVmArg() []string {
	if x != nil {
		return x.VmArg
	}
	return nil
}

func (x *PServerMetaData) GetServiceInfo() []*PServiceInfo {
	if x != nil {
		return x.ServiceInfo
	}
	return nil
}

type PServiceInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceName   string                 `protobuf:"bytes,1,opt,name=serviceName,proto3" json:"serviceName,omitempty"`
	ServiceLib    []string               `protobuf:"bytes,2,rep,name=serviceLib,proto3" json:"serviceLib,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PServiceInfo) Reset() {
	*x = PServiceInfo{}
	mi := &file_v1_Stat_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PServiceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PServiceInfo) ProtoMessage() {}

func (x *PServiceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_v1_Stat_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PServiceInfo.ProtoReflect.Descriptor instead.
func (*PServiceInfo) Descriptor() ([]byte, []int) {
	return file_v1_Stat_proto_rawDescGZIP(), []int{4}
}

func (x *PServiceInfo) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *PServiceInfo) GetServiceLib() []string {
	if x != nil {
		return x.ServiceLib
	}
	return nil
}

type PJvmInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       int32                  `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	VmVersion     string                 `protobuf:"bytes,2,opt,name=vmVersion,proto3" json:"vmVersion,omitempty"`
	GcType        PJvmGcType             `protobuf:"varint,3,opt,name=gcType,proto3,enum=v1.PJvmGcType" json:"gcType,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PJvmInfo) Reset() {
	*x = PJvmInfo{}
	mi := &file_v1_Stat_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PJvmInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PJvmInfo) ProtoMessage() {}

func (x *PJvmInfo) ProtoReflect() protoreflect.Message {
	mi := &file_v1_Stat_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PJvmInfo.ProtoReflect.Descriptor instead.
func (*PJvmInfo) Descriptor() ([]byte, []int) {
	return file_v1_Stat_proto_rawDescGZIP(), []int{5}
}

func (x *PJvmInfo) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *PJvmInfo) GetVmVersion() string {
	if x != nil {
		return x.VmVersion
	}
	return ""
}

func (x *PJvmInfo) GetGcType() PJvmGcType {
	if x != nil {
		return x.GcType
	}
	return PJvmGcType_JVM_GC_TYPE_UNKNOWN
}

type PAgentStat struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Timestamp       int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	CollectInterval int64                  `protobuf:"varint,2,opt,name=collectInterval,proto3" json:"collectInterval,omitempty"`
	Gc              *PJvmGc                `protobuf:"bytes,3,opt,name=gc,proto3" json:"gc,omitempty"`
	CpuLoad         *PCpuLoad              `protobuf:"bytes,4,opt,name=cpuLoad,proto3" json:"cpuLoad,omitempty"`
	Transaction     *PTransaction          `protobuf:"bytes,5,opt,name=transaction,proto3" json:"transaction,omitempty"`
	ActiveTrace     *PActiveTrace          `protobuf:"bytes,6,opt,name=activeTrace,proto3" json:"activeTrace,omitempty"`
	DataSourceList  *PDataSourceList       `protobuf:"bytes,7,opt,name=dataSourceList,proto3" json:"dataSourceList,omitempty"`
	ResponseTime    *PResponseTime         `protobuf:"bytes,8,opt,name=responseTime,proto3" json:"responseTime,omitempty"`
	Deadlock        *PDeadlock             `protobuf:"bytes,9,opt,name=deadlock,proto3" json:"deadlock,omitempty"`
	FileDescriptor  *PFileDescriptor       `protobuf:"bytes,10,opt,name=fileDescriptor,proto3" json:"fileDescriptor,omitempty"`
	DirectBuffer    *PDirectBuffer         `protobuf:"bytes,11,opt,name=directBuffer,proto3" json:"directBuffer,omitempty"`
	Metadata        string                 `protobuf:"bytes,12,opt,name=metadata,proto3" json:"metadata,omitempty"`
	TotalThread     *PTotalThread          `protobuf:"bytes,13,opt,name=totalThread,proto3" json:"totalThread,omitempty"`
	LoadedClass     *PLoadedClass          `protobuf:"bytes,14,opt,name=loadedClass,proto3" json:"loadedClass,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PAgentStat) Reset() {
	*x = PAgentStat{}
	mi := &file_v1_Stat_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PAgentStat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PAgentStat) ProtoMessage() {}

func (x *PAgentStat) ProtoReflect() protoreflect.Message {
	mi := &file_v1_Stat_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PAgentStat.ProtoReflect.Descriptor instead.
func (*PAgentStat) Descriptor() ([]byte, []int) {
	return file_v1_Stat_proto_rawDescGZIP(), []int{6}
}

func (x *PAgentStat) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *PAgentStat) GetCollectInterval() int64 {
	if x != nil {
		return x.CollectInterval
	}
	return 0
}

func (x *PAgentStat) GetGc() *PJvmGc {
	if x != nil {
		return x.Gc
	}
	return nil
}

func (x *PAgentStat) GetCpuLoad() *PCpuLoad {
	if x != nil {
		return x.CpuLoad
	}
	return nil
}

func (x *PAgentStat) GetTransaction() *PTransaction {
	if x != nil {
		return x.Transaction
	}
	return nil
}

func (x *PAgentStat) GetActiveTrace() *PActiveTrace {
	if x != nil {
		return x.ActiveTrace
	}
	return nil
}

func (x *PAgentStat) GetDataSourceList() *PDataSourceList {
	if x != nil {
		return x.DataSourceList
	}
	return nil
}

func (x *PAgentStat) GetResponseTime() *PResponseTime {
	if x != nil {
		return x.ResponseTime
	}
	return nil
}

func (x *PAgentStat) GetDeadlock() *PDeadlock {
	if x != nil {
		return x.Deadlock
	}
	return nil
}

func (x *PAgentStat) GetFileDescriptor() *PFileDescriptor {
	if x != nil {
		return x.FileDescriptor
	}
	return nil
}

func (x *PAgentStat) GetDirectBuffer() *PDirectBuffer {
	if x != nil {
		return x.DirectBuffer
	}
	return nil
}

func (x *PAgentStat) GetMetadata() string {
	if x != nil {
		return x.Metadata
	}
	return ""
}

func (x *PAgentStat) GetTotalThread() *PTotalThread {
	if x != nil {
		return x.TotalThread
	}
	return nil
}

func (x *PAgentStat) GetLoadedClass() *PLoadedClass {
	if x != nil {
		return x.LoadedClass
	}
	return nil
}

type PProfilerMetric struct {
	state           protoimpl.MessageState  `protogen:"open.v1"`
	Timestamp       int64                   `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	CollectInterval int64                   `protobuf:"varint,2,opt,name=collectInterval,proto3" json:"collectInterval,omitempty"`
	Name            string                  `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Fields          []*PProfilerMetricField `protobuf:"bytes,4,rep,name=fields,proto3" json:"fields,omitempty"`
	Tags            []*PProfilerMetricField `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PProfilerMetric) Reset() {
	*x = PProfilerMetric{}
	mi := &file_v1_Stat_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PProfilerMetric) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PProfilerMetric) ProtoMessage() {}

func (x *PProfilerMetric) ProtoReflect() protoreflect.Message {
	mi := &file_v1_Stat_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PProfilerMetric.ProtoReflect.Descriptor instead.
func (*PProfilerMetric) Descriptor() ([]byte, []int) {
	return file_v1_Stat_proto_rawDescGZIP(), []int{7}
}

func (x *PProfilerMetric) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *PProfilerMetric) GetCollectInterval() int64 {
	if x != nil {
		return x.CollectInterval
	}
	return 0
}

func (x *PProfilerMetric) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PProfilerMetric) GetFields() []*PProfilerMetricField {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *PProfilerMetric) GetTags() []*PProfilerMetricField {
	if x != nil {
		return x.Tags
	}
	return nil
}

type PProfilerMetricField struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Name  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Types that are valid to be assigned to Value:
	//
	//	*PProfilerMetricField_StringValue
	//	*PProfilerMetricField_LongValue
	Value         isPProfilerMetricField_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PProfilerMetricField) Reset() {
	*x = PProfilerMetricField{}
	mi := &file_v1_Stat_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PProfilerMetricField) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PProfilerMetricField) ProtoMessage() {}

func (x *PProfilerMetricField) ProtoReflect() protoreflect.Message {
	mi := &file_v1_Stat_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PProfilerMetricField.ProtoReflect.Descriptor instead.
func (*PProfilerMetricField) Descriptor() ([]byte, []int) {
	return file_v1_Stat_proto_rawDescGZIP(), []int{8}
}

func (x *PProfilerMetricField) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PProfilerMetricField) GetValue() isPProfilerMetricField_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *PProfilerMetricField) GetStringValue() string {
	if x != nil {
		if x, ok := x.Value.(*PProfilerMetricField_StringValue); ok {
			return x.StringValue
		}
	}
	return ""
}

func (x *PProfilerMetricField) GetLongValue() int64 {
	if x != nil {
		if x, ok := x.Value.(*PProfilerMetricField_LongValue); ok {
			return x.LongValue
		}
	}
	return 0
}

type isPProfilerMetricField_Value interface {
	isPProfilerMetricField_Value()
}

type PProfilerMetricField_StringValue struct {
	StringValue string `protobuf:"bytes,2,opt,name=stringValue,proto3,oneof"`
}

type PProfilerMetricField_LongValue struct {
	LongValue int64 `protobuf:"varint,3,opt,name=longValue,proto3,oneof"`
}

func (*PProfilerMetricField_StringValue) isPProfilerMetricField_Value() {}

func (*PProfilerMetricField_LongValue) isPProfilerMetricField_Value() {}

type PAgentStatBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentStat     []*PAgentStat          `protobuf:"bytes,1,rep,name=agentStat,proto3" json:"agentStat,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PAgentStatBatch) Reset() {
	*x = PAgentStatBatch{}
	mi := &file_v1_Stat_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PAgentStatBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PAgentStatBatch) ProtoMessage() {}

func (x *PAgentStatBatch) ProtoReflect() protoreflect.Message {
	mi := &file_v1_Stat_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PAgentStatBatch.ProtoReflect.Descriptor instead.
func (*PAgentStatBatch) Descriptor() ([]byte, []int) {
	return file_v1_Stat_proto_rawDescGZIP(), []int{9}
}

func (x *PAgentStatBatch) GetAgentStat() []*PAgentStat {
	if x != nil {
		return x.AgentStat
	}
	return nil
}

type PDataSource struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Id                   int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ServiceTypeCode      int32                  `protobuf:"varint,2,opt,name=serviceTypeCode,proto3" json:"serviceTypeCode,omitempty"`
	DatabaseName         string                 `protobuf:"bytes,3,opt,name=databaseName,proto3" json:"databaseName,omitempty"`
	Url                  string                 `protobuf:"bytes,4,opt,name=url,proto3" json:"url,omitempty"`
	ActiveConnectionSize int32                  `protobuf:"varint,5,opt,name=activeConnectionSize,proto3" json:"activeConnectionSize,omitempty"`
	MaxConnectionSize    int32                  `protobuf:"varint,6,opt,name=maxConnectionSize,proto3" json:"maxConnectionSize,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *PDataSource) Reset() {
	*x = PDataSource{}
	mi := &file_v1_Stat_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PDataSource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PDataSource) ProtoMessage() {}

func (x *PDataSource) ProtoReflect() protoreflect.Message {
	mi := &file_v1_Stat_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PDataSource.ProtoReflect.Descriptor instead.
func (*PDataSource) Descriptor() ([]byte, []int) {
	return file_v1_Stat_proto_rawDescGZIP(), []int{10}
}

func (x *PDataSource) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PDataSource) GetServiceTypeCode() int32 {
	if x != nil {
		return x.ServiceTypeCode
	}
	return 0
}

func (x *PDataSource) GetDatabaseName() string {
	if x != nil {
		return x.DatabaseName
	}
	return ""
}

func (x *PDataSource) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *PDataSource) GetActiveConnectionSize() int32 {
	if x != nil {
		return x.ActiveConnectionSize
	}
	return 0
}

func (x *PDataSource) GetMaxConnectionSize() int32 {
	if x != nil {
		return x.MaxConnectionSize
	}
	return 0
}

type PDataSourceList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DataSource    []*PDataSource         `protobuf:"bytes,1,rep,name=dataSource,proto3" json:"dataSource,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PDataSourceList) Reset() {
	*x = PDataSourceList{}
	mi := &file_v1_Stat_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PDataSourceList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PDataSourceList) ProtoMessage() {}

func (x *PDataSourceList) ProtoReflect() protoreflect.Message {
	mi := &file_v1_Stat_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PDataSourceList.ProtoReflect.Descriptor instead.
func (*PDataSourceList) Descriptor() ([]byte, []int) {
	return file_v1_Stat_proto_rawDescGZIP(), []int{11}
}

func (x *PDataSourceList) GetDataSource() []*PDataSource {
	if x != nil {
		return x.DataSource
	}
	return nil
}

type PFileDescriptor struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	OpenFileDescriptorCount int64                  `protobuf:"varint,1,opt,name=openFileDescriptorCount,proto3" json:"openFileDescriptorCount,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *PFileDescriptor) Reset() {
	*x = PFileDescriptor{}
	mi := &file_v1_Stat_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PFileDescriptor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PFileDescriptor) ProtoMessage() {}

func (x *PFileDescriptor) ProtoReflect() protoreflect.Message {
	mi := &file_v1_Stat_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PFileDescriptor.ProtoReflect.Descriptor instead.
func (*PFileDescriptor) Descriptor() ([]byte, []int) {
	return file_v1_Stat_proto_rawDescGZIP(), []int{12}
}

func (x *PFileDescriptor) GetOpenFileDescriptorCount() int64 {
	if x != nil {
		return x.OpenFileDescriptorCount
	}
	return 0
}

type PJvmGc struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Type                 PJvmGcType             `protobuf:"varint,1,opt,name=type,proto3,enum=v1.PJvmGcType" json:"type,omitempty"`
	JvmMemoryHeapUsed    int64                  `protobuf:"varint,2,opt,name=jvmMemoryHeapUsed,proto3" json:"jvmMemoryHeapUsed,omitempty"`
	JvmMemoryHeapMax     int64                  `protobuf:"varint,3,opt,name=jvmMemoryHeapMax,proto3" json:"jvmMemoryHeapMax,omitempty"`
	JvmMemoryNonHeapUsed int64                  `protobuf:"varint,4,opt,name=jvmMemoryNonHeapUsed,proto3" json:"jvmMemoryNonHeapUsed,omitempty"`
	JvmMemoryNonHeapMax  int64                  `protobuf:"varint,5,opt,name=jvmMemoryNonHeapMax,proto3" json:"jvmMemoryNonHeapMax,omitempty"`
	JvmGcOldCount        int64                  `protobuf:"varint,6,opt,name=jvmGcOldCount,proto3" json:"jvmGcOldCount,omitempty"`
	JvmGcOldTime         int64                  `protobuf:"varint,7,opt,name=jvmGcOldTime,proto3" json:"jvmGcOldTime,omitempty"`
	JvmGcDetailed        *PJvmGcDetailed        `protobuf:"bytes,8,opt,name=jvmGcDetailed,proto3" json:"jvmGcDetailed,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *PJvmGc) Reset() {
	*x = PJvmGc{}
	mi := &file_v1_Stat_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PJvmGc) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PJvmGc) ProtoMessage() {}

func (x *PJvmGc) ProtoReflect() protoreflect.Message {
	mi := &file_v1_Stat_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PJvmGc.ProtoReflect.Descriptor instead.
func (*PJvmGc) Descriptor() ([]byte, []int) {
	return file_v1_Stat_proto_rawDescGZIP(), []int{13}
}

func (x *PJvmGc) GetType() PJvmGcType {
	if x != nil {
		return x.Type
	}
	return PJvmGcType_JVM_GC_TYPE_UNKNOWN
}

func (x *PJvmGc) GetJvmMemoryHeapUsed() int64 {
	if x != nil {
		return x.JvmMemoryHeapUsed
	}
	return 0
}

func (x *PJvmGc) GetJvmMemoryHeapMax() int64 {
	if x != nil {
		return x.JvmMemoryHeapMax
	}
	return 0
}

func (x *PJvmGc) GetJvmMemoryNonHeapUsed() int64 {
	if x != nil {
		return x.JvmMemoryNonHeapUsed
	}
	return 0
}

func (x *PJvmGc) GetJvmMemoryNonHeapMax() int64 {
	if x != nil {
		return x.JvmMemoryNonHeapMax
	}
	return 0
}

func (x *PJvmGc) GetJvmGcOldCount() int64 {
	if x != nil {
		return x.JvmGcOldCount
	}
	return 0
}

func (x *PJvmGc) GetJvmGcOldTime() int64 {
	if x != nil {
		return x.JvmGcOldTime
	}
	return 0
}

func (x *PJvmGc) GetJvmGcDetailed() *PJvmGcDetailed {
	if x != nil {
		return x.JvmGcDetailed
	}
	return nil
}

type PJvmGcDetailed struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	JvmGcNewCount            int64                  `protobuf:"varint,1,opt,name=jvmGcNewCount,proto3" json:"jvmGcNewCount,omitempty"`
	JvmGcNewTime             int64                  `protobuf:"varint,2,opt,name=jvmGcNewTime,proto3" json:"jvmGcNewTime,omitempty"`
	JvmPoolCodeCacheUsed     float64                `protobuf:"fixed64,3,opt,name=jvmPoolCodeCacheUsed,proto3" json:"jvmPoolCodeCacheUsed,omitempty"`
	JvmPoolNewGenUsed        float64                `protobuf:"fixed64,4,opt,name=jvmPoolNewGenUsed,proto3" json:"jvmPoolNewGenUsed,omitempty"`
	JvmPoolOldGenUsed        float64                `protobuf:"fixed64,5,opt,name=jvmPoolOldGenUsed,proto3" json:"jvmPoolOldGenUsed,omitempty"`
	JvmPoolSurvivorSpaceUsed float64                `protobuf:"fixed64,6,opt,name=jvmPoolSurvivorSpaceUsed,proto3" json:"jvmPoolSurvivorSpaceUsed,omitempty"`
	JvmPoolPermGenUsed       float64                `protobuf:"fixed64,7,opt,name=jvmPoolPermGenUsed,proto3" json:"jvmPoolPermGenUsed,omitempty"`
	JvmPoolMetaspaceUsed     float64                `protobuf:"fixed64,8,opt,name=jvmPoolMetaspaceUsed,proto3" json:"jvmPoolMetaspaceUsed,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *PJvmGcDetailed) Reset() {
	*x = PJvmGcDetailed{}
	mi := &file_v1_Stat_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PJvmGcDetailed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PJvmGcDetailed) ProtoMessage() {}

func (x *PJvmGcDetailed) ProtoReflect() protoreflect.Message {
	mi := &file_v1_Stat_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PJvmGcDetailed.ProtoReflect.Descriptor instead.
func (*PJvmGcDetailed) Descriptor() ([]byte, []int) {
	return file_v1_Stat_proto_rawDescGZIP(), []int{14}
}

func (x *PJvmGcDetailed) GetJvmGcNewCount() int64 {
	if x != nil {
		return x.JvmGcNewCount
	}
	return 0
}

func (x *PJvmGcDetailed) GetJvmGcNewTime() int64 {
	if x != nil {
		return x.JvmGcNewTime
	}
	return 0
}

func (x *PJvmGcDetailed) GetJvmPoolCodeCacheUsed() float64 {
	if x != nil {
		return x.JvmPoolCodeCacheUsed
	}
	return 0
}

func (x *PJvmGcDetailed) GetJvmPoolNewGenUsed() float64 {
	if x != nil {
		return x.JvmPoolNewGenUsed
	}
	return 0
}

func (x *PJvmGcDetailed) GetJvmPoolOldGenUsed() float64 {
	if x != nil {
		return x.JvmPoolOldGenUsed
	}
	return 0
}

func (x *PJvmGcDetailed) GetJvmPoolSurvivorSpaceUsed() float64 {
	if x != nil {
		return x.JvmPoolSurvivorSpaceUsed
	}
	return 0
}

func (x *PJvmGcDetailed) GetJvmPoolPermGenUsed() float64 {
	if x != nil {
		return x.JvmPoolPermGenUsed
	}
	return 0
}

func (x *PJvmGcDetailed) GetJvmPoolMetaspaceUsed() float64 {
	if x != nil {
		return x.JvmPoolMetaspaceUsed
	}
	return 0
}

type PCpuLoad struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JvmCpuLoad    float64                `protobuf:"fixed64,1,opt,name=jvmCpuLoad,proto3" json:"jvmCpuLoad,omitempty"`
	SystemCpuLoad float64                `protobuf:"fixed64,2,opt,name=systemCpuLoad,proto3" json:"systemCpuLoad,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PCpuLoad) Reset() {
	*x = PCpuLoad{}
	mi := &file_v1_Stat_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PCpuLoad) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PCpuLoad) ProtoMessage() {}

func (x *PCpuLoad) ProtoReflect() protoreflect.Message {
	mi := &file_v1_Stat_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PCpuLoad.ProtoReflect.Descriptor instead.
func (*PCpuLoad) Descriptor() ([]byte, []int) {
	return file_v1_Stat_proto_rawDescGZIP(), []int{15}
}

func (x *PCpuLoad) GetJvmCpuLoad() float64 {
	if x != nil {
		return x.JvmCpuLoad
	}
	return 0
}

func (x *PCpuLoad) GetSystemCpuLoad() float64 {
	if x != nil {
		return x.SystemCpuLoad
	}
	return 0
}

type PTransaction struct {
	state                      protoimpl.MessageState `protogen:"open.v1"`
	SampledNewCount            int64                  `protobuf:"varint,2,opt,name=sampledNewCount,proto3" json:"sampledNewCount,omitempty"`
	SampledContinuationCount   int64                  `protobuf:"varint,3,opt,name=sampledContinuationCount,proto3" json:"sampledContinuationCount,omitempty"`
	UnsampledNewCount          int64                  `protobuf:"varint,4,opt,name=unsampledNewCount,proto3" json:"unsampledNewCount,omitempty"`
	UnsampledContinuationCount int64                  `protobuf:"varint,5,opt,name=unsampledContinuationCount,proto3" json:"unsampledContinuationCount,omitempty"`
	SkippedNewCount            int64                  `protobuf:"varint,6,opt,name=skippedNewCount,proto3" json:"skippedNewCount,omitempty"`
	SkippedContinuationCount   int64                  `protobuf:"varint,7,opt,name=skippedContinuationCount,proto3" json:"skippedContinuationCount,omitempty"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *PTransaction) Reset() {
	*x = PTransaction{}
	mi := &file_v1_Stat_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PTransaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PTransaction) ProtoMessage() {}

func (x *PTransaction) ProtoReflect() protoreflect.Message {
	mi := &file_v1_Stat_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PTransaction.ProtoReflect.Descriptor instead.
func (*PTransaction) Descriptor() ([]byte, []int) {
	return file_v1_Stat_proto_rawDescGZIP(), []int{16}
}

func (x *PTransaction) GetSampledNewCount() int64 {
	if x != nil {
		return x.SampledNewCount
	}
	return 0
}

func (x *PTransaction) GetSampledContinuationCount() int64 {
	if x != nil {
		return x.SampledContinuationCount
	}
	return 0
}

func (x *PTransaction) GetUnsampledNewCount() int64 {
	if x != nil {
		return x.UnsampledNewCount
	}
	return 0
}

func (x *PTransaction) GetUnsampledContinuationCount() int64 {
	if x != nil {
		return x.UnsampledContinuationCount
	}
	return 0
}

func (x *PTransaction) GetSkippedNewCount() int64 {
	if x != nil {
		return x.SkippedNewCount
	}
	return 0
}

func (x *PTransaction) GetSkippedContinuationCount() int64 {
	if x != nil {
		return x.SkippedContinuationCount
	}
	return 0
}

type PActiveTraceHistogram struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Version             int32                  `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	HistogramSchemaType int32                  `protobuf:"varint,2,opt,name=histogramSchemaType,proto3" json:"histogramSchemaType,omitempty"`
	ActiveTraceCount    []int32                `protobuf:"varint,3,rep,packed,name=activeTraceCount,proto3" json:"activeTraceCount,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *PActiveTraceHistogram) Reset() {
	*x = PActiveTraceHistogram{}
	mi := &file_v1_Stat_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PActiveTraceHistogram) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PActiveTraceHistogram) ProtoMessage() {}

func (x *PActiveTraceHistogram) ProtoReflect() protoreflect.Message {
	mi := &file_v1_Stat_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PActiveTraceHistogram.ProtoReflect.Descriptor instead.
func (*PActiveTraceHistogram) Descriptor() ([]byte, []int) {
	return file_v1_Stat_proto_rawDescGZIP(), []int{17}
}

func (x *PActiveTraceHistogram) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *PActiveTraceHistogram) GetHistogramSchemaType() int32 {
	if x != nil {
		return x.HistogramSchemaType
	}
	return 0
}

func (x *PActiveTraceHistogram) GetActiveTraceCount() []int32 {
	if x != nil {
		return x.ActiveTraceCount
	}
	return nil
}

type PActiveTrace struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Histogram     *PActiveTraceHistogram `protobuf:"bytes,1,opt,name=histogram,proto3" json:"histogram,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PActiveTrace) Reset() {
	*x = PActiveTrace{}
	mi := &file_v1_Stat_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PActiveTrace) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PActiveTrace) ProtoMessage() {}

func (x *PActiveTrace) ProtoReflect() protoreflect.Message {
	mi := &file_v1_Stat_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PActiveTrace.ProtoReflect.Descriptor instead.
func (*PActiveTrace) Descriptor() ([]byte, []int) {
	return file_v1_Stat_proto_rawDescGZIP(), []int{18}
}

func (x *PActiveTrace) GetHistogram() *PActiveTraceHistogram {
	if x != nil {
		return x.Histogram
	}
	return nil
}

type PResponseTime struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Avg           int64                  `protobuf:"varint,1,opt,name=avg,proto3" json:"avg,omitempty"`
	Max           int64                  `protobuf:"varint,2,opt,name=max,proto3" json:"max,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PResponseTime) Reset() {
	*x = PResponseTime{}
	mi := &file_v1_Stat_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PResponseTime) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PResponseTime) ProtoMessage() {}

func (x *PResponseTime) ProtoReflect() protoreflect.Message {
	mi := &file_v1_Stat_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PResponseTime.ProtoReflect.Descriptor instead.
func (*PResponseTime) Descriptor() ([]byte, []int) {
	return file_v1_Stat_proto_rawDescGZIP(), []int{19}
}

func (x *PResponseTime) GetAvg() int64 {
	if x != nil {
		return x.Avg
	}
	return 0
}

func (x *PResponseTime) GetMax() int64 {
	if x != nil {
		return x.Max
	}
	return 0
}

type PDeadlock struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         int32                  `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	ThreadDump    []*PThreadDump         `protobuf:"bytes,2,rep,name=threadDump,proto3" json:"threadDump,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PDeadlock) Reset() {
	*x = PDeadlock{}
	mi := &file_v1_Stat_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PDeadlock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PDeadlock) ProtoMessage() {}

func (x *PDeadlock) ProtoReflect() protoreflect.Message {
	mi := &file_v1_Stat_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PDeadlock.ProtoReflect.Descriptor instead.
func (*PDeadlock) Descriptor() ([]byte, []int) {
	return file_v1_Stat_proto_rawDescGZIP(), []int{20}
}

func (x *PDeadlock) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *PDeadlock) GetThreadDump() []*PThreadDump {
	if x != nil {
		return x.ThreadDump
	}
	return nil
}

type PDirectBuffer struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	DirectCount      int64                  `protobuf:"varint,1,opt,name=directCount,proto3" json:"directCount,omitempty"`
	DirectMemoryUsed int64                  `protobuf:"varint,2,opt,name=directMemoryUsed,proto3" json:"directMemoryUsed,omitempty"`
	MappedCount      int64                  `protobuf:"varint,3,opt,name=mappedCount,proto3" json:"mappedCount,omitempty"`
	MappedMemoryUsed int64                  `protobuf:"varint,4,opt,name=mappedMemoryUsed,proto3" json:"mappedMemoryUsed,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PDirectBuffer) Reset() {
	*x = PDirectBuffer{}
	mi := &file_v1_Stat_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PDirectBuffer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PDirectBuffer) ProtoMessage() {}

func (x *PDirectBuffer) ProtoReflect() protoreflect.Message {
	mi := &file_v1_Stat_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PDirectBuffer.ProtoReflect.Descriptor instead.
func (*PDirectBuffer) Descriptor() ([]byte, []int) {
	return file_v1_Stat_proto_rawDescGZIP(), []int{21}
}

func (x *PDirectBuffer) GetDirectCount() int64 {
	if x != nil {
		return x.DirectCount
	}
	return 0
}

func (x *PDirectBuffer) GetDirectMemoryUsed() int64 {
	if x != nil {
		return x.DirectMemoryUsed
	}
	return 0
}

func (x *PDirectBuffer) GetMappedCount() int64 {
	if x != nil {
		return x.MappedCount
	}
	return 0
}

func (x *PDirectBuffer) GetMappedMemoryUsed() int64 {
	if x != nil {
		return x.MappedMemoryUsed
	}
	return 0
}

type PTotalThread struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	TotalThreadCount int64                  `protobuf:"varint,1,opt,name=totalThreadCount,proto3" json:"totalThreadCount,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PTotalThread) Reset() {
	*x = PTotalThread{}
	mi := &file_v1_Stat_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PTotalThread) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PTotalThread) ProtoMessage() {}

func (x *PTotalThread) ProtoReflect() protoreflect.Message {
	mi := &file_v1_Stat_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PTotalThread.ProtoReflect.Descriptor instead.
func (*PTotalThread) Descriptor() ([]byte, []int) {
	return file_v1_Stat_proto_rawDescGZIP(), []int{22}
}

func (x *PTotalThread) GetTotalThreadCount() int64 {
	if x != nil {
		return x.TotalThreadCount
	}
	return 0
}

type PLoadedClass struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	LoadedClassCount   int64                  `protobuf:"varint,1,opt,name=loadedClassCount,proto3" json:"loadedClassCount,omitempty"`
	UnloadedClassCount int64                  `protobuf:"varint,2,opt,name=unloadedClassCount,proto3" json:"unloadedClassCount,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *PLoadedClass) Reset() {
	*x = PLoadedClass{}
	mi := &file_v1_Stat_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PLoadedClass) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PLoadedClass) ProtoMessage() {}

func (x *PLoadedClass) ProtoReflect() protoreflect.Message {
	mi := &file_v1_Stat_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PLoadedClass.ProtoReflect.Descriptor instead.
func (*PLoadedClass) Descriptor() ([]byte, []int) {
	return file_v1_Stat_proto_rawDescGZIP(), []int{23}
}

func (x *PLoadedClass) GetLoadedClassCount() int64 {
	if x != nil {
		return x.LoadedClassCount
	}
	return 0
}

func (x *PLoadedClass) GetUnloadedClassCount() int64 {
	if x != nil {
		return x.UnloadedClassCount
	}
	return 0
}

type PAgentUriStat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BucketVersion int32                  `protobuf:"varint,1,opt,name=bucketVersion,proto3" json:"bucketVersion,omitempty"`
	EachUriStat   []*PEachUriStat        `protobuf:"bytes,2,rep,name=eachUriStat,proto3" json:"eachUriStat,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PAgentUriStat) Reset() {
	*x = PAgentUriStat{}
	mi := &file_v1_Stat_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PAgentUriStat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PAgentUriStat) ProtoMessage() {}

func (x *PAgentUriStat) ProtoReflect() protoreflect.Message {
	mi := &file_v1_Stat_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PAgentUriStat.ProtoReflect.Descriptor instead.
func (*PAgentUriStat) Descriptor() ([]byte, []int) {
	return file_v1_Stat_proto_rawDescGZIP(), []int{24}
}

func (x *PAgentUriStat) GetBucketVersion() int32 {
	if x != nil {
		return x.BucketVersion
	}
	return 0
}

func (x *PAgentUriStat) GetEachUriStat() []*PEachUriStat {
	if x != nil {
		return x.EachUriStat
	}
	return nil
}

type PEachUriStat struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Uri             string                 `protobuf:"bytes,1,opt,name=uri,proto3" json:"uri,omitempty"`
	TotalHistogram  *PUriHistogram         `protobuf:"bytes,2,opt,name=totalHistogram,proto3" json:"totalHistogram,omitempty"`
	FailedHistogram *PUriHistogram         `protobuf:"bytes,3,opt,name=failedHistogram,proto3" json:"failedHistogram,omitempty"`
	Timestamp       int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PEachUriStat) Reset() {
	*x = PEachUriStat{}
	mi := &file_v1_Stat_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PEachUriStat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PEachUriStat) ProtoMessage() {}

func (x *PEachUriStat) ProtoReflect() protoreflect.Message {
	mi := &file_v1_Stat_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PEachUriStat.ProtoReflect.Descriptor instead.
func (*PEachUriStat) Descriptor() ([]byte, []int) {
	return file_v1_Stat_proto_rawDescGZIP(), []int{25}
}

func (x *PEachUriStat) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

func (x *PEachUriStat) GetTotalHistogram() *PUriHistogram {
	if x != nil {
		return x.TotalHistogram
	}
	return nil
}

func (x *PEachUriStat) GetFailedHistogram() *PUriHistogram {
	if x != nil {
		return x.FailedHistogram
	}
	return nil
}

func (x *PEachUriStat) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type PUriHistogram struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int64                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Max           int64                  `protobuf:"varint,2,opt,name=max,proto3" json:"max,omitempty"`
	Histogram     []int32                `protobuf:"varint,3,rep,packed,name=histogram,proto3" json:"histogram,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PUriHistogram) Reset() {
	*x = PUriHistogram{}
	mi := &file_v1_Stat_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PUriHistogram) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PUriHistogram) ProtoMessage() {}

func (x *PUriHistogram) ProtoReflect() protoreflect.Message {
	mi := &file_v1_Stat_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PUriHistogram.ProtoReflect.Descriptor instead.
func (*PUriHistogram) Descriptor() ([]byte, []int) {
	return file_v1_Stat_proto_rawDescGZIP(), []int{26}
}

func (x *PUriHistogram) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *PUriHistogram) GetMax() int64 {
	if x != nil {
		return x.Max
	}
	return 0
}

func (x *PUriHistogram) GetHistogram() []int32 {
	if x != nil {
		return x.Histogram
	}
	return nil
}

var File_v1_Stat_proto protoreflect.FileDescriptor

const file_v1_Stat_proto_rawDesc = "" +
	"\n" +
	"\rv1/Stat.proto\x12\x02v1\x1a\x13v1/ThreadDump.proto\"\a\n" +
	"\x05PPing\"\xfe\x01\n" +
	"\fPStatMessage\x12.\n" +
	"\tagentStat\x18\x01 \x01(\v2\x0e.v1.PAgentStatH\x00R\tagentStat\x12=\n" +
	"\x0eagentStatBatch\x18\x02 \x01(\v2\x13.v1.PAgentStatBatchH\x00R\x0eagentStatBatch\x127\n" +
	"\fagentUriStat\x18\x03 \x01(\v2\x11.v1.PAgentUriStatH\x00R\fagentUriStat\x12=\n" +
	"\x0eprofilerMetric\x18\x04 \x01(\v2\x13.v1.PProfilerMetricH\x00R\x0eprofilerMetricB\a\n" +
	"\x05field\"\x89\x03\n" +
	"\n" +
	"PAgentInfo\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\x12\x0e\n" +
	"\x02ip\x18\x02 \x01(\tR\x02ip\x12\x14\n" +
	"\x05ports\x18\x03 \x01(\tR\x05ports\x12 \n" +
	"\vserviceType\x18\x04 \x01(\x05R\vserviceType\x12\x10\n" +
	"\x03pid\x18\x05 \x01(\x05R\x03pid\x12\"\n" +
	"\fagentVersion\x18\x06 \x01(\tR\fagentVersion\x12\x1c\n" +
	"\tvmVersion\x18\a \x01(\tR\tvmVersion\x12\"\n" +
	"\fendTimestamp\x18\b \x01(\x03R\fendTimestamp\x12\x1c\n" +
	"\tendStatus\x18\t \x01(\x05R\tendStatus\x12;\n" +
	"\x0eserverMetaData\x18\n" +
	" \x01(\v2\x13.v1.PServerMetaDataR\x0eserverMetaData\x12&\n" +
	"\ajvmInfo\x18\v \x01(\v2\f.v1.PJvmInfoR\ajvmInfo\x12\x1c\n" +
	"\tcontainer\x18\f \x01(\bR\tcontainer\"{\n" +
	"\x0fPServerMetaData\x12\x1e\n" +
	"\n" +
	"serverInfo\x18\x01 \x01(\tR\n" +
	"serverInfo\x12\x14\n" +
	"\x05vmArg\x18\x02 \x03(\tR\x05vmArg\x122\n" +
	"\vserviceInfo\x18\x03 \x03(\v2\x10.v1.PServiceInfoR\vserviceInfo\"P\n" +
	"\fPServiceInfo\x12 \n" +
	"\vserviceName\x18\x01 \x01(\tR\vserviceName\x12\x1e\n" +
	"\n" +
	"serviceLib\x18\x02 \x03(\tR\n" +
	"serviceLib\"j\n" +
	"\bPJvmInfo\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x05R\aversion\x12\x1c\n" +
	"\tvmVersion\x18\x02 \x01(\tR\tvmVersion\x12&\n" +
	"\x06gcType\x18\x03 \x01(\x0e2\x0e.v1.PJvmGcTypeR\x06gcType\"\x97\x05\n" +
	"\n" +
	"PAgentStat\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\x12(\n" +
	"\x0fcollectInterval\x18\x02 \x01(\x03R\x0fcollectInterval\x12\x1a\n" +
	"\x02gc\x18\x03 \x01(\v2\n" +
	".v1.PJvmGcR\x02gc\x12&\n" +
	"\acpuLoad\x18\x04 \x01(\v2\f.v1.PCpuLoadR\acpuLoad\x122\n" +
	"\vtransaction\x18\x05 \x01(\v2\x10.v1.PTransactionR\vtransaction\x122\n" +
	"\vactiveTrace\x18\x06 \x01(\v2\x10.v1.PActiveTraceR\vactiveTrace\x12;\n" +
	"\x0edataSourceList\x18\a \x01(\v2\x13.v1.PDataSourceListR\x0edataSourceList\x125\n" +
	"\fresponseTime\x18\b \x01(\v2\x11.v1.PResponseTimeR\fresponseTime\x12)\n" +
	"\bdeadlock\x18\t \x01(\v2\r.v1.PDeadlockR\bdeadlock\x12;\n" +
	"\x0efileDescriptor\x18\n" +
	" \x01(\v2\x13.v1.PFileDescriptorR\x0efileDescriptor\x125\n" +
	"\fdirectBuffer\x18\v \x01(\v2\x11.v1.PDirectBufferR\fdirectBuffer\x12\x1a\n" +
	"\bmetadata\x18\f \x01(\tR\bmetadata\x122\n" +
	"\vtotalThread\x18\r \x01(\v2\x10.v1.PTotalThreadR\vtotalThread\x122\n" +
	"\vloadedClass\x18\x0e \x01(\v2\x10.v1.PLoadedClassR\vloadedClass\"\xcd\x01\n" +
	"\x0fPProfilerMetric\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\x12(\n" +
	"\x0fcollectInterval\x18\x02 \x01(\x03R\x0fcollectInterval\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x120\n" +
	"\x06fields\x18\x04 \x03(\v2\x18.v1.PProfilerMetricFieldR\x06fields\x12,\n" +
	"\x04tags\x18\x05 \x03(\v2\x18.v1.PProfilerMetricFieldR\x04tags\"w\n" +
	"\x14PProfilerMetricField\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\"\n" +
	"\vstringValue\x18\x02 \x01(\tH\x00R\vstringValue\x12\x1e\n" +
	"\tlongValue\x18\x03 \x01(\x03H\x00R\tlongValueB\a\n" +
	"\x05value\"?\n" +
	"\x0fPAgentStatBatch\x12,\n" +
	"\tagentStat\x18\x01 \x03(\v2\x0e.v1.PAgentStatR\tagentStat\"\xdf\x01\n" +
	"\vPDataSource\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12(\n" +
	"\x0fserviceTypeCode\x18\x02 \x01(\x05R\x0fserviceTypeCode\x12\"\n" +
	"\fdatabaseName\x18\x03 \x01(\tR\fdatabaseName\x12\x10\n" +
	"\x03url\x18\x04 \x01(\tR\x03url\x122\n" +
	"\x14activeConnectionSize\x18\x05 \x01(\x05R\x14activeConnectionSize\x12,\n" +
	"\x11maxConnectionSize\x18\x06 \x01(\x05R\x11maxConnectionSize\"B\n" +
	"\x0fPDataSourceList\x12/\n" +
	"\n" +
	"dataSource\x18\x01 \x03(\v2\x0f.v1.PDataSourceR\n" +
	"dataSource\"K\n" +
	"\x0fPFileDescriptor\x128\n" +
	"\x17openFileDescriptorCount\x18\x01 \x01(\x03R\x17openFileDescriptorCount\"\xf0\x02\n" +
	"\x06PJvmGc\x12\"\n" +
	"\x04type\x18\x01 \x01(\x0e2\x0e.v1.PJvmGcTypeR\x04type\x12,\n" +
	"\x11jvmMemoryHeapUsed\x18\x02 \x01(\x03R\x11jvmMemoryHeapUsed\x12*\n" +
	"\x10jvmMemoryHeapMax\x18\x03 \x01(\x03R\x10jvmMemoryHeapMax\x122\n" +
	"\x14jvmMemoryNonHeapUsed\x18\x04 \x01(\x03R\x14jvmMemoryNonHeapUsed\x120\n" +
	"\x13jvmMemoryNonHeapMax\x18\x05 \x01(\x03R\x13jvmMemoryNonHeapMax\x12$\n" +
	"\rjvmGcOldCount\x18\x06 \x01(\x03R\rjvmGcOldCount\x12\"\n" +
	"\fjvmGcOldTime\x18\a \x01(\x03R\fjvmGcOldTime\x128\n" +
	"\rjvmGcDetailed\x18\b \x01(\v2\x12.v1.PJvmGcDetailedR\rjvmGcDetailed\"\x8a\x03\n" +
	"\x0ePJvmGcDetailed\x12$\n" +
	"\rjvmGcNewCount\x18\x01 \x01(\x03R\rjvmGcNewCount\x12\"\n" +
	"\fjvmGcNewTime\x18\x02 \x01(\x03R\fjvmGcNewTime\x122\n" +
	"\x14jvmPoolCodeCacheUsed\x18\x03 \x01(\x01R\x14jvmPoolCodeCacheUsed\x12,\n" +
	"\x11jvmPoolNewGenUsed\x18\x04 \x01(\x01R\x11jvmPoolNewGenUsed\x12,\n" +
	"\x11jvmPoolOldGenUsed\x18\x05 \x01(\x01R\x11jvmPoolOldGenUsed\x12:\n" +
	"\x18jvmPoolSurvivorSpaceUsed\x18\x06 \x01(\x01R\x18jvmPoolSurvivorSpaceUsed\x12.\n" +
	"\x12jvmPoolPermGenUsed\x18\a \x01(\x01R\x12jvmPoolPermGenUsed\x122\n" +
	"\x14jvmPoolMetaspaceUsed\x18\b \x01(\x01R\x14jvmPoolMetaspaceUsed\"P\n" +
	"\bPCpuLoad\x12\x1e\n" +
	"\n" +
	"jvmCpuLoad\x18\x01 \x01(\x01R\n" +
	"jvmCpuLoad\x12$\n" +
	"\rsystemCpuLoad\x18\x02 \x01(\x01R\rsystemCpuLoad\"\xc8\x02\n" +
	"\fPTransaction\x12(\n" +
	"\x0fsampledNewCount\x18\x02 \x01(\x03R\x0fsampledNewCount\x12:\n" +
	"\x18sampledContinuationCount\x18\x03 \x01(\x03R\x18sampledContinuationCount\x12,\n" +
	"\x11unsampledNewCount\x18\x04 \x01(\x03R\x11unsampledNewCount\x12>\n" +
	"\x1aunsampledContinuationCount\x18\x05 \x01(\x03R\x1aunsampledContinuationCount\x12(\n" +
	"\x0fskippedNewCount\x18\x06 \x01(\x03R\x0fskippedNewCount\x12:\n" +
	"\x18skippedContinuationCount\x18\a \x01(\x03R\x18skippedContinuationCount\"\x8f\x01\n" +
	"\x15PActiveTraceHistogram\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x05R\aversion\x120\n" +
	"\x13histogramSchemaType\x18\x02 \x01(\x05R\x13histogramSchemaType\x12*\n" +
	"\x10activeTraceCount\x18\x03 \x03(\x05R\x10activeTraceCount\"G\n" +
	"\fPActiveTrace\x127\n" +
	"\thistogram\x18\x01 \x01(\v2\x19.v1.PActiveTraceHistogramR\thistogram\"3\n" +
	"\rPResponseTime\x12\x10\n" +
	"\x03avg\x18\x01 \x01(\x03R\x03avg\x12\x10\n" +
	"\x03max\x18\x02 \x01(\x03R\x03max\"R\n" +
	"\tPDeadlock\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x05R\x05count\x12/\n" +
	"\n" +
	"threadDump\x18\x02 \x03(\v2\x0f.v1.PThreadDumpR\n" +
	"threadDump\"\xab\x01\n" +
	"\rPDirectBuffer\x12 \n" +
	"\vdirectCount\x18\x01 \x01(\x03R\vdirectCount\x12*\n" +
	"\x10directMemoryUsed\x18\x02 \x01(\x03R\x10directMemoryUsed\x12 \n" +
	"\vmappedCount\x18\x03 \x01(\x03R\vmappedCount\x12*\n" +
	"\x10mappedMemoryUsed\x18\x04 \x01(\x03R\x10mappedMemoryUsed\":\n" +
	"\fPTotalThread\x12*\n" +
	"\x10totalThreadCount\x18\x01 \x01(\x03R\x10totalThreadCount\"j\n" +
	"\fPLoadedClass\x12*\n" +
	"\x10loadedClassCount\x18\x01 \x01(\x03R\x10loadedClassCount\x12.\n" +
	"\x12unloadedClassCount\x18\x02 \x01(\x03R\x12unloadedClassCount\"i\n" +
	"\rPAgentUriStat\x12$\n" +
	"\rbucketVersion\x18\x01 \x01(\x05R\rbucketVersion\x122\n" +
	"\veachUriStat\x18\x02 \x03(\v2\x10.v1.PEachUriStatR\veachUriStat\"\xb6\x01\n" +
	"\fPEachUriStat\x12\x10\n" +
	"\x03uri\x18\x01 \x01(\tR\x03uri\x129\n" +
	"\x0etotalHistogram\x18\x02 \x01(\v2\x11.v1.PUriHistogramR\x0etotalHistogram\x12;\n" +
	"\x0ffailedHistogram\x18\x03 \x01(\v2\x11.v1.PUriHistogramR\x0ffailedHistogram\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\"U\n" +
	"\rPUriHistogram\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x03R\x05total\x12\x10\n" +
	"\x03max\x18\x02 \x01(\x03R\x03max\x12\x1c\n" +
	"\thistogram\x18\x03 \x03(\x05R\thistogram*\x95\x01\n" +
	"\n" +
	"PJvmGcType\x12\x17\n" +
	"\x13JVM_GC_TYPE_UNKNOWN\x10\x00\x12\x16\n" +
	"\x12JVM_GC_TYPE_SERIAL\x10\x01\x12\x18\n" +
	"\x14JVM_GC_TYPE_PARALLEL\x10\x02\x12\x13\n" +
	"\x0fJVM_GC_TYPE_CMS\x10\x03\x12\x12\n" +
	"\x0eJVM_GC_TYPE_G1\x10\x04\x12\x13\n" +
	"\x0fJVM_GC_TYPE_ZGC\x10\x05B5\n" +
	"!com.navercorp.pinpoint.grpc.traceB\tStatProtoP\x01Z\x03/v1b\x06proto3"

var (
	file_v1_Stat_proto_rawDescOnce sync.Once
	file_v1_Stat_proto_rawDescData []byte
)

func file_v1_Stat_proto_rawDescGZIP() []byte {
	file_v1_Stat_proto_rawDescOnce.Do(func() {
		file_v1_Stat_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_Stat_proto_rawDesc), len(file_v1_Stat_proto_rawDesc)))
	})
	return file_v1_Stat_proto_rawDescData
}

var file_v1_Stat_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_v1_Stat_proto_msgTypes = make([]protoimpl.MessageInfo, 27)
var file_v1_Stat_proto_goTypes = []any{
	(PJvmGcType)(0),               // 0: v1.PJvmGcType
	(*PPing)(nil),                 // 1: v1.PPing
	(*PStatMessage)(nil),          // 2: v1.PStatMessage
	(*PAgentInfo)(nil),            // 3: v1.PAgentInfo
	(*PServerMetaData)(nil),       // 4: v1.PServerMetaData
	(*PServiceInfo)(nil),          // 5: v1.PServiceInfo
	(*PJvmInfo)(nil),              // 6: v1.PJvmInfo
	(*PAgentStat)(nil),            // 7: v1.PAgentStat
	(*PProfilerMetric)(nil),       // 8: v1.PProfilerMetric
	(*PProfilerMetricField)(nil),  // 9: v1.PProfilerMetricField
	(*PAgentStatBatch)(nil),       // 10: v1.PAgentStatBatch
	(*PDataSource)(nil),           // 11: v1.PDataSource
	(*PDataSourceList)(nil),       // 12: v1.PDataSourceList
	(*PFileDescriptor)(nil),       // 13: v1.PFileDescriptor
	(*PJvmGc)(nil),                // 14: v1.PJvmGc
	(*PJvmGcDetailed)(nil),        // 15: v1.PJvmGcDetailed
	(*PCpuLoad)(nil),              // 16: v1.PCpuLoad
	(*PTransaction)(nil),          // 17: v1.PTransaction
	(*PActiveTraceHistogram)(nil), // 18: v1.PActiveTraceHistogram
	(*PActiveTrace)(nil),          // 19: v1.PActiveTrace
	(*PResponseTime)(nil),         // 20: v1.PResponseTime
	(*PDeadlock)(nil),             // 21: v1.PDeadlock
	(*PDirectBuffer)(nil),         // 22: v1.PDirectBuffer
	(*PTotalThread)(nil),          // 23: v1.PTotalThread
	(*PLoadedClass)(nil),          // 24: v1.PLoadedClass
	(*PAgentUriStat)(nil),         // 25: v1.PAgentUriStat
	(*PEachUriStat)(nil),          // 26: v1.PEachUriStat
	(*PUriHistogram)(nil),         // 27: v1.PUriHistogram
	(*PThreadDump)(nil),           // 28: v1.PThreadDump
}
var file_v1_Stat_proto_depIdxs = []int32{
	7,  // 0: v1.PStatMessage.agentStat:type_name -> v1.PAgentStat
	10, // 1: v1.PStatMessage.agentStatBatch:type_name -> v1.PAgentStatBatch
	25, // 2: v1.PStatMessage.agentUriStat:type_name -> v1.PAgentUriStat
	8,  // 3: v1.PStatMessage.profilerMetric:type_name -> v1.PProfilerMetric
	4,  // 4: v1.PAgentInfo.serverMetaData:type_name -> v1.PServerMetaData
	6,  // 5: v1.PAgentInfo.jvmInfo:type_name -> v1.PJvmInfo
	5,  // 6: v1.PServerMetaData.serviceInfo:type_name -> v1.PServiceInfo
	0,  // 7: v1.PJvmInfo.gcType:type_name -> v1.PJvmGcType
	14, // 8: v1.PAgentStat.gc:type_name -> v1.PJvmGc
	16, // 9: v1.PAgentStat.cpuLoad:type_name -> v1.PCpuLoad
	17, // 10: v1.PAgentStat.transaction:type_name -> v1.PTransaction
	19, // 11: v1.PAgentStat.activeTrace:type_name -> v1.PActiveTrace
	12, // 12: v1.PAgentStat.dataSourceList:type_name -> v1.PDataSourceList
	20, // 13: v1.PAgentStat.responseTime:type_name -> v1.PResponseTime
	21, // 14: v1.PAgentStat.deadlock:type_name -> v1.PDeadlock
	13, // 15: v1.PAgentStat.fileDescriptor:type_name -> v1.PFileDescriptor
	22, // 16: v1.PAgentStat.directBuffer:type_name -> v1.PDirectBuffer
	23, // 17: v1.PAgentStat.totalThread:type_name -> v1.PTotalThread
	24, // 18: v1.PAgentStat.loadedClass:type_name -> v1.PLoadedClass
	9,  // 19: v1.PProfilerMetric.fields:type_name -> v1.PProfilerMetricField
	9,  // 20: v1.PProfilerMetric.tags:type_name -> v1.PProfilerMetricField
	7,  // 21: v1.PAgentStatBatch.agentStat:type_name -> v1.PAgentStat
	11, // 22: v1.PDataSourceList.dataSource:type_name -> v1.PDataSource
	0,  // 23: v1.PJvmGc.type:type_name -> v1.PJvmGcType
	15, // 24: v1.PJvmGc.jvmGcDetailed:type_name -> v1.PJvmGcDetailed
	18, // 25: v1.PActiveTrace.histogram:type_name -> v1.PActiveTraceHistogram
	28, // 26: v1.PDeadlock.threadDump:type_name -> v1.PThreadDump
	26, // 27: v1.PAgentUriStat.eachUriStat:type_name -> v1.PEachUriStat
	27, // 28: v1.PEachUriStat.totalHistogram:type_name -> v1.PUriHistogram
	27, // 29: v1.PEachUriStat.failedHistogram:type_name -> v1.PUriHistogram
	30, // [30:30] is the sub-list for method output_type
	30, // [30:30] is the sub-list for method input_type
	30, // [30:30] is the sub-list for extension type_name
	30, // [30:30] is the sub-list for extension extendee
	0,  // [0:30] is the sub-list for field type_name
}

func init() { file_v1_Stat_proto_init() }
func file_v1_Stat_proto_init() {
	if File_v1_Stat_proto != nil {
		return
	}
	file_v1_ThreadDump_proto_init()
	file_v1_Stat_proto_msgTypes[1].OneofWrappers = []any{
		(*PStatMessage_AgentStat)(nil),
		(*PStatMessage_AgentStatBatch)(nil),
		(*PStatMessage_AgentUriStat)(nil),
		(*PStatMessage_ProfilerMetric)(nil),
	}
	file_v1_Stat_proto_msgTypes[8].OneofWrappers = []any{
		(*PProfilerMetricField_StringValue)(nil),
		(*PProfilerMetricField_LongValue)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_Stat_proto_rawDesc), len(file_v1_Stat_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   27,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1_Stat_proto_goTypes,
		DependencyIndexes: file_v1_Stat_proto_depIdxs,
		EnumInfos:         file_v1_Stat_proto_enumTypes,
		MessageInfos:      file_v1_Stat_proto_msgTypes,
	}.Build()
	File_v1_Stat_proto = out.File
	file_v1_Stat_proto_goTypes = nil
	file_v1_Stat_proto_depIdxs = nil
}
