// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.36.1
// source: testapp.proto

package testapp

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Greeting struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Msg           string                 `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Greeting) Reset() {
	*x = Greeting{}
	mi := &file_testapp_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Greeting) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Greeting) ProtoMessage() {}

func (x *Greeting) ProtoReflect() protoreflect.Message {
	mi := &file_testapp_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Greeting.ProtoReflect.Descriptor instead.
func (*Greeting) Descriptor() ([]byte, []int) {
	return file_testapp_proto_rawDescGZIP(), []int{0}
}

func (x *Greeting) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_testapp_proto protoreflect.FileDescriptor

const file_testapp_proto_rawDesc = "" +
	"\n" +
	"\rtestapp.proto\"\x1c\n" +
	"\bGreeting\x12\x10\n" +
	"\x03msg\x18\x01 \x01(\tR\x03msg2\xd3\x01\n" +
	"\x05Hello\x12.\n" +
	"\x14UnaryCallUnaryReturn\x12\t.Greeting\x1a\t.Greeting\"\x00\x121\n" +
	"\x15UnaryCallStreamReturn\x12\t.Greeting\x1a\t.Greeting\"\x000\x01\x121\n" +
	"\x15StreamCallUnaryReturn\x12\t.Greeting\x1a\t.Greeting\"\x00(\x01\x124\n" +
	"\x16StreamCallStreamReturn\x12\t.Greeting\x1a\t.Greeting\"\x00(\x010\x01B;Z9github.com/pinpoint-apm/pinpoint-go-agent/v2/test/testappb\x06proto3"

var (
	file_testapp_proto_rawDescOnce sync.Once
	file_testapp_proto_rawDescData []byte
)

func file_testapp_proto_rawDescGZIP() []byte {
	file_testapp_proto_rawDescOnce.Do(func() {
		file_testapp_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_testapp_proto_rawDesc), len(file_testapp_proto_rawDesc)))
	})
	return file_testapp_proto_rawDescData
}

var file_testapp_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_testapp_proto_goTypes = []any{
	(*Greeting)(nil), // 0: Greeting
}
var file_testapp_proto_depIdxs = []int32{
	0, // 0: Hello.UnaryCallUnaryReturn:input_type -> Greeting
	0, // 1: Hello.UnaryCallStreamReturn:input_type -> Greeting
	0, // 2: Hello.StreamCallUnaryReturn:input_type -> Greeting
	0, // 3: Hello.StreamCallStreamReturn:input_type -> Greeting
	0, // 4: Hello.UnaryCallUnaryReturn:output_type -> Greeting
	0, // 5: Hello.UnaryCallStreamReturn:output_type -> Greeting
	0, // 6: Hello.StreamCallUnaryReturn:output_type -> Greeting
	0, // 7: Hello.StreamCallStreamReturn:output_type -> Greeting
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_testapp_proto_init() }
func file_testapp_proto_init() {
	if File_testapp_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_testapp_proto_rawDesc), len(file_testapp_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_testapp_proto_goTypes,
		DependencyIndexes: file_testapp_proto_depIdxs,
		MessageInfos:      file_testapp_proto_msgTypes,
	}.Build()
	File_testapp_proto = out.File
	file_testapp_proto_goTypes = nil
	file_testapp_proto_depIdxs = nil
}
