// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.36.1
// source: testapp.proto

package testapp

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Hello_UnaryCallUnaryReturn_FullMethodName   = "/Hello/UnaryCallUnaryReturn"
	Hello_UnaryCallStreamReturn_FullMethodName  = "/Hello/UnaryCallStreamReturn"
	Hello_StreamCallUnaryReturn_FullMethodName  = "/Hello/StreamCallUnaryReturn"
	Hello_StreamCallStreamReturn_FullMethodName = "/Hello/StreamCallStreamReturn"
)

// HelloClient is the client API for Hello service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HelloClient interface {
	UnaryCallUnaryReturn(ctx context.Context, in *Greeting, opts ...grpc.CallOption) (*Greeting, error)
	UnaryCallStreamReturn(ctx context.Context, in *Greeting, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Greeting], error)
	StreamCallUnaryReturn(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[Greeting, Greeting], error)
	StreamCallStreamReturn(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Greeting, Greeting], error)
}

type helloClient struct {
	cc grpc.ClientConnInterface
}

func NewHelloClient(cc grpc.ClientConnInterface) HelloClient {
	return &helloClient{cc}
}

func (c *helloClient) UnaryCallUnaryReturn(ctx context.Context, in *Greeting, opts ...grpc.CallOption) (*Greeting, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Greeting)
	err := c.cc.Invoke(ctx, Hello_UnaryCallUnaryReturn_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *helloClient) UnaryCallStreamReturn(ctx context.Context, in *Greeting, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Greeting], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Hello_ServiceDesc.Streams[0], Hello_UnaryCallStreamReturn_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Greeting, Greeting]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Hello_UnaryCallStreamReturnClient = grpc.ServerStreamingClient[Greeting]

func (c *helloClient) StreamCallUnaryReturn(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[Greeting, Greeting], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Hello_ServiceDesc.Streams[1], Hello_StreamCallUnaryReturn_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Greeting, Greeting]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Hello_StreamCallUnaryReturnClient = grpc.ClientStreamingClient[Greeting, Greeting]

func (c *helloClient) StreamCallStreamReturn(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Greeting, Greeting], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Hello_ServiceDesc.Streams[2], Hello_StreamCallStreamReturn_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Greeting, Greeting]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Hello_StreamCallStreamReturnClient = grpc.BidiStreamingClient[Greeting, Greeting]

// HelloServer is the server API for Hello service.
// All implementations must embed UnimplementedHelloServer
// for forward compatibility.
type HelloServer interface {
	UnaryCallUnaryReturn(context.Context, *Greeting) (*Greeting, error)
	UnaryCallStreamReturn(*Greeting, grpc.ServerStreamingServer[Greeting]) error
	StreamCallUnaryReturn(grpc.ClientStreamingServer[Greeting, Greeting]) error
	StreamCallStreamReturn(grpc.BidiStreamingServer[Greeting, Greeting]) error
	mustEmbedUnimplementedHelloServer()
}

// UnimplementedHelloServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHelloServer struct{}

func (UnimplementedHelloServer) UnaryCallUnaryReturn(context.Context, *Greeting) (*Greeting, error) {
	return nil, status.Error(codes.Unimplemented, "method UnaryCallUnaryReturn not implemented")
}
func (UnimplementedHelloServer) UnaryCallStreamReturn(*Greeting, grpc.ServerStreamingServer[Greeting]) error {
	return status.Error(codes.Unimplemented, "method UnaryCallStreamReturn not implemented")
}
func (UnimplementedHelloServer) StreamCallUnaryReturn(grpc.ClientStreamingServer[Greeting, Greeting]) error {
	return status.Error(codes.Unimplemented, "method StreamCallUnaryReturn not implemented")
}
func (UnimplementedHelloServer) StreamCallStreamReturn(grpc.BidiStreamingServer[Greeting, Greeting]) error {
	return status.Error(codes.Unimplemented, "method StreamCallStreamReturn not implemented")
}
func (UnimplementedHelloServer) mustEmbedUnimplementedHelloServer() {}
func (UnimplementedHelloServer) testEmbeddedByValue()               {}

// UnsafeHelloServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HelloServer will
// result in compilation errors.
type UnsafeHelloServer interface {
	mustEmbedUnimplementedHelloServer()
}

func RegisterHelloServer(s grpc.ServiceRegistrar, srv HelloServer) {
	// If the following call panics, it indicates UnimplementedHelloServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Hello_ServiceDesc, srv)
}

func _Hello_UnaryCallUnaryReturn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Greeting)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HelloServer).UnaryCallUnaryReturn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Hello_UnaryCallUnaryReturn_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HelloServer).UnaryCallUnaryReturn(ctx, req.(*Greeting))
	}
	return interceptor(ctx, in, info, handler)
}

func _Hello_UnaryCallStreamReturn_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Greeting)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(HelloServer).UnaryCallStreamReturn(m, &grpc.GenericServerStream[Greeting, Greeting]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Hello_UnaryCallStreamReturnServer = grpc.ServerStreamingServer[Greeting]

func _Hello_StreamCallUnaryReturn_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(HelloServer).StreamCallUnaryReturn(&grpc.GenericServerStream[Greeting, Greeting]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Hello_StreamCallUnaryReturnServer = grpc.ClientStreamingServer[Greeting, Greeting]

func _Hello_StreamCallStreamReturn_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(HelloServer).StreamCallStreamReturn(&grpc.GenericServerStream[Greeting, Greeting]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Hello_StreamCallStreamReturnServer = grpc.BidiStreamingServer[Greeting, Greeting]

// Hello_ServiceDesc is the grpc.ServiceDesc for Hello service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Hello_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Hello",
	HandlerType: (*HelloServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UnaryCallUnaryReturn",
			Handler:    _Hello_UnaryCallUnaryReturn_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "UnaryCallStreamReturn",
			Handler:       _Hello_UnaryCallStreamReturn_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamCallUnaryReturn",
			Handler:       _Hello_StreamCallUnaryReturn_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "StreamCallStreamReturn",
			Handler:       _Hello_StreamCallStreamReturn_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "testapp.proto",
}
